### ISSUE TITLE
Logging not working from bound service running in its own process

### ISSUE THREAD

**Issue by hirschbp** [DataDog/dd-sdk-android#1019]
**Describe what happened**
Logs aren't sent to Datadog backend when using the library in a bound service which is running in its own process. Actually there was no error printed on Logcat even with `Datadog.setVerbosity(Log.VERBOSE)`

**Steps to reproduce the issue:**

- Create a bound service which is running in its own process.
- in that bound service: initialize Datadog and create a new logger
- log sth with the logger

**Describe what you expected:**
- expected: The log is showing up on Datadog backend.
- actual: the logs are never send to the backend (when logging to Logcat is activated they are still printed to it). When changing the bound service to be running in the same process as the main application all logs are successfully sent to the Datadog backend.

**Additional context**
 - Android OS version: 12
 - Device Model: SM-G991B (Samsung S21)
 - Datadog SDK version: 1.13.0, 1.14.0-beta1
 - Gradle Plugins: dd-sdk-android-gradle-plugin:1.4.0

**Comment by xgouchet** [comment]
Hi @holoridePeter, one of the mechanism we use to ensure we handle multi-process application, is that only the main process of an application can upload data. The way we do this is that all tracked data is stored on disk, and is sent eventually, and in case of multi-process applications, we want to avoid two processes trying to send the same file concurrently. 
If only a background/bound service with a different process is running, it won't send data on its own, but as soon as the main process starts, it will upload any tracked files. The logs might not be sent immediately but they will be uploaded eventually.

**Comment by holoridePeter** [comment]
Thank you for your answer. Is this actually documented somewhere? So this basically means that the main application is forced to have a direct dependency on the Datadog library and needs to initialize it so that a bound service will be able to use it, right?

**Comment by xgouchet** [comment]
Just calling `Datadog.initialize()` will be enough for events to be sent indeed. We don't have official documentation, as usually we recommend to initialize the SDK in the application's `onCreate()` method, which will be called for all processes.

**Comment by xgouchet** [comment]
Indeed, the current architecture is not great for this use case. We are working on a version 2.0.0 with a new architecture that would be better suited for such a use case. 

I'll close the issue as the problem seems to be solved.
