### ISSUE TITLE
Missing view load time and resources report

### ISSUE THREAD

**Issue by pietrini** [DataDog/dd-sdk-android#1050]
Thanks for taking the time for reporting an issue!

**Describe what happened**
In session f971b727-a90f-4e67-be80-68ff9b627ed0 you can see that under the resources loaded, some of them are appearing under the "_home-feed/feed" view name. But if you take a look at the session, this view is never reported as loaded. I can't see my resources filtered by view as I can do with "_sync".
I'm not sure if I'm wrong with the setup or if I missed something. I used the debugger to see if the SDK works as expected and it seems it does. AndroidXFragmentLifecycleCallbacks reports everything as it should. And for instance I click somewhere, I can see that the click has been registered it's done inside the "_home-feed/feed".

**Steps to reproduce the issue:**
Track session using MixedViewTrackingStrategy, but with the navigation lib. As I saw in the lib code I do not think it's an issue.

**Describe what you expected:**
Being able to track all my views as the same.

**Additional context**
 - Android OS version: 12
 - Device Model: device simulator
 - Datadog SDK version: 1.14.0
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: none for debug
 - Gradle Plugins: not relevant

**Comment by xgouchet** [comment]
Hi @pietrini , we unfortunately don't have access to your sessions, can you show us screenshots that explain what you're seeing, vs what you expect to see? Another solution would be to report this directly to [our support](https://www.datadoghq.com/support/).

**Comment by pietrini** [comment]
Ah sorry! Yes, of course.

![Screen Shot 2022-09-20 at 21 11 01](https://user-images.githubusercontent.com/2203877/191344496-20b3f87e-71df-4ce6-9bcc-0f608581db6a.jpg)

![Screen Shot 2022-09-20 at 21 12 51](https://user-images.githubusercontent.com/2203877/191344493-4088dd24-a406-462e-9c06-2541c5bdad10.jpg)


As you can see the view "_home-feed/feed" is not present on the session list views.

**Comment by xgouchet** [comment]
Are you sure this `_home-feed/feed` view is part of that same session? When you click on the resource, you should have a link to go to that view, allowing you to see it. 
On a side note, can you share the code you use to configure the SDK?

**Comment by pietrini** [comment]
Yes, those screenshots were filtered with the corresponding session id.

This is my setup:

```
      val configuration = Configuration.Builder(
            logsEnabled = true,
            tracesEnabled = true,
            crashReportsEnabled = true,
            rumEnabled = true
        )
            .trackInteractions()
            .useSite(DatadogSite.US1)
            .setFirstPartyHosts(
                listOf(
                    ...
                )
            )
            .trackLongTasks(500L)
            .useViewTrackingStrategy(
                MixedViewTrackingStrategy(
                    componentPredicate = SpotMeAcceptAllActivities(),
                    supportFragmentComponentPredicate = SpotMeAcceptAllSupportFragments(),
                    trackExtras = true
                )
            )
            .build()
```

With:
```

class SpotMeAcceptAllActivities : AcceptAllActivities() {

    override fun getViewName(component: Activity): String? {
        return if (component is SpotMeDDNameProvider) {
            component.getViewName()
        } else {
            super.getViewName(component)
        }
    }
}

class SpotMeAcceptAllSupportFragments : AcceptAllSupportFragments() {

    override fun accept(component: Fragment): Boolean {
        return when (component) {
            is SupportRequestManagerFragment -> false
            is SpotMeNavHostFragment -> false
            is BottomNavigationNavFragment -> false
            else -> true
        }
    }

    override fun getViewName(component: Fragment): String? {
        return if (component is SpotMeDDNameProvider) {
            "_" + component.getViewName()
        } else {
            super.getViewName(component)
        }
    }
}

```

**Comment by xgouchet** [comment]
Can you add the following line next to the place where you initialize the SDK, and check if there are any warnings or errors showing in the logcat
```
Datadog.setVerbosity(Log.VERBOSE)
```

**Comment by pietrini** [comment]
I already checked the debug logs and this is what I found:

'''
09:22:54.099  W  A RUM event was detected, but no view is active. To track views automatically, try calling the Configuration.Builder.useViewTrackingStrategy() method.
                 You can also track views manually using the RumMonitor.startView() and RumMonitor.stopView() methods.
09:22:54.193  W  You added a TracingInterceptor to your OkHttpClient, but you didn't register any Tracer. We automatically created a local tracer for you.
09:22:54.651  W  You added a TracingInterceptor to your OkHttpClient, but you didn't register any Tracer. We automatically created a local tracer for you.
09:23:01.293  W  A RUM event was detected, but no view is active. To track views automatically, try calling the Configuration.Builder.useViewTrackingStrategy() method.
                 You can also track views manually using the RumMonitor.startView() and RumMonitor.stopView() methods.
09:23:01.297  W  A RUM event was detected, but no view is active. To track views automatically, try calling the Configuration.Builder.useViewTrackingStrategy() method.
                 You can also track views manually using the RumMonitor.startView() and RumMonitor.stopView() methods.
09:23:17.237  V  Batch 76d08dae-d871-4d84-9dae-3527a6884188 [5218 bytes] (TracesOkHttpUploaderV2) sent successfully.
09:23:17.731  V  Batch 3abf8cca-3d81-4342-92b2-803daf723080 [19467 bytes] (RumOkHttpUploaderV2) sent successfully.
'''

What's weird is this missing view name is present after the `_sync` in my view hierarchy.

**Comment by xgouchet** [comment]
Hi @pietrini, only with those elements we can't find why those views don't appear. Can you [contact the support](https://www.datadoghq.com/support/) with a reproducing sample app that exhibits the same behavior that you're seeing, please?

**Comment by pietrini** [comment]
Hi @xgouchet thx for your help.
I don't even think the issue is coming from the Android SDK as it's clear it reports the other views as it should. I'll investigate a bit more and try to look at what goes out of the device with a proxy.
Have a great day!

**Comment by xgouchet** [comment]
This issue has been stale for a long time, so we're closing it. Feel free to reopen with more information if need be.
