### ISSUE TITLE
Batch upload does not work since 1.13.0

### ISSUE THREAD

**Issue by nm2n** [DataDog/dd-sdk-android#1053]
**Describe what happened**
No batches are uploaded when using SDK version 1.13.0 onwards

**Steps to reproduce the issue:**
I was integrating the SDK in our app using version 1.13.0, however, no batches have been uploaded (same behaviour with 1.14.0). I downgraded the SDK to version 1.12.0 and batch upload worked. It is worth to mention, that when creating a vanilla app with the exact same SDK setup the batch upload works, too. So it seems something in our app is not compatible or interfering with changes made in the 1.13.0 version.
From debugging the SDK it seems the BatchFileDataReader isn't getting any files from the FileOrchestrator, maybe this helps.

**Describe what you expected:**
Batch upload works regardless the SDK version

**Additional context**
 - Android OS version: API 33 / 25
 - Device Model: Pixel 6/ Pixel 2 (Emulator)
 - Datadog SDK version: 1.13.0/1.14.0
 - Versions of any other relevant dependencies (OkHttp 4.9.3, Retrofit 2.9.0): 
 - Proguard configuration: NA on debug builds
 - Gradle Plugins: AGP 7.1.2, Firebase Crashlytics 2.9.1, Google Services 4.3.10

**Comment by 0xnm** [comment]
Hello @nm2n! Thanks for opening the issue.

Do you see any warnings/errors in logcat? You can enable Datadog SDK logs by calling `Datadog.setVerbosity`.

Also can you please check that you have `GRANTED` tracking consent and your emulator has network connectivity and is has no low battery level?

**Comment by nm2n** [comment]
Hi @0xnm ! Thanks for your quick reply.

Using 1.13.0 onward I don't see any logs. For 1.12.0 I see the warning

> A RUM event was detected, but no view is active. To track views automatically, try calling the Configuration.Builder.useViewTrackingStrategy() method.
>     You can also track views manually using the RumMonitor.startView() and RumMonitor.stopView() methods.

and then later a log message that the batch has been uploaded (but I remember that I saw that warning also for 1.13.0 before)

This is our setup

```
val clientToken = "<TOKEN>"
val applicationId = "<APP_ID>"

val environmentName = "<ENV>"
val appVariantName = "<VARIANT>"

val configuration = Configuration.Builder(
    rumEnabled = true,
    crashReportsEnabled = false,
    logsEnabled = false,
    tracesEnabled = false
)
    .useSite(DatadogSite.EU1)
    .sampleRumSessions(100f)
    .build()

val credentials = Credentials(clientToken, environmentName, appVariantName, applicationId)
Datadog.initialize(this, credentials, configuration, TrackingConsent.GRANTED)

Datadog.setVerbosity(Log.VERBOSE)
Datadog.enableRumDebugging(true)

GlobalRum.registerIfAbsent(RumMonitor.Builder().build())
```
My device is fully charged and connected to network

**Comment by 0xnm** [comment]
Thanks for the info! Are you able to check your app's cache folder, do you see the files (folders hosting them should start with `dd-`, like `dd-rum-v2`, folders with batches ready for upload shouldn't have `pending` word) from our SDK there?

Also a couple of things to check:

* Can you check if you are not adding any very big objects (like bitmaps in base64) to the attributes?
* Can you try to send some logs to Datadog (if not sending already)?
* Can you try a clean app install/clean emulator state?
* If you try to run our [sample](https://github.com/DataDog/dd-sdk-android/tree/develop/sample) app on your emulator, does it making an attempt to upload data? You can put fake values for the `applicationId` and `apiKey`.

Otherwise if you have a chance to share a sample project where the issue is reproduced, this would be great.

**Comment by nm2n** [comment]
Sure thing, here a my results

> do you see the files (folders hosting them should start with dd-, like dd-rum-v2, folders with batches ready for upload shouldn't have pending word) from our SDK there?

yes!

<img width="603" alt="image" src="https://user-images.githubusercontent.com/2349682/192270588-e3e91a2a-476f-4b5d-9b68-a1f1557c0088.png">

> Can you check if you are not adding any very big objects (like bitmaps in base64) to the attributes?

Not 100% sure to which attributes you are referring to, but we usually do not handle big objects except for image loading.

> Can you try to send some logs to Datadog (if not sending already)?

There are files in the dd-logd-v2 folder, however, I did not recognize any uploads.

> Can you try a clean app install/clean emulator state?

Same results

> Otherwise if you have a chance to share a sample project where the issue is reproduced, this would be great.

Unfortunately not, we are only able to reproduce it on our app not on sample projects

> If you try to run our [sample](https://github.com/DataDog/dd-sdk-android/tree/develop/sample) app on your emulator, does it making an attempt to upload data?

Added fake token and id to the credentials. I don't see any attempts to upload batches. However, I see files in "pending" folders (and only in these folders)

**Comment by 0xnm** [comment]
> Added fake token and id to the credentials. I don't see any attempts to upload batches. However, I see files in "pending" folders (and only in these folders)

For our sample app you need to switch default consent permission from `PENDING` to `GRANTED` by opening 3-dots menu and tapping `GDPR`.

Do you use any 3rd party instrumentation in our app which does any byte-code injection?

Alternatively can you please step through `BatchFileOrchestrator#getReadableFile` with debugger to see at which point it returns nothing?

**Comment by nm2n** [comment]
I found the issue. No batches are created from file due to an `InvocationTargetException` thrown while parsing the Json the `EventMeta` class. That exception appears to be swallowed as it is not shown in the logs. 
So, it turns out that the Datadog SDK is using a newer version of Gson than we do, while we are enforcing the older version. This means `JsonParser.parseString` is not invokable. Updating Gson on our side will solve the issue.

Thank you for your support!
