### ISSUE TITLE
ANR reports number is significantly different from the Google Play

### ISSUE THREAD

**Issue by emartynov** [DataDog/dd-sdk-android#1067]
**Describe what happened**
The number of ANR reports in RUM is significantly more than at Google Play. However, the number of crashes is similar.

**Steps to reproduce the issue:**
1. Integrate DataDog Android SDK
2. Check the RUM error section

**Describe what you expected:**
1. Number of ANR is similar to Google Play's one

P.S. I was not able to find the algorithm of the ANR collection in the documentation.

**Comment by xgouchet** [comment]
Hi @emartynov, our ANR detection algorithm is an estimation of ANR, and unfortunately will have some discrepancies compared to Google's detection.
The way we do it is have a small task that is trying to run on the main thread regularly, and if this task is blocked for more than 5 seconds, we consider that to be an ANR, even though the OS might not have detected it or might not have shown the ANR popup to the end user. You can find our [implementation here](https://github.com/DataDog/dd-sdk-android/blob/develop/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnable.kt). 
Although we might have more false positives, it essentially still means that your application is doing a lot of work on the main thread, that could be offloaded to background threads for better performances.

**Comment by emartynov** [comment]
Great! However, there is no easy way to filter out ANR and crash. And it is tough to focus on the crash fix for now. 

Also, the number of DD ANRs is devastating. It is much/much more than Google Play. Can you agree with Google, or can we tweak the threshold?

**Comment by xgouchet** [comment]
Hi @emartynov, 
When you say devastating, what's the order of magnitude we're talking about. Are we reporting twice the number of ANRs that the play store reports, 100 times more? We didn't notice a huge discrepancies from our tests, do you have a sample app that reproduces this issue that we could use to investigate if there's an edge case we don't handle properly?

there's no option to tweak the detection, as we base ourselves to the duration documented by Google. 
The ANR (as experienced by the end user, and as reported by Google Play) is tracked at the OS level, with tools that we don't have access to, meaning we need to use some estimation. 

We might add an option to tweak the threshold value, or probably disable ANR reporting altogether. But again, the number of ANR we report, even if it doesn't match the number reported by Google Play, still means that the application is blocking the main thread a lot which leads to freeze experienced by the end users.

**Comment by emartynov** [comment]
Let me drop some screenshots.

# Google Play
<img width="681" alt="Screenshot 2023-01-02 at 11 35 23" src="https://user-images.githubusercontent.com/295424/210220535-9d809312-b655-4765-ab1a-9bcf24fbf77d.png">
<img width="285" alt="Screenshot 2023-01-02 at 11 35 27" src="https://user-images.githubusercontent.com/295424/210220603-774af00a-1617-443b-83ee-ca4808587482.png">

# Data Dog
<img width="446" alt="Screenshot 2023-01-02 at 11 38 04" src="https://user-images.githubusercontent.com/295424/210220656-8537eb4f-fe4d-49f8-a7fb-c686ad2a7eae.png">

The DD data is only for the last month and is just top of the list. The numbers below are also hundreds.

**Comment by xgouchet** [comment]
Thanks for the screenshots, indeed the discrepancy is important; do you have a sample app that could help us understand the use cases?

**Comment by emartynov** [comment]
Nope, I need a sample app. I can send you some stack traces privately or share my application id in the DD.

**Comment by xgouchet** [comment]
Can you open a support ticket then to share those stack traces please, with a mention of this discussion so that it can reach me faster ?

**Comment by emartynov** [comment]
@xgouchet, sorry for the delay. I created the support ticket and asked to forward it to you.

**Comment by emartynov** [comment]
Oke, I got the answer from support - DD will prioritise and work on this issue. As for now, I can use [drop run events feature](https://docs.datadoghq.com/real_user_monitoring/android/advanced_configuration/?tab=kotlin#modify-or-drop-rum-events). Hopefully, it works in a way that I can just drop the ANR data and not whole RUM session associated.

**Comment by xgouchet** [comment]
Yes you can drop only those ANR errors by checking the reported type, e.g.: 

```kotlin
        configBuilder.setRumErrorEventMapper(object: EventMapper<ErrorEvent> {
            override fun map(event: ErrorEvent): ErrorEvent? {
                if (event.error.message == "Application Not Responding") {
                    return null
                } 
                 return event
            }
        })
```

**Comment by emartynov** [comment]
@xgouchet How does SDK count the frozen frames? 

We don't have a bit load. And I see 100% frozen frames some times. Could it be that frames in the background are counted?
