### ISSUE TITLE
Question: Support multiple datadog sessions(AppIds) in the same application (Android)

### ISSUE THREAD

**Issue by cchaouachi** [DataDog/dd-sdk-android#1088]
Hello,

We are using several modules in our application and we want to have one datadog application per module.

Is it possible to implement several datadog AppIds in the same application?

**Comment by 0xnm** [comment]
Hello @cchaouachi. We don't support currently having multiple instances of our SDK in the same process, meaning we don't support multiple RUM applications in the same process as well.

However, we are working on such support which should land in the upcoming SDK v2 (we cannot give any timeline for the release at the moment).

**Comment by cchaouachi** [comment]
Thank you for your response.
