### ISSUE TITLE
I can't receive any data in dashboard from the datadog android sdk.

### ISSUE THREAD

**Issue by emanoellucasml** [DataDog/dd-sdk-android#1099]
Datadog android SDK is not sending any information to my dashboard. After running the app with the SDK initialized, I get the following errors/warnings:
```
W/Datadog: A RUM event was detected, but no view is active. To track views automatically, try calling the Configuration.Builder.useViewTrackingStrategy() method. You can also track views manually using the RumMonitor.startView() and RumMonitor.stopView() methods.
```
```
W/Datadog: You added a TracingInterceptor to your OkHttpClient, but you didn't register any Tracer. We automatically created a local tracer for you.
```
As if I weren't defining a view tracking strategy when creating Configurations object, which is not true, as we can see in my Datadog sdk initialization code:

```
        val clientToken = ""
        val applicationId = ""

        val environmentName = "android-test"
        val appVariantName = "android-test"

        val configuration = Configuration.Builder(
            rumEnabled = true,
            crashReportsEnabled = true,
            logsEnabled = true,
            tracesEnabled = true
        )
            .trackInteractions()
            .trackLongTasks(100L)
            .useViewTrackingStrategy(MixedViewTrackingStrategy(true))
            .useSite(DatadogSite.US1)
            .build()
        val credentials = Credentials(clientToken,environmentName,appVariantName,applicationId)
        Datadog.initialize(this, credentials, configuration, TrackingConsent.GRANTED)
        GlobalRum.registerIfAbsent(RumMonitor.Builder().build())
        Datadog.setVerbosity(Log.VERBOSE)
```

### **Other relevant informations:**

**build.gradle file**
```
buildscript {
    dependencies {
        classpath "com.datadoghq:dd-sdk-android-gradle-plugin:1.5.1"
    }
}

plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id("com.datadoghq.dd-sdk-android-gradle-plugin") version "1.5.1"
}
...
implementation 'com.datadoghq:dd-sdk-android:1.14.1'
```
**gradle.properties file**
```
android.useAndroidX=true
android.enableJetifier=true
```

**Additional context**
 - Android OS version: Android 11
 - Device Model: Android SDK (emulator)
 - Datadog SDK version: 1.14.1

 *What else could I do to get this problem solved? I'd appreciate any suggestion.*

**Comment by 0xnm** [comment]
Hello @emanoellucasml! Can you please check that you are targeting the right site (that your app is indeed registered in the `US1` region)?

Also can you see any messages about batch upload attempts in your logs?

And I advise you to check the following issue as well https://github.com/DataDog/dd-sdk-android/issues/1053.

**Comment by emanoellucasml** [comment]
Hello, @0xnm! Yes,

1) yes, I am targeting the right one. We're use [app.datadog.com](https://app.datadoghq.com/)
2) no, nothing about this neither

I just checked https://github.com/DataDog/dd-sdk-android/issues/1053#issuecomment-1259363887 and found the problem: we are forcing a older version of Gson as well. Thank you so much for your support!
