### ISSUE TITLE
DataDog crashing with directBootAware-"true" attribute

### ISSUE THREAD

**Issue by BBaleilevuka** [DataDog/dd-sdk-android#1116]
[direct_boot_aware_work_manager_crash.log](https://github.com/DataDog/dd-sdk-android/files/9903112/direct_boot_aware_work_manager_crash.log)
Thanks for taking the time for reporting an issue!

**Describe what happened**
- When using DataDog Log reporting in a `directBootAware="true"` application, the WorkManager inside the DataDog SDK isn't permitted to run before the device in unlocked.
- Our Application is running on boot-up and is used on the lock-screen to unlock the device.

**Steps to reproduce the issue:**
- Create an Android application.
- In the manifest file add the `android:directBootAware="true"` flag 
- Run the application

**Describe what you expected:**
- Datadog can be used within a `directBootAware` application without crashing.

**Additional context**
 - Android OS version: AOSP 11(non-gms)
 - Device Model: RealWear Navigator 500
 - Datadog SDK version: 1.14.1
 - Versions of any other relevant dependencies (OkHttp, …): `androidx.appcompat:appcompat:1.3.0`

**Comment by xgouchet** [comment]
Hi @BBaleilevuka , and thanks for reporting this issue. We're going to take a look at this and will come back to you as soon as possible.

**Comment by xgouchet** [comment]
HI @BBaleilevuka , 
This issue was [reported a while ago](https://github.com/DataDog/dd-sdk-android/issues/854) but we never managed to reproduce it on our side. It seems that adding the `android:directBootAware="true"` flag to an application is not enough to make the application crash, do you have more precise steps to reproduce the crash?

**Comment by BBaleilevuka** [comment]
Hey @xgouchet,

Thanks a lot for responding. I will attempt to get an example android project up and repo steps as soon as I can.

In the mean time, the main step which is important is having a full-disk encrypted device or file-base encrypted device, and then run an application that starts before the device is unlocked: https://developer.android.com/training/articles/direct-boot#dpm

I will get back to your with a demo app and repro steps asap.

Again, thank you very much @xgouchet

**Comment by xgouchet** [comment]
Thanks @BBaleilevuka , having the device encrypted is the key information I was missing. We'll take a look at this issue and come back to you when we have more info.
