### ISSUE TITLE
HttpUploader failing to upload

### ISSUE THREAD

**Issue by jcwhitenc** [DataDog/dd-sdk-android#1129]
I'm trying to set up a new application but cannot pass the verification step. Whenever I start up my app and start interacting with it I don't have any crashes and can use the network with no issue, but in logcat I have this error occurring about every 2 min. 
`E/Datadog: Batch af25824a-0683-47a5-9e6e-c9295938c6c3 [5297 bytes] (RumOkHttpUploaderV2) failed because of a network error; we will retry later.`

```
val clientToken = BuildConfig.DATADOG_CLIENT_TOKEN
        val applicationId = BuildConfig.DATADOG_APPLICATION_ID

        val environmentName = BuildConfig.BUILD_TYPE
        val appVariantName = packageName

        val configuration = Configuration.Builder(
            logsEnabled = true,
            tracesEnabled = true,
            crashReportsEnabled = true,
            rumEnabled = true
        )
            .useSite(DatadogSite.US1)
            .trackInteractions()
            .trackLongTasks()
            .useViewTrackingStrategy(MixedViewTrackingStrategy(trackExtras = true))
            .trackBackgroundRumEvents(true)
            .build()
        val credentials = Credentials(clientToken, environmentName, appVariantName, applicationId)
        Datadog.initialize(applicationContext, credentials, configuration, TrackingConsent.GRANTED)
        Datadog.setVerbosity(level = Log.VERBOSE)

        GlobalRum.registerIfAbsent(RumMonitor.Builder().build())
```

**Comment by 0xnm** [comment]
Hello @jcwhitenc! It seems that the device you are testing on has some problems connecting to our RUM intake. Can you please check if you are able to connect to https://rum.browser-intake-datadoghq.com (it is the URL for the RUM intake in the US1 region defined [here](https://github.com/DataDog/dd-sdk-android/blob/a669a1f7fa1c384b26779763791b35d0d5df8b71/dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEndpoint.kt#L101)) from the device?

**Comment by jcwhitenc** [comment]
When I go to that URL I am presented with a screen that displays only this text: `{"errors":[{"status":"400","title":"Bad Request","detail":"HTTP path is invalid"}]}`

**Comment by 0xnm** [comment]
Hello @jcwhitenc. This means that you can connect to the RUM intake without any issues. Can you please confirm that you opened this URL on the device where you have the application installed? Can you please also share the version of our SDK you are using?

**Comment by jcwhitenc** [comment]
It's catching a timeout excpetion.

**Comment by 0xnm** [comment]
If it is a write timeout exception, then do you maybe have a limited connectivity set up in the emulator settings? SDK has a timeout set to 45 seconds, which means that upload should be done in 45 seconds, given that max batch size is 4 MB (But normally batch size should be much smaller).

Considering that, I suppose that there is either a speed limit set up on your emulator, or your physical connection is not fast enough.

**Comment by jcwhitenc** [comment]
I'm not sure how but after restarting my computer, it connected.

**Comment by 0xnm** [comment]
Great to know, glad that it is solved now!
