### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by namget2** [DataDog/dd-sdk-android#1178]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Fatal Exception: java.util.ConcurrentModificationException
com.datadog.android.rum.internal.domain.scope.RumSessionScope.handleEvent (RumSessionScope.kt:88)
com.datadog.android.rum.internal.domain.scope.RumApplicationScope.handleEvent (RumApplicationScope.kt:51)
com.datadog.android.rum.internal.monitor.DatadogRumMonitor.handleEvent$dd_sdk_android_release (DatadogRumMonitor.kt:357)
com.datadog.android.rum.internal.monitor.DatadogRumMonitor.addCrash (DatadogRumMonitor.kt:272)

**Steps to reproduce the issue:**
RxJavaException will work and cause concurrency issues.

**Describe what you expected:**
I think we need to synchronize the reading and writing actions

**Additional context**
 - Android OS version: Android 12
 - Device Model: Galaxy S10 5G
 - Datadog SDK version: 1.13.0
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins: 1.5.1

**Comment by xgouchet** [comment]
Hi @namget2 , and thanks for reporting this issue. Can you share more details about how to reproduce this crash? You're mentioning RxJavaException, is this something you're using in your application? If possible, giving us a minimal sample project that illustrates this issue would help understand this crash.

**Comment by 0xnm** [comment]
Hello @namget2! Thanks for reporting the issue. We've landed a fix and it should be available in the next release (`1.16.0`) which should come out soon.
