### ISSUE TITLE
Measuring time elapsed with RUM

### ISSUE THREAD

**Issue by Albertoperezs90** [DataDog/dd-sdk-android#1244]
**Is your feature request related to a problem? Please describe.**
I want to track the performance of different places around our application. I know there is a functionality on the RUM SDK to measure. I know you guys already provides some ways to that but I think any of those can fit our needs.

-  `GlobalRum.get().addTiming("hero_image")` determine the time between the start of the current RUM view and the time when you call this function. That works greatly if you are measuring anything relative to the start of the current view, and I want to set `startTrack` manually and call `endTrack` manually, so we can measure time it takes for a function, or a segment of code to execute.
- `AndroidTracer` works greatly also, but I'm worried about how it calculates the pricing because as far as I know, every different host is increasing the price of APM. On the client-side, how is calculated when a trace comes from a client? I mean, every mobile device is treated like a different host? Also, those traces are not integrated with RUM "easily", I can't see those traces from `AndroidTracer` on the Trace window on RUM sessions.

**Describe the solution you'd like**
Something completely integrated with RUM and visible from the session view. Allow to set `startTrack` and `endTrack` without only relying on relative start of the current RUM view.

**Describe alternatives you've considered**
Using a custom `Timer` on our project and calculate the time elapsed between a defined `startTrack` and `endTrack`, then send those results using the `Logger` class of Datadog.

**Comment by xgouchet** [comment]
Hi @Albertoperezs90 and thanks for submitting this feature request. 

Regarding the pricing I know that it's slightly different for mobile, but you might want to reach your CSM contact for an official quote on that. 

Your understanding of the addTiming method is correct, it measures timings since the beginning of the current view. Using a logger with a custom timing is indeed the workaround I'd recommend for this feature.

We'll keep this idea in mind and see how we can expand our product to include this in the future.

**Comment by Albertoperezs90** [comment]
Thanks @xgouchet, just a question, can we create monitors or dashboard using the solution with Logger? I mean, it's possible to generate percentiles based on the information of Logger and from that percentiles, check if any value is bigger than X?

**Comment by xgouchet** [comment]
Yes, indeed, using the [Logs to Metrics feature](https://docs.datadoghq.com/logs/log_configuration/logs_to_metrics/), you can create a metric based on a log attribute, and create monitors on them. And logs can also be used in graphs in your custom dashboards.

**Comment by Albertoperezs90** [comment]
Thanks @xgouchet! closing this issue, tho It should be nice to include this feature on the future!
