### ISSUE TITLE
Log class names in Logcat

### ISSUE THREAD

**Issue by Vavassor** [DataDog/dd-sdk-android#133]
When Logcat is enabled, every message is tagged with the service name. When using Timber's vanilla `Timber.DebugTree`, it tags every message with the class the log came from. This is more useful to tell where the log came from when debugging.

It could be helpful to make a subclass of `Timber.DebugTree` which could pass tags from Timber to the datadog logger.

**Comment by mariusc83** [comment]
Hi @Vavassor and thank you for your feedback. I think you have a good point there, we will be looking into this internally and came back to you on this matter.

**Comment by xgouchet** [comment]
Hi @Vavassor , just to be sure of what you're asking, you only want the class name to appear in LogCat right ?
Getting the class name automatically is a very heavy process (not to mention that it can be error prone with obfuscation / minification), and doing so can impact greatly the performance of your application, which is why Timber only does it on a DebugTree.

**Comment by Vavassor** [comment]
@xgouchet Yes. The issue I was experiencing is mainly that using `DatadogTree` for all my logs made the messages tagged the same in Logcat. This is really just related to timber integration, I think.

I wouldn't expect to see class names in Datadog logs.

**Comment by xgouchet** [comment]
In that case we'll see what we can do on that topic.

**Comment by mariusc83** [comment]
@Vavassor this new feature was added recently on master. It will be available in our next release (1.3.0) probably starting next week. Please have in mind that this will only work in Debug mode.

**Comment by xgouchet** [comment]
This is now available in version [`1.3.0`](https://github.com/DataDog/dd-sdk-android/releases/tag/1.3.0). 
Thanks @Vavassor for submitting this feature request
