### ISSUE TITLE
OkHTTP3 version vulnerable to header information exposure

### ISSUE THREAD

**Issue by sparga** [DataDog/dd-sdk-android#1340]
**Describe what happened**
The version of OkHttp3 used in this project is potentially vulnerable to [CWE-200](https://cwe.mitre.org/data/definitions/200.html) security issue as explained in [this report by Snyk](https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044):

> [com.squareup.okhttp3:okhttp](https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp) is a HTTP & HTTP/2 client for Android and Java applications Affected versions of this package are vulnerable to Information Exposure. When there's an illegal character in a header value, an IllegalArgumentException is thrown whose message includes the full header value.

**Steps to reproduce the issue:**
Adding this SDK to an application is enough to make an app vulnerable. 

I noticed that, if the app is already using a higher version of OKHttp3, it appears that Gradle will force the resolution to use the most recent version anyway. But this is still an issue for apps not using OkHttp3 or using older versions.

**Describe what you expected:**
Please consider updating OkHttp3 to v4.9.2 or higher.

**Additional context**
 - Version 1.17.2 of the SDK and prior are affected.

**Comment by 0xnm** [comment]
Hello @sparga! We are aware of this CWE and did the necessary [mitigation](https://github.com/DataDog/dd-sdk-android/commit/864849316a1e38ccf11194a9a506e41705c2c144) for the sensitive headers a few versions back.

That being said and also considering that all headers are controlled by the SDK and client token and application ID are exposed in the application binary, this is not an issue for current 1.x versions of SDK with OkHttp 3.x. We have to keep OkHttp 3.x for now in 1.x versions for the compatibility with API 19 (KitKat), but we will be able to use OkHttp 4.x in SDK v2.
