### ISSUE TITLE
Using Datadog SDK in Application + custom SDK overwrites datadog serviceName

### ISSUE THREAD

**Issue by dnhyde** [DataDog/dd-sdk-android#1357]
**Describe what happened**
I have an application that integrates a custom SDK. I am using datadog to log both from my application (logs some events and errors) and from my custom SDK (logs a different set of events).
When I search on logs explorer it seems that I can only see logs with the service name of my application. Meaning that events logged from my SDK will inherit the serviceName that I defined in my application.

**Steps to reproduce the issue:**
Initialize datadog in your application as described in the [docs](https://docs.datadoghq.com/logs/log_collection/android/?tab=kotlin#setup).

App initialization inside `MainApplication` onCreate(): 
```kotlin
  // initialize datadog
        val configuration = Configuration.Builder(
            logsEnabled = true,
            tracesEnabled = false,
            crashReportsEnabled = false,
            rumEnabled = false
        ).useSite(DatadogSite.EU1).build()
        val credentials = Credentials(
            BuildConfig.DATADOG,
            if (BuildConfig.DEBUG) "dev" else "prod",
            Credentials.NO_VARIANT,
            null,
            "<MY_APP_SERVICE_NAME>"
        )
        Datadog.initialize(applicationContext, credentials, configuration, TrackingConsent.GRANTED)
```

SDK initialization (from application Context of the app integrating the SDK received as parameter):
```kotlin
 // initialize datadog
        val configuration = Configuration.Builder(
            logsEnabled = true,
            tracesEnabled = false,
            crashReportsEnabled = false,
            rumEnabled = false
        ).useSite(DatadogSite.EU1).build()
        val credentials = Credentials(
            BuildConfig.DATADOG,
            if (BuildConfig.DEBUG) "sdk_dev" else "sdk_prod",
            Credentials.NO_VARIANT,
            null,
            "<MY_SDK_SERVICE_NAME>"
        )
        Datadog.initialize(context, credentials, configuration, TrackingConsent.GRANTED)
```

**Describe what you expected:**
I expected to be able to filter by the twi different serviceNames: `"<MY_APP_SERVICE_NAME>"` versus `"<MY_SDK_SERVICE_NAME>"` from the dashboard of logs explorer.
However it seems that `"<MY_APP_SERVICE_NAME>"` has precedence and overwrites the `"<MY_SDK_SERVICE_NAME>"`, so I see events from my SDK that are tagged with my application service name.

**Additional context**
 - Android OS version: all from api level 23 and above
 - Device Model: all devices have the same behavior
 - Datadog SDK version: `1.14.1` both in my application and my SDK
 - Versions of any other relevant dependencies (OkHttp, …): only used in my application: 
    - same version for [datadog-timber plugin](https://github.com/DataDog/dd-sdk-android/blob/develop/dd-sdk-android-timber/README.md) 
    - retrofit `2.9.0`
    - gson `2.9.1`
 - Proguard configuration: nothing about datadog
 - Gradle Plugins: android gradle plugin `7.3.0`,  gradle version `7.5.1`

**Comment by dnhyde** [comment]
Hi @0xnm is it possible that the use-case above is supported for the iOS SDK?
(I see the warning on Android: `The Datadog library has already been initialized.` is there a similar warning on iOS)

**Comment by 0xnm** [comment]
Hello @dnhyde. iOS SDK doesn't support this use-case as well, but soon we are going to release v2 version of our SDK which supports it.

**Comment by dnhyde** [comment]
Ok I was asking because on iOS I am able to see two different service names suggesting the use case is already supported (not sure how this happens I will investigate more in depth)
