### ISSUE TITLE
Taps not recorded when your finger moves a little

### ISSUE THREAD

**Issue by GetsEclectic** [DataDog/dd-sdk-android#1389]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Include any error message or stack trace if available.

If you tap and move your finger slightly before releasing, it doesn't show up as a tap in RUM.

**Steps to reproduce the issue:**

Put your finger/cursor on a button, move 5-10px and then release. The UI will recognize this as a button press but it doesn't show up in RUM.

I believe this is because GesturesListener.onUp handles scrolls and swipes but not taps. It looks like the UI behavior is that if the down is on a button and the up is on the same button, it will be recognized as tapping the button.

You can tap down on a button, move off of the button, move back onto the button, and then release, and it will count as tapping the button.

If you tap down on a button, move off of the button, and then release, it will not count as tapping the button.

It is not uncommon that people move their finger slightly when pressing a button. It looks very strange in RUM as if they went to a new screen with no tap.

**Describe what you expected:**

I expect this to be recognized as a tap if the UI recognizes it as a tap.

**Additional context**
Android OS version: 14
Device Model: pixel 4 xl
Datadog SDK version: 1.17.1
Versions of any other relevant dependencies (OkHttp, …):
Proguard configuration:
Gradle Plugins:

**Comment by xgouchet** [comment]
This is fixed by #1622 , which will be released soon.

**Comment by GetsEclectic** [comment]
Awesome, thank you!
