### ISSUE TITLE
Performance Timing will be reported with wrong view scope

### ISSUE THREAD

**Issue by ken-kentan** [DataDog/dd-sdk-android#1432]
**Describe what happened**

In following scenario, I expected to get the performance timing only for the screen home and item. But the SDK reported the timing with not only screens but also `ApplicationLaunch`

Setup:
Create a sample app that has 2 screens called home and item.
Add a performance timing to measure Compose rendering performance.
Add some network calls in `Application::onCreate()`.

Scenario:
1. Open the app
   - a timing for home screen will be reported 
3. Navigate to item screen
   - a timing for item screen and ApplicationLaunch will be reported <- !?

**Steps to reproduce the issue:**

Clone this PR and run the sample Kotlin app.
https://github.com/ken-kentan/dd-sdk-android/pull/1

**Describe what you expected:**

Performance Timing won't be sent with ApplicationLaunch scope.

**Additional context**
 - Android OS version: Any
 - Device Model: Any
 - Datadog SDK version: develop
 - Versions of any other relevant dependencies (OkHttp, …): OkHttp
 - Proguard configuration: Any
 - Gradle Plugins: Any

**Comment by 0xnm** [comment]
Hello @ken-kentan! Thanks a lot for the reporting the issue and doing the investigation.

I've opened a PR with the fix [here](https://github.com/DataDog/dd-sdk-android/pull/1433), so you can try it if you want.

Can you please also give us the importance of this issue for you, so that we can understand if we should do a patch release? I believe you can just apply the filter for the views you want to see this timing for in the dashboard.

**Comment by ken-kentan** [comment]
Hello! Thank you for fixing this issue. I also confirmed the fix working well.

Since we can't correct our data correctly, I would like to request a patch release.
As you mentioned, in some cases, it's possible to filter in dashboard, but the wrong performance timing issue also happening on deactivated screen. It means more difficult to filtered out.

**Comment by ken-kentan** [comment]
@0xnm Sorry for ping you directly 🙇 
Could you check the above comment?

**Comment by ken-kentan** [comment]
Maybe you already working to release a patch release in https://github.com/DataDog/dd-sdk-android/pull/1439 ?
Sorry if I sent a duplicated request 🙇

**Comment by 0xnm** [comment]
Hello @ken-kentan! Indeed we are in the process of publishing version 1.19.1 which will include the fix needed. I will keep you updated once it is available.

**Comment by 0xnm** [comment]
`1.19.1` release is [available](https://search.maven.org/artifact/com.datadoghq/dd-sdk-android/1.19.1/aar) now.

**Comment by ken-kentan** [comment]
Thank you for releasing the new patch version!

**Comment by 0xnm** [comment]
@ken-kentan Please don't update SDK to version `1.19.1`, it contains the bug in the unrelated change, we will do a new release at the beginning of next week.

**Comment by ken-kentan** [comment]
Got it, we will keep using previous version until a new release published.

**Comment by 0xnm** [comment]
@ken-kentan `1.19.2` is released, you can safely use it.

**Comment by ken-kentan** [comment]
Thank you for releasing the new version! We will use the new version!
