### ISSUE TITLE
Allow configuring Datadog after OkHttp initializers are created

### ISSUE THREAD

**Issue by lwasyl** [DataDog/dd-sdk-android#1497]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : [e.g. `Realm`, `RxJava`] OkHttp
- Library type: [e.g. database] networking
- Library version: [e.g. 5.2] 4.x

**Is your feature request related to a problem? Please describe.**

It's frustrating to have to configure and initialize Datadog _before_ creating `OkHttp` initializers. OkHttp is usually one of the top dependencies within the project and should be created as soon as possible, while Datadog initialization might be deferred.

I see in other issues like https://github.com/DataDog/dd-sdk-android/issues/511 that people are encountering this and are restructuring their DI to accommodate Datadog

**Describe the solution you'd like**

It'd be great to have an option to create initializers _before_ Datadog is initialized, but that'd pick up the Datadog configuration once it's initialized. I realize this would cause some network calls to potentially be untracked, which is fine

**Describe alternatives you've considered**

Writing own `TracingInterceptor`, but given the amount of internal fields and complex implementation it's rather unpractical

**Additional context**

**Comment by 0xnm** [comment]
Hello @lwasyl! You can try our [first beta of SDK v2](https://github.com/DataDog/dd-sdk-android/releases/tag/2.0.0-beta1) which now allows to configure `OkHttp` before Datadog SDK is initialized (requests will be captured once Datadog SDK is up and running).

Feel free to re-open this ticket if this solution doesn't work for you.
