### ISSUE TITLE
How can I get sessionId?

### ISSUE THREAD

**Issue by emanoellucasml** [DataDog/dd-sdk-android#1535]
As we can see [here](https://github.com/DataDog/dd-sdk-ios/pull/590#discussion_r703313457) , it is possible to define on the iOS version of Datadog a callback method to be called as soon as the session starts. This is useful, for example, I want to get the sessionId of the current session, however I've been searching and didn't find something like this on Android. How could I achieve the same thing in Android?

**Comment by 0xnm** [comment]
Hello @emanoellucasml! We have the similar API in Android SDK, it is `RumMonitor.Builder#setSessionListener`, you can check it [here](https://github.com/DataDog/dd-sdk-android/blob/adfa6e8f3958a3c6f4ad0f0e31b006a43f6a0887/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt#L298).

**Comment by emanoellucasml** [comment]
Thank you very much!
