### ISSUE TITLE
Drop errors based on their Exception 

### ISSUE THREAD

**Issue by orafaaraujo** [DataDog/dd-sdk-android#1560]
Hi,

I'm trying to drop some errors, but they continue to appear in the Dashboards. 

I'm using a custom `TracedRequestListener` on `DatadogInterceptor` and `TracingInterceptor`.

```kotlin
DatadogInterceptor(
    firstPartyHosts = tracedHosts,
    tracedRequestListener = customTracedRequestListener,
)

TracingInterceptor(
    tracedHosts = tracedHosts,
    tracedRequestListener = customTracedRequestListener,
)

private val customTracedRequestListener = object : TracedRequestListener {
    override fun onRequestIntercepted(
        request: Request,
        span: Span,
        response: Response?,
        throwable: Throwable?,
    ) {
        if (throwable is IOException) {
            (span as? DDSpan?)?.drop()
        }
    }
}
```

I aim to remove all `java.io.IOException: Canceled` generated from Coroutines when the user leaves the screen in a middle of a request. Those exceptions are expected, so we do not want to send them to Datadog.

Am I missing something? What's the correct approach in this situation?

Thank you 

**Additional context**
 - Android OS version: Android 13
 - Device Model: Emulator, Pixel 5
 - Datadog SDK version: 1.19.3
 - Versions of any other relevant dependencies (OkHttp, …): OKHttp bom 4.11.0, retrofit 2.9.0, coroutines 1.7.1
 - Proguard configuration: nothing unusual 
 - Gradle Plugins: 1.10.0

**Comment by 0xnm** [comment]
Hello @orafaaraujo!

Can you please tell us which dashboard are you checking? Is it RUM or Traces (APM)?

Please also share the SDK version used.

**Comment by orafaaraujo** [comment]
Hey @0xnm 

It's on the RUM dashboard. 

<img width="1667" alt="Screenshot 2023-07-28 at 15 03 44" src="https://github.com/DataDog/dd-sdk-android/assets/1668348/234aaec2-94cf-4a86-a14d-e6542f5e913e">




I'm using the SDK version 1.19.3, plugin version 1.10.0.

**Comment by 0xnm** [comment]
`TracedRequestListener` works with spans, which are used for distributed tracing (APM) in case of OkHttp instrumentation.

For your use-case, since it is RUM, you may use [setRumErrorEventMapper](https://docs.datadoghq.com/real_user_monitoring/android/advanced_configuration/?tab=kotlin#modify-or-drop-rum-events) and return `null` in the implementation for the events which you want to drop based on your criteria.

**Comment by orafaaraujo** [comment]
Hey @0xnm 

Now it's working like a charm. Thank you for your help on that.
Have a nice weekend!
