### ISSUE TITLE
Events between Activities considered as Background

### ISSUE THREAD

**Issue by jraska** [DataDog/dd-sdk-android#1565]
**Describe what happened**
1.  When the application is in the foreground, but a new activity is starting, RUM treats events between `Activity1#onPause` and subsequent `Activity2#onResume` as background events, therefore dropping them if background tracking is disabled.
2. This behaviour exists due to a gap in time between [`RumMonitor.stopView("Activity1")`](https://github.com/DataDog/dd-sdk-android/blob/08ec188dc2534d420f4cbffbd7839eb6b5f67d90/features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt#L52) and [`RumMonitor.startView("Activity2")`](https://github.com/DataDog/dd-sdk-android/blob/08ec188dc2534d420f4cbffbd7839eb6b5f67d90/features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt#L44) is called as part of [`ActivityViewTrackingStrategy`](https://github.com/DataDog/dd-sdk-android/blob/08ec188dc2534d420f4cbffbd7839eb6b5f67d90/features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt#L52) - see diagram:

![Dropped RUM events drawio](https://github.com/DataDog/dd-sdk-android/assets/6277721/23b70b29-1f9a-4234-b81d-c392f0261b88)

3. This is fixed by the `.trackBackgroundEvents(true)` and events in such cases are reported with `"Background"` as a view, however this setting is not desirable for our case as it would yield large amount of sessions.
<img width="737" alt="Screenshot 2023-08-01 at 17 06 47" src="https://github.com/DataDog/dd-sdk-android/assets/6277721/cb8227b7-e6c9-4292-bc61-b0e96f29167b">

**Steps to reproduce the issue:**
1. Setup the SDK [with `.trackBackgroundEvents(false)`](https://docs.datadoghq.com/real_user_monitoring/android/?tab=kotlin#track-background-events) .
3. Set `.useViewTrackingStrategy(MixedViewTrackingStrategy(trackExtras = true))`, though I believe default [ActivityViewTrackingStrategy](https://github.com/DataDog/dd-sdk-android/blob/08ec188dc2534d420f4cbffbd7839eb6b5f67d90/features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt#L52) would work as well.
5. Report Custom Action or Error in `Activity#onStop`, `Activity#onDestroy` or (`Activity.onCreate` except the ApplicationLaunch state)
6. These custom actions will be dropped.

**Describe what you expected:**
1. RUM events reported to DataDog would be expected as the app is not in the background, there is only a gap between `Activity1#onPause` and subsequent `Activity2#onResume`
2. One option could be using the [ActivityManager.RunningAppProcessInfo#importance](https://developer.android.com/reference/android/app/ActivityManager.RunningAppProcessInfo#importance) to determine background events - I see this value is used already within SDK for some use cases.
3. Possible implementation could be a different `ViewTrackingStrategy` taking this edge case into account. Jetpack components solve this problem by having a timeout of 5 seconds before equivalent of `stopView` is being called. for example asLiveData uses [timeout](https://developer.android.com/reference/kotlin/androidx/lifecycle/package-summary#(kotlinx.coroutines.flow.Flow).asLiveData(kotlin.coroutines.CoroutineContext,java.time.Duration)) to handle similar use case. 

**Additional context**
 - Android OS version: 12, same behaviour on multiple versions
 - Device Model: Reproducible on any available device
 - Datadog SDK version: `1.19.3`
 - Versions of any other relevant dependencies (OkHttp, …): OkHttp 4.11.0, though this is more relevant to handling lifecycle.
 - Proguard configuration: Reproducible in debug
 - Gradle Plugins: DataDog and standard Android plugins

**Clarifications**
1. The first question is if this is actually desired behaviour from the SDK?
2. The second question is how not to drop these events at the transition period between activities && not enabling background events tracking?

Thanks for the answer.

**Comment by plousada** [comment]
Hi @jraska, thank you for the detailed explanation! 

Indeed this is a flaw we had identified recently but still didn't come to a conclusion on the best way to address it.  
To answer your questions:

> The first question is if this is actually desired behaviour from the SDK?
No, this is a side effect of the current implementation of some of our View tracking strategies. We aim to provide as much coverage as possible during the Application lifecycle so this is something we aim to address in the near future. 

> The second question is how not to drop these events at the transition period between activities && not enabling background events tracking?
There are 2 routes you could take:

1. Implementing a "Transition" view by manually calling `startView` right after the `ViewTrackingStrategy` stops the previous view. You could register your own `onPause` callback after the SDK initializes to achieve this. This transition view would then cease to exist when the `onResume` method was called and the SDK starts another view. Similar to Background tracking but without the effects of creating additional sessions in other scenarios. 

2. Don't use a view tracking strategy and instead revert to manually calling `startView` and `stopView` on where it makes the most sense for the app.

**Comment by jraska** [comment]
ok, thanks for the response. 👍 

We will go for option 1. for now, though handling that on the SDK side would be preferable :) I will keep the issue open to update once once this is solved from the SDK side.

Thank you

**Comment by xgouchet** [comment]
Hi @jraska , our recently merged PR #1578 should fix the gap between onPause and onResume on Activities and Fragments. It'll. be part of our next release of the SDK
