### ISSUE TITLE
ConcurrentModificationException in TracingInterceptor

### ISSUE THREAD

**Issue by jamesbluecrow** [DataDog/dd-sdk-android#1570]
Thanks for taking the time for reporting an issue!

**Describe what happened**

```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
       at java.util.LinkedList$ListItr.next(LinkedList.java:892)
       at com.datadog.opentracing.PendingTrace.expireReference(PendingTrace.java:192)
       at com.datadog.opentracing.PendingTrace.expireSpan(PendingTrace.java:118)
       at com.datadog.opentracing.PendingTrace.addSpan(PendingTrace.java:144)
       at com.datadog.opentracing.DDSpan.finishAndAddToTrace(DDSpan.java:101)
       at com.datadog.opentracing.DDSpan.finish(DDSpan.java:110)
       at com.datadog.android.tracing.TracingInterceptor.handleResponse(TracingInterceptor.kt:514)
       at com.datadog.android.tracing.TracingInterceptor.interceptAndTrace(TracingInterceptor.kt:248)
       at com.datadog.android.tracing.TracingInterceptor.intercept(TracingInterceptor.kt:180)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.ourpackage.DatadogSpanInterceptor.intercept(DatadogSpanInterceptor.kt:30)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Steps to reproduce the issue:**
Not sure how to reproduce it but we've had a few reports of this exception.
**Describe what you expected:**

**Additional context**
 - Android OS version: So far in Android 12 & 13
 - Device Model: Galaxy Z Fold4, Model:Galaxy S21+ 5G, Redmi Note 12, Model:Camon 17, ...
 - Datadog SDK version: 1.19.2
 - Versions of any other relevant dependencies (OkHttp, …): OkHttp=4.11.0
 - Proguard configuration: 
 - Gradle Plugins:

**Comment by xgouchet** [comment]
Hi @jamesbluecrow , can you show us the content of your `com.ourpackage.DatadogSpanInterceptor` please?

**Comment by jamesbluecrow** [comment]
> Hi @jamesbluecrow , can you show us the content of your `com.ourpackage.DatadogSpanInterceptor` please?

You can see it below. 

```
class DatadogSpanInterceptor : Interceptor {

    override fun intercept(chain: Chain): Response {
        val request = chain.request()

        val newRequest = runAndCatch {
            val serviceContextId = request.header(OpenPhoneHeaders.HEADER_NAME_REQUEST_ID)
            DatadogDestination.contextToSpanMap[serviceContextId]?.let {
                request.newBuilder().parentSpan(it.span).build()
            } ?: request
        }.getOrDefault(request)

        return chain.proceed(newRequest)
    }
}
```

`DatadogDestination.contextToSpanMap` is a `ConcurrentMutableMap` from https://github.com/touchlab/Stately

**Comment by xgouchet** [comment]
Thanks a lot for this code, do you have more in fo about that `contextToSpanMap`? What type of objects does it hold? What's the purpose of this Interceptor?

**Comment by jamesbluecrow** [comment]
> Thanks a lot for this code, do you have more in fo about that `contextToSpanMap`? What type of objects does it hold? What's the purpose of this Interceptor?

Sure let me explain:
- `contextToSpanMap` is a `ConcurrentMutableMap<String, PerformanceSpan>()` where `PerformanceSpan` is just a data class that holds the `io.opentracing.Span` together with some other metadata.
- We are using this to "connect" the spans that we track manually and the spans created by `com.datadog.android.DatadogInterceptor` so when we look at the span + subspans in datadog we can see the http requests related data as subspans of our use cases spans.

**Comment by xgouchet** [comment]
In theory the `TracingInterceptor` already connects the okhttp span with the current active Span. Did you try making the parent span active, and let our interceptor make the link automatically?

**Comment by jamesbluecrow** [comment]
> In theory the `TracingInterceptor` already connects the okhttp span with the current active Span. Did you try making the parent span active, and let our interceptor make the link automatically?

Mmmm, it will not because there could be many different active spans at the same time so it would not work, no?

I mean we are creating the spans manually so there is no way for datadog sdk to know what is the active span, I imagine that you are thinking that it would be done automatically if we were using `launchTraced` from the datadog sdk extensions (but we are not).

**Comment by jamesbluecrow** [comment]
@xgouchet To clarify what I mean:

The `TracingInterceptor` connects successfully the Android http requests and the backend traces, but in the Android app we do something like:
- ViewModel -> UseCase -> Repository -> OkHttp

We are currently creating a span when the `UseCase` is executed. Then we want to see any http requests triggered inside the use case as subspans of our use case.

**Comment by xgouchet** [comment]
We're trying to reproduce this locally, which version of the Stately library are you using?

**Comment by jamesbluecrow** [comment]
> We're trying to reproduce this locally, which version of the Stately library are you using?

We are currently using:
```
co.touchlab:stately-concurrency:2.0.0-rc1
co.touchlab:stately-concurrent-collections:2.0.0-rc1
``` 

I haven't been able to reproduce this myself manually, but we are definitely seeing it in prod for some of our users.

**Comment by jamesbluecrow** [comment]
Over the last week we have seen an increase on crashes around this. Still insignificant compared to the number of users we have but it has grown to more than 100 crashes related to this.

I haven't been able to reproduce this myself either. But the underlaying issue seems to be that `PendingTrace` is not thread safe.

`span.finish()` can be called from multiple threads and `expireReference` iterates over the list of pending traces and that list can be modified from multiple threads while iterating the list.
