### ISSUE TITLE
Netwrok Info in Datadog logger is sent when disabled 

### ISSUE THREAD

**Issue by ahmedMubarak2024** [DataDog/dd-sdk-android#1572]
Thanks for taking the time for reporting an issue!

**Describe what happened**
so we have a requirement in Vodafone that we don't send user data to thrid parties and you collect Network info including location and IP address when I used 
Logger.Builder().setNetworkInfoEnabled(false) in Android did not stop it and it still being sent in Logger in every log 
**Steps to reproduce the issue:**
just test it with the flag False it you will see Network info in logger

**Describe what you expected:**
the SDK shouldn't sent this info when I set the flag to false 

**Additional context**
 - Android OS version: Api 32
 - Device Model: Emulator 
 - Datadog SDK version: 1.19.3
 - Versions of any other relevant dependencies (OkHttp, …): okhttp3 4.10.0 and okhttp2 : 2.7.5
 - Proguard configuration: nothing related to datadog 
 - Gradle Plugins:7.4.2

**Comment by xgouchet** [comment]
Hi @ahmedMubarak2024 , those information are not track from our mobile SDK itself but are gathered by the ingestion pipeline. You can disable this in your [Logs pipeline configuration](https://mobile-integration.datadoghq.com/logs/pipelines) by: 
1. cloning the automatic `Android Logs` rules 
<img width="934" alt="Screenshot 2023-08-08 at 16 19 47" src="https://github.com/DataDog/dd-sdk-android/assets/818706/33f2ebf1-31ba-48f7-8f38-e80670e05004">

2. disabling the collection of IP and Geo Location: 
<img width="934" alt="Screenshot 2023-08-08 at 16 20 41" src="https://github.com/DataDog/dd-sdk-android/assets/818706/d8a18f3c-cd86-4627-a26d-568c5be7d0fa">

**Comment by ahmedMubarak2024** [comment]
@xgouchet we tested this solution and it is working but now we etwork
{
client
{
ip
196.155.18.167
}
} and we want to remove it any ideas

**Comment by xgouchet** [comment]
Hi, indeed, we don't have an option to not capture the IP address, but you can discard it by overriding it: 

1. create a new processor in the Android pipeline you cloned
<img width="602" alt="Screenshot 2023-08-08 at 17 39 04" src="https://github.com/DataDog/dd-sdk-android/assets/818706/e4bb0f30-ffb1-4f49-bc8e-a8d05c162bd0">

2. Edit it to use "String Builder Processer", give it a relevant name, target the `network.client.ip` attribute and set the `target attribute value` to `0.0.0.0` for example
<img width="1086" alt="Screenshot 2023-08-08 at 17 39 57" src="https://github.com/DataDog/dd-sdk-android/assets/818706/09612d16-c459-4865-b786-c77a8f5a51ed">

3. click on `Create`
