### ISSUE TITLE
Concerns about Android Client Migration to Datadog 2.0 and APM Trace Compatibility

### ISSUE THREAD

**Issue by RamiTrabelsi** [DataDog/dd-sdk-android#1573]
**Describe what happened**

I'm currently considering the migration of our Android application to Datadog's new Release 2.0. Given the importance of APM traces in our monitoring, I'm concerned about potential adaptability issues that might arise when migrating the Android client to this new release, while leaving other platforms (iOS and backend) on version 1.19.3.

**Describe what you expected:**

Ideally, I would expect the migration to Datadog Release 2.0 to seamlessly integrate with our Android client, ensuring that APM traces continue to function as expected without any disruptions or data inconsistencies.

**Comment by xgouchet** [comment]
Hi @RamiTrabelsi, the changes between version 1.x.x and 2.0.0 mostly consists of an architectural change which was required to add the Session Replay feature for Android and iOS. 
The APM feature is for all intents and purposes unchanged, meaning there is no known incompatibility with the agent you might use in the backend, or other RUM SDKs (iOS, browser, …), and migrating to 2.0.0 should be seamless as you expect. 
Did you notice any actual bug or discrepancy?

**Comment by RamiTrabelsi** [comment]
Hi @xgouchet ,

Thanks for your quick response and detailed explanation. I haven't noticed any bugs or issues so far. I appreciate your support.

**Comment by xgouchet** [comment]
You're welcome, I'll close this ticket, but if you find any behavior feel free to open an issue again
