### ISSUE TITLE
Unable to import com.datadoghq:dd-sdk-android-rum:1.16.0

### ISSUE THREAD

**Issue by PhaniParvathaneni** [DataDog/dd-sdk-android#1580]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Include any error message or stack trace if available.
* What went wrong:
Execution failed for task ':app:mergeDevelopmentDebugNativeLibs'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find com.datadoghq:dd-sdk-android-rum:1.16.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/datadoghq/dd-sdk-android-rum/1.16.0/dd-sdk-android-rum-1.16.0.pom
       - https://www.jitpack.io/com/datadoghq/dd-sdk-android-rum/1.16.0/dd-sdk-android-rum-1.16.0.pom

This is my build.gradle(Project level)
classpath("com.datadoghq:dd-sdk-android-gradle-plugin:1.6.0")

build.gradle app level
plugins {
  id("com.datadoghq.dd-sdk-android-gradle-plugin")
}

dependencies {
implementation "com.datadoghq:dd-sdk-android-rum:1.16.0"
}

**Steps to reproduce the issue:**

**Describe what you expected:**

**Additional context**
 - Android OS version:
 - Device Model:
 - Datadog SDK version:
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins:

**Comment by xgouchet** [comment]
Hi @PhaniParvathaneni and thanks for opening this issue, you need to use the version `2.0.0` of the SDK to use the feature specific artifacts.
