### ISSUE TITLE
RUM's isSlowRenderedFlag reporting false positives

### ISSUE THREAD

**Issue by usamakzafar** [DataDog/dd-sdk-android#1583]
**Describe what happened**
The way `@view.is_slow_rendered` flag is reported is not taking into account the adaptive refresh rates of newer devices with version > Android 11.

**Steps to reproduce the issue:**

_Note: I've done my analysis with Samsung S22 Ultra but any new model from the past 2 that supports adaptive refresh rates should work_
1. Setup the SDK with RUM in an empty or basic Android project
3. Turn on the device's refresh rate monitor from the developer options
![Screenshot 2023-08-22 at 11 26 09](https://github.com/DataDog/dd-sdk-android/assets/29094064/48b41081-2ff2-4e94-b579-49158fb5b634)
4. Turn off battery saver mode (if on)
5. Launch the app and don't interact with the screen. The resting refresh rate should come down to 24 fps. (if it doesn't, the device may not support adaptive refresh rates)
6. Let it rest for at least 50% of the session 
7. The `@view.is_slow_rendered` would now show `true` for the session and the refresh rate distribution would look something like:
![Screenshot 2023-08-22 at 11 30 41](https://github.com/DataDog/dd-sdk-android/assets/29094064/e5f53877-2ef9-41cf-80dd-ec35ff13a451)

**Describe what you expected:**
When the device is in resting, the lower performance-saving refresh rate values inside should not be used to calculate the `isSlowRendered` boolean.
```
refreshRateInfo.meanValue < SLOW_RENDERED_THRESHOLD_FPS
```

**Additional context**
 - Android OS version: 13
 - Device Model: Samsung S22 Ultra
 - Datadog SDK version: 1.19
 - Versions of any other relevant dependencies (OkHttp, …): not relevant
 - Proguard configuration: Reproducible in debug
 - Gradle Plugins: Standard Android

**Comment by jonathanmos** [comment]
hi @usamakzafar thanks for reporting. We'll investigate what's going on here

**Comment by jonathanmos** [comment]
Could you please try to check this using v2 of the sdk and let us know if it's still an issue there? There were some changes made in v2 to the timing behaviour

**Comment by usamakzafar** [comment]
@jonathanmos thanks for the response. We were just doing more investigations on our side today and we noticed that V2 doesn't use Choreographer, rather the JankStats from androidx. We'll bump the version and let you know if we find any problems.

TY!

**Comment by 0xnm** [comment]
Hello @usamakzafar! Do you have any updates on this issue?
