### ISSUE TITLE
Multiple Instances of Datadog RUM

### ISSUE THREAD

**Issue by amrita019** [DataDog/dd-sdk-android#1585]
Hello team,

I've integrated DataDog RUM for monitoring into my Android Library. I'm currently attempting to establish multiple instances of DataDog, one within the main application and another within the library itself. (As of version 2.0.0 onwards, I believe this is possible, and I'm using the same version in both contexts.)

I'm encountering a situation where all the data and errors are being tracked solely on the dashboard of the main application—the one that was initialized first.

I've tried to look for available documentation for insights on this matter, but unfortunately, I haven't been able to locate any relevant information. Could you please help in resolving this?

Thank you.

**Comment by xgouchet** [comment]
Hi @amrita019  and thanks for opening this question. 
When creating a new Datadog instance, you can name it. Each named instance of the SDK stores data in a distinct folder, and will send data separately. 

e.g.: 

```kotlin
// Initialize the unnamed SDK instance, usually for an application
val configuration = Configuration.Builder(…).build()
Datadog.initialize(context, configuration, trackingConsent)


// Initialize a named SDK instance, for a library
// Note that the name is a free form string but *must* be identical in all cases. 
// Using the package name of the library (e.g.: com.example.library) or 
// the maven group and artifact name (e.g.: com.example:library) is a best practice
val configuration = Configuration.Builder(…).build()
Datadog.initialize("com.example.library", context, configuration, trackingConsent)
```

When initializing a feature, you can retrieve a specific SDK instance with 
```kotlin
val sdk = Datadog.getInstance("com.example.library")
val logsConfig = LogsConfiguration.Builder().build()
Logs.enable(logsConfig, sdk) 
// the second parameter is optional and defaults to the unnamed SDK instance
```

**Comment by amrita019** [comment]
Hello @xgouchet 
Thank you for replying, I followed it.

So on the dashboard, I see something like this, Orange bars for the main app and red ones for the SDK. 
Is that correct to have it like that?

<img width="787" alt="Screenshot 2023-09-04 at 8 57 35 AM" src="https://github.com/DataDog/dd-sdk-android/assets/35000058/76fa9356-454c-4cc7-8218-32a7ee600320">

**Comment by mariusc83** [comment]
Hi @amrita019 , actually in order to be able to initialize 2 SDKs you will have to create 2 RUM applications in your Dashboard and for each SDK instance you will need to provide an unique `clientToken` and `RUM App ID`. To be able to see the data for one SDK instance you will have to open the equivalent RUM application in your dashboard. What you are seeing there in your dashboard is amount of sessions vs amount of errors (in red) and not data from the 2 SDKs.

**Comment by 0xnm** [comment]
Hello @amrita019! Do you still have any questions regarding this topic? If not, can this issue be closed?

**Comment by amrita019** [comment]
Oh yes, Thank you for your support. Closing the issue.
