### ISSUE TITLE
View's duplicated when using version 2.x

### ISSUE THREAD

**Issue by orafaaraujo** [DataDog/dd-sdk-android#1614]
**Describe what happened**
Once we updated our app to use version 2.0 (and now 2.1.0), we noticed that the views inside the sessions were duplicated. 

In the duplicated view, one is full of data, like tracers, and the other is empty. 

Here's our setup

```kotlin
fun startLibrary() {
    if (Datadog.isInitialized()) return
    val configuration = getConfiguration()
    val trackingConsent = TrackingConsent.GRANTED
    Datadog.initialize(context, configuration, trackingConsent)

    // Enable RUM
    setupRumConfiguration()

    // Setup Tracers
    setupTracesConfiguration()

    if (showLogs) {
        Datadog.setVerbosity(Log.VERBOSE)
    }
}

fun setupUserInLibrary(user: User) {
    Datadog.setUserInfo(id = user.id)
}

fun unsetUserInLibrary() {
    // Setting nothing as user info will default to null attributes
    Datadog.setUserInfo()
}

private fun setupRumConfiguration() {
    val rumConfig = RumConfiguration
        .Builder(applicationId = ...)
        .setSessionSampleRate(SampleRateProvider.sampleRate())
        .setSessionListener(object : RumSessionListener {
            override fun onSessionStarted(sessionId: String, isDiscarded: Boolean) {
                log("Datadog - sessionId = [$sessionId], isDiscarded = [$isDiscarded]")
            }
        })
        .useViewTrackingStrategy(strategy = strategyProvider.get())
        .trackUserInteractions()
        .setErrorEventMapper(ErrorEventMapper())
        .trackLongTasks()
        .build()
    Rum.enable(rumConfig)
}

private fun setupTracesConfiguration() {
    val traceConfig = TraceConfiguration.Builder().build()
    Trace.enable(traceConfig)

    val tracer = AndroidTracer.Builder().build()
    GlobalTracer.registerIfAbsent(tracer)
}

private fun getConfiguration(): Configuration {

    return Configuration
        .Builder(
            clientToken = ...,
            env = ...,
            variant = ...,
            service = ...
        )
        .useSite(site = DatadogSite.EU1)
        .setCrashReportsEnabled(crashReportsEnabled = true)
        .setFirstPartyHosts(tracedHosts)
        .build()
}
```

```kotlin
class ViewTrackingStrategyProvider {

    private val activityPredicate = object : ComponentPredicate<Activity> {
        override fun accept(component: Activity): Boolean {
            return true
        }

        override fun getViewName(component: Activity): String? {
            return component.javaClass.simpleName
        }
    }

    private val fragmentPredicate = object : ComponentPredicate<Fragment> {
        override fun accept(component: Fragment): Boolean {
            // Skip Glide Fragments
            return (component is SupportRequestManagerFragment).not()
        }

        override fun getViewName(component: Fragment): String {
            return component.javaClass.simpleName.toString()
        }
    }

    @Suppress("deprecation")
    private val fragmentLegacyPredicate = object : ComponentPredicate<android.app.Fragment> {
        override fun accept(component: android.app.Fragment): Boolean {
            return true
        }

        override fun getViewName(component: android.app.Fragment): String {
            return component.javaClass.simpleName.toString()
        }
    }

    fun get() = MixedViewTrackingStrategy(
        trackExtras = true,
        componentPredicate = activityPredicate,
        supportFragmentComponentPredicate = fragmentPredicate,
        defaultFragmentComponentPredicate = fragmentLegacyPredicate,
    )
}
```

**Steps to reproduce the issue:**
Just use the app in version 2.x and open multiple screens.

**Describe what you expected:**
No views are duplicated, like version 1.x.

**Additional context**
 - Android OS version: 33
 - Datadog SDK version: 2.1.0
 - Gradle Plugins: 7.4.2

---

Let me know if I can help with any extra information.

Thanks!

**Comment by xgouchet** [comment]
Hi @orafaaraujo, and thanks for opening this issue. 

Indeed we might need more info to understand your use case.
When you say that views are duplicate, are you seeing views for the exact same Component twice? Is this happening for Activities, Fragment or both? If you add breakpoints in your `ComponentPredicate` implementations, do you see them called twice for a single component?

**Comment by orafaaraujo** [comment]
Hey @xgouchet 
Thanks for the fast reply 🙏

That's right! The same component appears twice, but one looks normal; the other is just empty.
It is happening with both (Activities and Fragments). 

![image-20230901-083544](https://github.com/DataDog/dd-sdk-android/assets/1668348/b5cebb7d-7a07-4eff-a4ea-b57333621827)

We'll also notice that the empty view record was recorded very quickly,  check the prints below. 

<img width="400" alt="image" src="https://github.com/DataDog/dd-sdk-android/assets/1668348/156e9f5c-4164-44f5-9d30-79276cfb0b23">

<img width="400" alt="image (1)" src="https://github.com/DataDog/dd-sdk-android/assets/1668348/e399059d-205d-46ec-8c5b-c5e2aac21ff9">

I'll debug the `ComponentPredicate` and we'll back with the results. 

Thanks!

**Comment by orafaaraujo** [comment]
Hey @xgouchet 

Yes, they appear twice on `ComponentPredicate`. Activities and fragments.

Thanks

**Comment by xgouchet** [comment]
Can you check to see if maybe the `Rum.enable(rumConfig)` line in your `startLibrary()` function is called twice?

**Comment by orafaaraujo** [comment]
Hey

Nops, we are not calling it twice. I think if we do it we would have duplicate Sessions too, it is not the case. 

> FYI, I'm working with @RamiTrabelsi in this update, so both of us can provide information.

**Comment by xgouchet** [comment]
When during your app's lifecycle are you calling the `startLibrary()` method? Is it always done on the same thread?

**Comment by RamiTrabelsi** [comment]
Hello @xgouchet, we're doing the call for `startLibrary()` on our `BaseApplication.onCreate()` once. We are launching it inside a Coroutines because we would like to remove the start-up from the main thread.

```kotlin
class BaseApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        
        ProcessLifecycleOwner.get().lifecycleScope.launch { dataDogSetup.startProvider() }
   }
}
```

**Comment by RamiTrabelsi** [comment]
Hello @xgouchet, debugged again and I'm 100% sure it's not called twice. I can see the breakpoint stopped only once.

Also, I want to highlight, that with this same setup before the migration (we were on version `1.19.3`), the issue did never happen before.

Another interesting point, is that the events that seem duplicated, they are not exactly the same. The pattern is that they always have the same `View Name` and the same `Relative Time`, if we check closer for example in the screenshots ([shared in this message](https://github.com/DataDog/dd-sdk-android/issues/1614#issuecomment-1715723394)) we can notice for example that the `View Time Spent` is different and always happen that one is in `μs` and the other one is in `ms`.

**Comment by xgouchet** [comment]
Yes, what seems to be happening is that our view tracking strategy is starting the same view twice. Because when starting a view, any previous active view is stopped, that explain why one of the duplicates only lasts a couple of `μs`. 

I'm sorry for asking you to debug this, with the breakpoint in your `ComponentPredicate`, can you check if they're called with the same instance of `ActivityViewTrackingStrategy` for instance (in theory it should)?
Also if you add a breakpoint in our `MixedViewTrackingStrategy.register()`, can you check if it's being called twice?

**Comment by RamiTrabelsi** [comment]
I can confirm that it's the same instance of `ActivityViewTrackingStrategy` that is called when it's happening twice.

Adding a breakpoint `MixedViewTrackingStrategy.register()`, it seems that it's not called while switching Views. I tested also by putting breakpoints on `MixedViewTrackingStrategy.onActivityResumed()` for example and this one is called.

**Comment by xgouchet** [comment]
The `MixedViewTrackingStrategy.register()` is called only once for it to start listening to Activity lifecycle events, at least it should be called only once. If it's the same `ActivityViewTrackingStrategy` calling twice, it means it's been added twice as listener to Activities lifecycle events.

**Comment by orafaaraujo** [comment]
Hello 👋 

If we don't include the `MixedViewTrackingStrategy`, the tracer is not duplicated, but we can see only `Activities`. 

```kotlin
// Commenting this line RumConfiguration call
// .useViewTrackingStrategy(strategy = strategyProvider.get())
```

btw, this class is marked as [deprecated](https://github.com/DataDog/dd-sdk-android/blob/206dcd2d524279b783ba5f22f9a0fee7a754b9a3/features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/MixedViewTrackingStrategy.kt#L29). Should we use another resource?

Thanks

**Comment by xgouchet** [comment]
Can you open a ticket in our official [Support page](https://www.datadoghq.com/support/), and link to this thread. The best way would be to have a call so that we can see this behavior in your code base and add the relevant breakpoints to find out what's happening here;

**Comment by RamiTrabelsi** [comment]
Hello @xgouchet, the first possible date to have a call and fix this seems to not be possible before the week of February 24th. Can we convene to any solution before? Otherwise, we won't be able to upgrade our SDK to v 2.x :(

**Comment by xgouchet** [comment]
Hi @RamiTrabelsi I'm pretty sure this was a typo I'll check with support to have a call much earlier than that
