### ISSUE TITLE
No view is active when custom tracking views

### ISSUE THREAD

**Issue by cipry13** [DataDog/dd-sdk-android#1617]
**Steps to reproduce the issue:**
Dummy sample:
```
class HomeFragment : Fragment() {
    private var fragmentBinding: FragmentHomeBinding? = null
    private val binding get() = fragmentBinding!!

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        if (fragmentBinding == null) {
            fragmentBinding = FragmentHomeBinding.inflate(inflater, container, false)

            binding.lifecycleOwner = viewLifecycleOwner
            binding.homeComposeView.setContent {
                MaterialTheme { HomeScreen() }
            }
        }

        return binding.root
    }
}

@Composable
fun HomeScreen(
    modifier: Modifier = Modifier
) {
    TrackScreen(viewName = "home")
    val viewModel = getViewModel<HomeViewModel>()
    val state = viewModel.uiState.collectAsStateWithLifecycle().value

    Box(modifier = modifier.fillMaxSize()) {
        HomeScreenContent(state = state)
        if(state.showDialog) DialogScreenContent()
    }
}

@OptIn(ExperimentalTvMaterial3Api::class)
@Composable
fun HomeScreenContent(
    modifier: Modifier = Modifier,
    onClick: () -> Unit
) {
    Box(modifier = modifier.fillMaxSize()){
        Button(
            onClick = trackClick(
                targetName = "home_button",
                onClick = onClick
            )
        )
    }
}

@Composable
fun DialogScreenContent(
    onDismiss: () -> Unit,
    modifier: Modifier = Modifier
) {
    TrackScreen(viewName = "dialog")

    Dialog(
        onDismissRequest = onDismiss,
        properties = DialogProperties(usePlatformDefaultWidth = false)
    ) {
        Box(modifier = modifier.fillMaxSize()) {
            // ... content
        }
    }
}

@Composable
fun TrackScreen(viewName: String) {
    DisposableEffect(
        key1 = Unit,
        effect = {
            GlobalRumMonitor.get().startView(viewName, viewName)
            Log.d("ViewLogger", "startView: $viewName")

            onDispose {
                GlobalRumMonitor.get().stopView(viewName)
                Log.d("ViewLogger", "stopView: $viewName")
            }
        }
    )
}
```
**Describe what you expected:**

What happens in the logs:
1. when home screen is displayed: startView: home
2. show dialog: startView: dialog
3. close dialog: stopView: dialog
4. open dialog again:
[_dd.sdk_core.default]: A RUM event was detected, but no view is active. To track views automatically, try calling the Configuration.Builder.useViewTrackingStrategy() method.
You can also track views manually using the RumMonitor.startView() and RumMonitor.stopView() methods.
startView: dialog

In Datadog RUM dashboard I would like to log a click event from the screen that the action was triggered.
In this case, once I use .stopView on the "dialog" view, "home" view lost without using the .stopView method.
I was expecting to be able to continue with the "home" view instead of having to start the "home" view again.

Is this the expected behaviour?

**Additional context**
- Datadog SDK version: latest (2.1.0)

**Comment by 0xnm** [comment]
Hello @cipry13!

`startView` / `stopView` methods of RUM are sequential and are not creating the stack in the same fashion as say Activities/Fragments are creating it when they are started and stopped.

This means that if you do `startView(A)` -> `stopView(A)` -> `startView(B)` -> `stopView(B)` in the end you don't have any active RUM view available (or in other words, after you call `startView(B)` view `A` won't be restored), so you need to write your custom view strategy keeping this in mind.

Speaking of reporting actions, one must have a RUM view active in order to report the action (so that it is associated to it) as the logcat entry says.

You may also check our `dd-sdk-android-compose` module which contains `NavigationViewTrackingEffect` to help track views in case of Navigation library usage.
