### ISSUE TITLE
Is Android Client Thread Safe?

### ISSUE THREAD

**Issue by georgeBanno** [DataDog/dd-sdk-android#1624]
More of a question than an Issue. We have a case where we are logging on different threads in the Android app.  Looking at the Datadog Android Client code nothing jumped out at me that would indicate synchronization is being done with the logger.  Is the logger Thread Safe or should we instantiate a new one on each thread?

**Comment by 0xnm** [comment]
Hello @georgeBanno!

Yes, `Logger` class is thread-safe, so you can pass the same instance around the threads. Its [shared state](https://github.com/DataDog/dd-sdk-android/blob/85087f339053523ae189dae3f20dbcb899cf6c2e/features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/Logger.kt#L40-L41) is able to address concurrency and all the elements used down the processing pipeline handle concurrency on the client side as well.
