### ISSUE TITLE
Some button actions and Alert view actions were not logging in DataDog RUM Android

### ISSUE THREAD

**Issue by manojKumar-L** [DataDog/dd-sdk-android#1671]
Thanks for taking the time for reporting an issue!

**Describe what happened**
- Whenever Alerts were shown/dismissed in the Android application, its view was not logging in DataDog RUM
- Some of the button click actions were not logging in to the RUM

**Steps to reproduce the issue:**
- Follow the Initial Process of DataDog Rum 
**Describe what you expected:**
- I would like to log all the alert view events and all click actions to the RUM
**Additional context**
 - Android OS version: 13
 - Device Model: Samsung M53
 - Datadog SDK version: 2.2.0
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins: 8.1.1

**Comment by mariusc83** [comment]
Also are you using the old `AlertDialog` API or the new one based on the `DialogFragment` ?

**Comment by manojKumar-L** [comment]
Hi, @mariusc83, Thanks for your quick reply. In my Application, I am using both **AlertDialog API** and **DiaglogFragment.**
I am getting my View and Action logged on DataDog RUM for the DialogFragment, Only for all the AlertDialog APIs the view and actions are not logging.

>> _can you tell us if you do not get any Action event on your Alert window or just some of them ?_
I am not getting action events for all the Alert windows which are all using **AlertDialog API**

**Comment by mariusc83** [comment]
Hi @manojKumar-L , thank you for your reply and this confirms our investigation. Basically we do not support automated tracking for actions and view events in `AlertDialog`. We will be working on this probably this quarter or beginning of next year. For now the alternative would be for you to use our manual RUM API on those dialogs. We will add a not on this issue once this feature will be supported.

**Comment by manojKumar-L** [comment]
Thank you again @mariusc83 for your quick reply and suggestions.
Can I ask for another clarification here before closing this Issue,
When I Initialised the DataDog in My Application class, All the events of my Application were logging in Rum as expected But when I initialised DataDog from Fragment (After some time my Application was launched) not all the events were logging in Rum,
It skips some of the Fragment View and Button Click events to log in to the DataDog RUM.

Is there any reason for this scenario OR we should only initialize the DataDog in the Application alone?

**Comment by manojKumar-L** [comment]
Hi @mariusc83 Do I have any answer to the previous question about missing some action/view to be logged when initializing DataDog in Fragment?

**Comment by manojKumar-L** [comment]
Thanks for your feedback @mariusc83, I am closing this issue for now, If you included a new feature for logging AlertDialog please mention it in this issue.
