### ISSUE TITLE
Inconsistent in Logging RUM events when initializing DataDog in Fragment

### ISSUE THREAD

**Issue by manojKumar-L** [DataDog/dd-sdk-android#1673]
Thanks for taking the time for reporting an issue!

**Describe what happened**
- When I initialized DataDog on the Fragment some of my click events and View events were not tracked in the DataDog RUM.

**Steps to reproduce the issue:**
- Initialise the DataDog Rum in Fragment (starting screen of your Application)

**Describe what you expected:**
- I would like to log all the click events and view events to the RUM

**Additional context**
 - Android OS version: 13
 - Device Model: Samsung M53
 - Datadog SDK version: 2.2.0
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins: 8.1.1

**Comment by 0xnm** [comment]
Hello @manojKumar-L! Can you please share your initialization snippet of Datadog SDK and also tell us at which point you do this exactly (like is it `Fragment#onResume`)?

We recommend initializing Datadog SDK in the `Application#onCreate` instead to get a complete tracking of the views in your application, because all the RUM actions (clicks, taps), resource calls are tracked in the context of the view (which should be captured as well by our instrumentation), and if there is no RUM view active, RUM action will be dropped (you probably can see such warnings in the logcat).

**Comment by manojKumar-L** [comment]
Hello @0xnm, I am Initialising DataDog on the **Interface**  which I override on my **Fragment**, I have attached my initialization snippet for your reference, 
`val configuration = Configuration.Builder(
            clientToken = datadogCredentials.clientToken,
            env = datadogCredentials.environment,
            variant = release
        )
            .useSite(EU1) 
            .setUploadFrequency(UploadFrequency.FREQUENT) 
            .setBatchSize(BatchSize.SMALL) 
            .build()
        Datadog.initialize(application, configuration, trackingConsent=TrackingConsent.GRANTED)
        val rumConfiguration = RumConfiguration.Builder(applicationID)
            .trackUserInteractions()
            .trackLongTasks(300L)
            .useViewTrackingStrategy(MixedViewTrackingStrategy(true))
            .build()
        Rum.enable(rumConfiguration)`

Regarding Warning, I am getting the below warning in my LogCat, If I initialize DataDog on my Fragment
![image](https://github.com/DataDog/dd-sdk-android/assets/87462107/0beca681-7823-40aa-8e77-5f90579f0512)

If I initialize DataDog on My Application then I receive the value for processImportance as 100,

Is there any way that I can log all the actions without initializing DataDog on my Application or I should only initialize it on my Application?

**Comment by 0xnm** [comment]
We still recommend to initialize Datadog SDK as early as possible in your application, meaning in the `Application#onCreate` if possible. Do you do initialization during some `Fragment#onResume` lifecycle step of your application?

Regarding different `processImportance`: does your application have by any chance activities running in the different process (by leveraging [the following property](https://developer.android.com/guide/topics/manifest/activity-element#proc))?
