### ISSUE TITLE
[Q] Will application_start event reports only cold startup?

### ISSUE THREAD

**Issue by ken-kentan** [DataDog/dd-sdk-android#1676]
Hi, this is just a question and not either bug nor feature request.

Datadog performance dashboard reports App Startup Time as Mobile Vitals.
Is the duration about cold startup? or both cold warn startup?

We are going to have a threshold to monitor our app startup time, but we would like to set the threshold based on the startup type.
So I'm wondering if we can assume the reported time is only cold startup.

**Comment by 0xnm** [comment]
Hello @ken-kentan!

Currently our SDK doesn't make a distinction between `warm` and `cold` start. We may consider it for the future, but as of now there are no APIs in Android to know this OOTB and the existing solutions are based on heuristics or can be fragile.

**Comment by ken-kentan** [comment]
Hello Nikita!

Thank you for answering my question, we will handle that the report includes any kind of startup.
