### ISSUE TITLE
Confusion about dependency versions

### ISSUE THREAD

**Issue by StylianosGakis** [DataDog/dd-sdk-android#1679]
As I wanted to add some OkHttp integration with datadog I noticed that the artifact `dd-sdk-android-okhttp` exists, which is on version 2.2.0
Then I realized `dd-sdk-android-core` is also on version `2.2.0`.
However the artifact `com.datadoghq:dd-sdk-android` is on version `1.19.3`, and this is the one I've been historically using. Moreover, this github repo seems like is tagged with 2.2.0.

This is a bit confusing, is it possible that I mixing dependencies that I should not be mixing together? Should I be using something else instead of `com.datadoghq:dd-sdk-android`? Perhaps there's replacement for this in various `com.datadoghq:dd-sdk-android-FOO` exactly like the `-core` and the `-okhttp` dependencies are? Maybe there are equivalents for RUM and whatever else I may be using?

If there's some documentation around this I'd love to read it to get a clearer picture for myself here.

**Comment by StylianosGakis** [comment]
It seems like there is in fact a `com.datadoghq:dd-sdk-android-rum` as I imagined.
Is this some sort of effort to split the original big module perhaps, and if possible I can just drop `com.datadoghq:dd-sdk-android` as soon as I can just depend on all the other individual versions instead?

This would also explain very well why when I added the OkHttp module I was suddenly getting access to two `DatadogInterceptor` in `com.datadog.android.okhttp.` and in `com.datadog.android.`.

Is this documented somewhere which I just completely missed perhaps 🫣

**Comment by 0xnm** [comment]
Hello @StylianosGakis!

Yes, this is mention in our [migration guide](https://github.com/DataDog/dd-sdk-android/blob/develop/MIGRATION.MD) and it is referenced from [version 2.0.0 release notes](https://github.com/DataDog/dd-sdk-android/releases/tag/2.0.0). You shouldn't use `dd-sdk-android` artifact for version 2+.

**Comment by StylianosGakis** [comment]
Yup had completely missed this. I wonder how I could've known this? I am not asking here to pass judgement in any way, I am just curious if other people have had this question directed at you after the 2.x release.

Renovate did not suggest bumping since it's a different artifact ID.
The readme does not contain a link to the migration guide.
And the docs themselves are referring to the new artifacts, but as a user of 1.x already, when I went to the docs to see something, I didn't even consider checking if my artifact ID was correct as I thought I was already up to date.
The migration file exists, but prior to this discussion I would've never just stumbled upon the github project, check the files until my eye caught that file and I even felt compelled to click it.

You see what I mean? Is there something else that can be done (or is done already and I completely missed it) to compel devs to learn about the verison bump?

**Comment by 0xnm** [comment]
Hello @StylianosGakis!

We are relying on [semver](https://semver.org/) conventions when changing the versions of our SDK. Since it was a major version change, breaking changes in API are expected and so we expect users to check the [release notes](https://github.com/DataDog/dd-sdk-android/releases/tag/2.0.0) when doing SDK upgrade. Generally we see customers adopting SDK v2 without any major issues.

We will consider the issue you had during the SDK upgrade and will add more visibility by adding the necessary references and statements to our `README` file and docs.

**Comment by StylianosGakis** [comment]
Right, my point was mostly that the one dependency which I was using before didn't change (the `com.datadoghq:dd-sdk-android` that is). The only reason I ever went inside here to see the release notes in the first place is that I happened to have to do some changes in our datadog setup. Otherwise I would've never noticed it.
And thanks a lot for the clarification and the links provided, it helped me with pulling off the migration 😊
