### ISSUE TITLE
App does not log when background service had been running

### ISSUE THREAD

**Issue by alparp27** [DataDog/dd-sdk-android#169]
Thanks for taking the time for reporting an issue!

**Describe what happened**
When app is launched, logs are recorded.  But if only background service had been running, logs are not recorded.

**Steps to reproduce the issue:**
1. Initiate data dog in application (not activity) to make sure it should be initialized even when background service has started.
2. Start background service with some intent, log few lines.  
3. Check data dog log explorer, do not launch app.
4. If user launches app, logs are seen in log explorer on same build

**Describe what you expected:**
Logs were logged both the times

Please advise if 
1. I missed a setting (read through the document but could not find anything relevant).
2. Perhaps initialization is missing setting up user id such that user can be uniquely identified, I am not sure there is mandatory call is missing

**Additional context**
 - Android OS version: tried on various OS
 - Device Model: Various device models
 - Datadog SDK version:1.2.1
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins:

**Comment by mariusc83** [comment]
Hi @alparp27 , thank you for taking the time to report this, we will investigate this problem on our end and will get back to you with more info the following days.

**Comment by xgouchet** [comment]
Hi @alparp27 can you provide a code sample on how you create and start your service. Alsot do you know how long that service is alive ? 
Our first guess on this issue is that your service starts and stops too fast for our upload thread to send anything.

**Comment by alparp27** [comment]
In android application:
Datadog.initialize(this, BuildConfig.DD_CLIENT_TOKEN);

In Logger:
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                    datadogLogger = new Logger.Builder()
                            .setNetworkInfoEnabled(true)
                            .setServiceName(SERVICE_NAME)
                            .setLogcatLogsEnabled(true)
                            .setDatadogLogsEnabled(true)
                            .setLoggerName(BuildConfig.DEBUG ? LOGGER_NAME_STAGE : LOGGER_NAME_PROD)
                            .build();
                }

Normally background app will run for at least 1 minute to several hours.

**Comment by alparp27** [comment]
Please note that we used datadog to replace older service that we use to use and older service was able to log everything successfully.

I look at all my events I cant find ones without user_id.  I was wondering if that is my code error where user_id is not specified and then it is filtering error, perhaps logs are coming in and I don't see it.

**Comment by xgouchet** [comment]
Is your background service running as an IntentService ? Or are you making it foreground with a Notification ?
Using the latest stable SDK `1.3.0`, add the following line after you initialize the SDK in your application : 
```
Datadog.setVerbosity(Log.Verbose);
```

Then you should see some info about the SDK in the logcat, among other whether it sends the logs and if the upload works.

**Comment by alparp27** [comment]
Is there a way for me to catch those into crashlytics when upload does not work?

**Comment by xgouchet** [comment]
You mean catching those logs ? No I don't think so.

**Comment by xgouchet** [comment]
I've been testing starting some background services, and log upload does work from those, so maybe there's something else that prevent logs from being uploaded in your service.

**Comment by xgouchet** [comment]
@alparp27 can you share the service source code (maybe removing sensitive/proprietary code) so that we can reproduce the issue on our side ?

**Comment by alparp27** [comment]
This has been working fine sice that one instance.
