### ISSUE TITLE
Datadog SDK is logging very high application start time in some RUM traces

### ISSUE THREAD

**Issue by agnihotriayush** [DataDog/dd-sdk-android#1765]
Thanks for taking the time for reporting an issue!

**Describe what happened**
We have found some traces Application_start with duration around 33 minutes. Since app start time calculation is performed inside the SDK itself. It is difficult to understand what might be the probable reasons for this.

I would like to know, if this is bug with sdk or what can be the steps to figure out the possibilitiy of this kind of Application_start event with very high launch time.
<img width="1202" alt="Screenshot 2023-12-14 at 5 04 35 PM" src="https://github.com/DataDog/dd-sdk-android/assets/59553955/79680eed-f0ff-4cee-9a9c-2c316453a83a">

**Additional context**
 - Android OS version: 13
 - Device Model:
 - Datadog SDK version: 1.19.3
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins:1.9.0

**Comment by mariusc83** [comment]
@agnihotriayush we noticed that you are using an old version of our sdk (v1.19.3). Please have in mind that our most recent version is v2.3.0. As a first step can you please update to the last version and see if the problem is still there ? Thanks !!

**Comment by agnihotriayush** [comment]
@mariusc83 Sure, I will update it to most recent version and will update here if this fixes the issue.

**Comment by 0xnm** [comment]
Hello @agnihotriayush! Do you have any update regarding this issue?
