### ISSUE TITLE
Support for Kotlin Multiplatform and Ktor

### ISSUE THREAD

**Issue by ThomasRichtsfeld** [DataDog/dd-sdk-android#1773]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name :  `KMP, Ktor`
- Library type: KMP library
- Library version: ktor version. 2.3.4

**Is your feature request related to a problem? Please describe.**
We are currently using Ktor in one of our KMP modules. None of the network calls are reported in Datadog. All the other network calls that are done with retrofit are reported.

**Describe the solution you'd like**
If Datadog is installed in the App module it should automatically trace the network requests that are done with the Ktor HttpClient

**Describe alternatives you've considered**
We didn't find an alternative solution

**Comment by jonathanmos** [comment]
hi @ThomasRichtsfeld, thanks for this feature request. We don't currently have plans to support `KMP`. Regarding `Ktor` we will discuss and see whether it is possible.

**Comment by ThomasRichtsfeld** [comment]
From our POV we don't need support for KMP, as long as tracing works for Ktor out of the box.

Thanks for the update @jonathanmos

**Comment by tassilo-posegga** [comment]
Any updates on this ussue? It looks like we are not the only ones with this need: https://www.reddit.com/r/ktor/comments/10584a3/ktor_client_tracing_and_monitoring_for_a_kotlin/

**Comment by 0xnm** [comment]
Hello @tassilo-posegga! There is no update on this topic so far, it is not at the top of our list, but if we see that this feature is highly requested this will definitely change its priority for us.

**Comment by christer-hansen** [comment]
Ktor is growing bigger and bigger, it would be great to have support for this.

**Comment by MaelNamNam** [comment]
Hi everyone 👋

Good news: we recently released a KMM SDK in private beta. It currently supports
1. RUM (incl. crash reporting, network request tracking through Ktor, and webview tracking),
2. Logs,
3. and frontend-to-backend APM distributed tracing,

both for iOS and Android.

There are some caveats and the feature set isn't 100% complete obviously, but we're actively looking for more customers to partner with us and help us shape the roadmap for this new SDK.

So if you're welling to give it a try, could you reach out to your account manager (or to [support](https://www.datadoghq.com/support/)) to get this enabled for your organisation please (not through this thread for obvious confidentiality reasons 😊)?

**Comment by ThomasRichtsfeld** [comment]
> Hi everyone 👋
> 
> Good news: we recently released a KMM SDK in private beta. It currently supports
> 
> 1. RUM (incl. crash reporting, network request tracking through Ktor, and webview tracking),
> 2. Logs,
> 3. and frontend-to-backend APM distributed tracing,
> 
> both for iOS and Android.
> 
> There are some caveats and the feature set isn't 100% complete obviously, but we're actively looking for more customers to partner with us and help us shape the roadmap for this new SDK.
> 
> So if you're welling to give it a try, could you reach out to your account manager (or to [support](https://www.datadoghq.com/support/)) to get this enabled for your organisation please (not through this thread for obvious confidentiality reasons 😊)?

That's great news 🥳 

Would we also need to update our SDK on the clients (Android and iOS) or is this only a setting in our admin panel on the web

**Comment by 0xnm** [comment]
Hello @ThomasRichtsfeld! It is a new SDK (which is using Android/iOS SDKs) under the hood, so you will have to integrate it in your app.

**Comment by ThomasRichtsfeld** [comment]
@0xnm can you share the version with us?
I guess we can then just integrate the SDK on Android/iOS and test if the data shows up correctly on the web without changing anything else. Am I right?

**Comment by 0xnm** [comment]
@ThomasRichtsfeld Please contact our support, because anyway KMP SDK functionality on web needs to be activated per organization basis and we don't have any public docs yet.

**Comment by 0xnm** [comment]
We now have [Kotlin Multiplatform SDK repository](https://github.com/DataDog/dd-sdk-kotlin-multiplatform) opened as public and we also published the [necessary documentation](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/kotlin-multiplatform/).

Kotlin Multiplatform SDK still stays in the PREVIEW, so if you want to use it open a ticket with our support to activate it for your org.
