### ISSUE TITLE
RUM Resources `RumResourceMethod` enum is missing HTTP request method names

### ISSUE THREAD

**Issue by jraska** [DataDog/dd-sdk-android#1816]
**Is your feature request related to a problem? Please describe.**
Hi, 

1. RUM resources reporting introduced in October 2023 [enum RumResourceMethod](https://github.com/DataDog/dd-sdk-android/blob/develop/features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumResourceMethod.kt) to constrain reported HTTP method names https://github.com/DataDog/dd-sdk-android/pull/1653
2. The enum is having a subset of HTTP method names, missing `TRACE`, `OPTIONS` and `CONNECT` and defaulting to `GET` for those.
3. The question is if this is deliberate? These methods are way less likely to be used.

**Describe the solution you'd like**
- Add `TRACE`, `OPTIONS` and `CONNECT` method names into the `RumResourceMethod` and all related code as `ResourceEvent` and `ErrorEvent`.

**Describe alternatives you've considered**
- Accept `"GET"` being reported for such methods as these method names are used rarely, but it is possible.

**Additional context**
- [RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110#name-method-definitions) defining TRACE, OPTIONS and CONNECT
- [HTTP Wikipedia](https://en.wikipedia.org/wiki/HTTP#Request_methods)

**Comment by 0xnm** [comment]
Hello @jraska!

Indeed, it is a known issue and we have it already in our backlog. No ETA for the change though, these methods are not used very frequently (and they will need changes on our backend).

**Comment by 0xnm** [comment]
The change will land in the `2.6.0` release.

**Comment by 0xnm** [comment]
The fix is a part of the [2.6.0 release](https://github.com/DataDog/dd-sdk-android/releases/tag/2.6.0).
