### ISSUE TITLE
TextView's compound drawables rendered smaller when enabling SessionReplay

### ISSUE THREAD

**Issue by MassimoDjungle** [DataDog/dd-sdk-android#1857]
As you can see in the attached screenshot, the `drawableStart` of the `TextView` is rendered smaller than it should be. It is a vector drawable passed through the `app:drawableStartCompat` attribute of the `TextView`.
This happens in every single `TextView` using a compound drawable (the start one or the end one), only when the drawables are vector drawables, and only when enabling SessionReplay, e.g.:

```
SessionReplay.enable(
    sessionReplayConfiguration = SessionReplayConfiguration.Builder(100f)
        .build()
)
```

<img width="300" alt="SessionReplay enabled" src="https://github.com/DataDog/dd-sdk-android/assets/107140931/5ea2b232-2f6c-4cb7-a9fb-d355162dd773">

This is how the compound drawable should be:
<img width="300" alt="SessionReplay disabled" src="https://github.com/DataDog/dd-sdk-android/assets/107140931/af2ee1c8-7e38-4c1d-8f62-0ae5ef1798d8">

**Additional context**
 - It happens in all Android versions; I've tested on a Google Pixel 4a with Android 13 and on a Xiaomi Redmi Note 8 Pro with Android 11, and in different emulators with Android 10 and higher, the same problem in all of these devices.
 - The problem is surely present in the Datadog SDK v.2.5.0 and v2.5.1. Version 2.1.0 does not have this bug; it seems to have been introduced in v2.2.0.
 - Proguard configuration is not important: it happens when minified and when not minified, debug or release build.
 - Gradle Plugins: 8.2.2

**Comment by mariusc83** [comment]
Hi @MassimoDjungle thank you for taking the time to report this issue. We will analyse this internally and get back on this thread.

**Comment by mariusc83** [comment]
Hi @MassimoDjungle after analyzing this internally we've concluded that this indeed is a limitation in our current recorder and we opened a task in our backlog to handle this properly. This will probably be available in our next release. We will get back on this thread with a notification once this was merged.

**Comment by jonathanmos** [comment]
Hi @MassimoDjungle, a fix for this has been merged so you should see it resolved with the next release. I'm closing this issue for now - please let us know if after the next release you continue to see the issue.
