### ISSUE TITLE
Tracer and OkHttp: what happen when apply sampler for both of them?

### ISSUE THREAD

**Issue by alecarnevale** [DataDog/dd-sdk-android#1892]
### Question

Hi there, I have some questions about sampling.
I'm sorry if my doubts are documented somewhere, but I didn't find anything here or in the official doc.

Looking into the code, I found two different `Sampler` interfaces:
- one into [android-core](https://github.com/DataDog/dd-sdk-android/blob/6d24e01d7065137a7940db04d0e0b41e195ebe60/dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/sampling/Sampler.kt#L14)
- another into the [android-trace](https://github.com/DataDog/dd-sdk-android/blob/6d24e01d7065137a7940db04d0e0b41e195ebe60/features/dd-sdk-android-trace/src/main/java/com/datadog/trace/common/sampling/Sampler.java#L15)

As far as I understood the former is applied at [OkHttp level](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/android/?tab=kotlin#okhttp), the latter when you register an `AndroidTracer` through `AndroidTracer.Builder().setSampleRate(double)`.

---

My first doubt is how do the two work together? What If I apply both of them?
Correct me if I'm wrong, but looking into the code:
- given that you set `AndroidTracer.Builder().setSampleRate(globalRate)`;
- given that you added a `DataDogInterceptor` (application) or a `TracingInterceptor` (network) with a `RateBasedSampler`;
- the `RateBasedSampler` is [triggered at the network level](https://github.com/DataDog/dd-sdk-android/blob/6d24e01d7065137a7940db04d0e0b41e195ebe60/integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt#L289) and some span is sampled;
- then the sampled span is [injected](https://github.com/DataDog/dd-sdk-android/blob/6d24e01d7065137a7940db04d0e0b41e195ebe60/integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt#L529) into the `AndroidTracer`;
- then the sampler set with the `globalRate` [is applied](https://github.com/DataDog/dd-sdk-android/blob/6d24e01d7065137a7940db04d0e0b41e195ebe60/features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/DDTracer.java#L329).

Is this flow correct?

---

My second doubt is about the [DeterministicSampler](https://github.com/DataDog/dd-sdk-android/blob/6d24e01d7065137a7940db04d0e0b41e195ebe60/features/dd-sdk-android-trace/src/main/java/com/datadog/trace/common/sampling/DeterministicSampler.java#L18) implementation of the `andorid-core` sampler.
Is it a [head-based sampling](https://docs.datadoghq.com/tracing/guide/ingestion_sampling_use_cases/#solution-head-based-sampling) like the [TraceIdRatioBased OpenTelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#traceidratiobased) sampler?

This is specifically to understand if apply the `DeterministicSampler` into the Android client and a [TraceIdRatioBased](https://docs.datadoghq.com/opentelemetry/guide/ingestion_sampling_with_opentelemetry/#sdk-level-sampling) on some backend services as well, means that when a span is sampled from the Android client then also the related spans for the same _trace_id_ are sampled on the backend as well.

**Comment by xgouchet** [comment]
Hi @alecarnevale  and thanks for contacting us. 

Regarding the sampling rates from the AndroidTracer and the TracingInterceptor, they are as you thought cumulative. 
The former one simply asks how many spans (out of all the one the tracer receives) should be kept, and the latter asks how many network requests should have a span created for it. 

And indeed the sampling works as Head Based sampling, as describe in the documentation you're mentionning. In theory the DeterministicSampler should give you the same sampling on both Android and the Backend, assuming we use the same Deterministic sampling algorithm (our Android implementation uses the same implementation as our Backend Java Agent).

**Comment by alecarnevale** [comment]
Hi @xgouchet thanks for your reply, that's all clear now.
