### ISSUE TITLE
integration issue 

### ISSUE THREAD

**Issue by AhmedShaabanElhdad** [DataDog/dd-sdk-android#1898]
### Describe the bug

**Could not find com.datadoghq:dd-sdk-android-gradle-plugin:2.1.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/datadoghq/dd-sdk-android-gradle-plugin/2.1.0/dd-sdk-and**
       
       
// Top-level build file where you can add configuration options common to all sub-projects/modules.       
```
buildscript {
    dependencies {
        classpath("com.datadoghq:dd-sdk-android-gradle-plugin:2.1.0")
    }
}
```

``` kotlin
plugins {
    id 'com.android.application' version '7.2.0' apply false
//    id 'com.datadoghq.dd-sdk-android-gradle-plugin' version '2.1.0' apply false
}
```
in app gradle

```kotlin
plugins {
    id 'com.android.application'
    id 'com.datadoghq.dd-sdk-android-gradle-plugin'
}
android {
   ....
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    ....
}

dependencies {
implementation "com.datadoghq:dd-sdk-android-rum:2.1.0"
    implementation "com.datadoghq:dd-sdk-android-rum-coroutines:2.1.0"
    implementation "com.datadoghq:dd-sdk-android-trace:2.1.0"
    implementation "com.datadoghq:dd-sdk-android-glide:2.1.0"
}
```

in settings.gradle

``` kotlin
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
//        maven { url "https://dl.bintray.com/datadog/datadog-maven" }
//        maven { setUrl("https://plugins.gradle.org/m2/") }
    }
}
```

### Reproduction steps

// Top-level build file where you can add configuration options common to all sub-projects/modules.       
```
buildscript {
    dependencies {
        classpath("com.datadoghq:dd-sdk-android-gradle-plugin:2.1.0")
    }
}
```

``` kotlin
plugins {
    id 'com.android.application' version '7.2.0' apply false
//    id 'com.datadoghq.dd-sdk-android-gradle-plugin' version '2.1.0' apply false
}
```
in app gradle

```kotlin
plugins {
    id 'com.android.application'
    id 'com.datadoghq.dd-sdk-android-gradle-plugin'
}
android {
   ....
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    ....
}

dependencies {
implementation "com.datadoghq:dd-sdk-android-rum:2.1.0"
    implementation "com.datadoghq:dd-sdk-android-rum-coroutines:2.1.0"
    implementation "com.datadoghq:dd-sdk-android-trace:2.1.0"
    implementation "com.datadoghq:dd-sdk-android-glide:2.1.0"
}
```

in settings.gradle

``` kotlin
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
//        maven { url "https://dl.bintray.com/datadog/datadog-maven" }
//        maven { setUrl("https://plugins.gradle.org/m2/") }
    }
}
```

### Logcat logs

A problem occurred configuring root project 'BeHyve'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.datadoghq:dd-sdk-android-gradle-plugin:2.1.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/datadoghq/dd-sdk-android-gradle-plugin/2.1.0/dd-sdk-android-gradle-plugin-2.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/datadoghq/dd-sdk-android-gradle-plugin/2.1.0/dd-sdk-android-gradle-plugin-2.1.0.pom
       - https://repo.maven.apache.org/maven2/com/datadoghq/dd-sdk-android-gradle-plugin/2.1.0/dd-sdk-android-gradle-plugin-2.1.0.pom
       - https://jitpack.io/com/datadoghq/dd-sdk-android-gradle-plugin/2.1.0/dd-sdk-android-gradle-plugin-2.1.0.pom
     Required by:
         project :

### Affected SDK versions

2.1.0

### Latest working SDK version

2.1.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Kotlin / Java version

1.8.10

### Gradle / AGP version

gradle-7.4-bin.zip

**Comment by 0xnm** [comment]
Hello @AhmedShaabanElhdad! Our Gradle Plugin is following different versioning compared to our SDKs, you can find the list of the versions available [here](https://plugins.gradle.org/plugin/com.datadoghq.dd-sdk-android-gradle-plugin).

The latest one available is `1.12.0`.
