### ISSUE TITLE
Rum works but logger don't send logs

### ISSUE THREAD

**Issue by Jaeger87** [DataDog/dd-sdk-android#1931]
### Describe the issue

After following all the steps in the official guide, I can see sessions on Rum monitor, but in the log page i don't see any kind of log.

I can share the piece of code where I configure the logger.

### Reproduction steps

        if(data.activeLogger) {
            LogsConfiguration logsConfig = new LogsConfiguration.Builder().build();
            Logs.enable(logsConfig);
            logger = new Logger.Builder()
                    .setNetworkInfoEnabled(true) //Add the network.client.connectivity attribute to all logs. The data logged by default is connectivity (Wifi, 3G, 4G…) and carrier_name (AT&T - US). carrier_name is only available for Android API level 28+.
                    .setLogcatLogsEnabled(false) //	Set to true to use Logcat as a logger.
                    .setRemoteSampleRate(data.loggerSampleSessionsRate)//Set the sampling rate for this logger. All the logs produced by the logger instance are randomly sampled according to the provided sample rate (default 1.0 = all logs). Note: The Logcat logs are not sampled.
                    .setBundleWithRumEnabled(true) //Set to true (default) to bundle the logs with the current RUM context in your application. This parameter lets you display all the logs sent while a specific View is active by using the Datadog RUM Explorer.
                    .setBundleWithTraceEnabled(true)//Set to true (default) to bundle the logs with the active trace in your application. This parameter lets you display all the logs sent during a specific trace by using the Datadog dashboard.
                    .setName(data.loggerName)//Set <LOGGER_NAME> as the value for the logger.name attribute attached to all logs sent to Datadog.
                    .build();
            Log.d("DATADOGLogger enabled: ", "" + Logs.isEnabled());
        }

//loggerSampleSessionsRate is 100

### SDK version

2.6.2

**Comment by Jaeger87** [comment]
In my logcat I found this:

[_dd.sdk_core.default]: Batch 665f71e1-175f-4be1-8afb-4787f7e0c95f [1244 bytes] (Logs Request) sent successfully.

But i don't see any log in my log page.

**Comment by xgouchet** [comment]
Hi @Jaeger87 , can you check in your Datadog Logs Pipeline if you have some rules that could discard the logs sent from Mobile Devices. We've seen that in the past in large organisation, one team would create a rule with a broad filter that would impact mobile logs unknowingly.

**Comment by Jaeger87** [comment]
I'll check it, but i can tell you that I implemented Rum and logs for same app in iOS and I can see logs for the iOS version.

**Comment by Jaeger87** [comment]
Ok, I found my logs!

From RUM Session I can see the logs of that session, if I click one of them they are showed in log page.

I noticed that the service name is the app path name "com.mycompany.myapp". Can I change it? Thank you!

**Comment by xgouchet** [comment]
Hi, indeed the service name of the application uses the application's package name as it's a unique identifier used both by the Play store and the Android OS. 
You can override this when creating your Logger as follow : 

```
val myLogger = Logger.Builder().setService("my_service").build()
```

**Comment by Jaeger87** [comment]
Thank you!
