### ISSUE TITLE
Remove a default attribute

### ISSUE THREAD

**Issue by Jaeger87** [DataDog/dd-sdk-android#1937]
### Question

Hi, is possible to remove a [default attribute](https://docs.datadoghq.com/standard-attributes/?product=android) for instance the ones about the geolocalization?

Thank you!

**Comment by xgouchet** [comment]
Hi @Jaeger87 , the geolocation attributes are set by the servers when ingesting the data. You can disable this when editing your RUM application [settings](https://docs.datadoghq.com/data_security/real_user_monitoring/#geolocation).

If you're talking about Logs, then you can disable the automatic Logs pipeline which applies to Android Logs.

**Comment by 0xnm** [comment]
Hi @Jaeger87! I believe your question is now answered, so I'm closing this issue. Don't hesitate to re-open it if needed.
