### ISSUE TITLE
setTelemetrySampleRate, explanation

### ISSUE THREAD

**Issue by Jaeger87** [DataDog/dd-sdk-android#1980]
### Question

What should I expect if I change the telemetry value?

**Comment by xgouchet** [comment]
Hi @Jaeger87 , this api is there to set the sample rate for Internal Telemetry. Essentially this allows you to limit or expand how much data we (Datadog) can track about how the SDK works. This lets us keep a track on the performance and usage of the SDK. 
By default it's set to 20%.

**Comment by Jaeger87** [comment]
Ok, now is clear what telemetry means, thank you!
