### ISSUE TITLE
How to group views as Service?

### ISSUE THREAD

**Issue by manju1375** [DataDog/dd-sdk-android#2033]
### Question

We are tracking views using GlobalRumMonitor.get().startView(viewKey, viewName, viewAttributes) within Android Application.

We got requirement to track multiple views which performs certain actions under one service/tag.
The above can be achieved within WebApp using datadogRum.startView({ viewName, service });

Is there any way to achieve the same within Android App?

the service can be initialised at the time of SDK initialisation within Android. 
Is there way to change the service name to group of views dynamically?

Any help/links/refs/docs will be much appreciated. Thanks in Advance.

**Comment by xgouchet** [comment]
Hi @manju1375 ,

We do not have a way to change the service per view in Android. But it'd be fairly easy to add a custom attribute in the call to   `GlobalRumMonitor.get().startView(…)`, such as `view.service` for instance. Doing so would allow you to split your views accordingly.
