### ISSUE TITLE
Fragment views stopped getting registered 

### ISSUE THREAD

**Issue by satyajitvure91** [DataDog/dd-sdk-android#2071]
### Describe the bug

I've integrated DD Rum into my android project and initially the fragments were showing up in the visited screens tab. I was playing with a custom fragment predicate to filter some views and ever since the fragments stop showing up altogether. Now only ApplicationLaunch shows up in the tab.

### Reproduction steps

```
RumConfiguration.Builder(applicationId = key)
            .useViewTrackingStrategy(
                FragmentViewTrackingStrategy(
                    trackArguments = true,
                    supportFragmentComponentPredicate = FragmentPredicate()
                )
            ).build
```

### Expected behavior

Fragment views should show up as the user navigates through the app.

### Affected SDK versions

2.8.0

### Latest working SDK version

-

### Did you confirm if the latest SDK version fixes the bug?

No

**Comment by 0xnm** [comment]
Hello @satyajitvure91!

Can you please check that the custom predicate you've created doesn't reject all the views? Basically please make sure that `ComponentPredicate#accept` doesn't return `false` all the time.

If it is not the case, can you please set SDK logging verbose to `debug` by calling `Datadog.setVerbosity` and check if you have any SDK logs in the Logcat which make be relevant to the issue you are experiencing.

**Comment by satyajitvure91** [comment]
Hey @0xnm 

Based
