### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Recording currently in progress - missing #endRecording() call?

### ISSUE THREAD

**Issue by leedawonswing** [DataDog/dd-sdk-android#2078]
### Describe the bug

Fatal Exception: java.lang.IllegalStateException
Recording currently in progress - missing #endRecording() call?

After updating to version 2.10.0, an issue is posted in Firebase Crashlytics.

### Reproduction steps

Fatal Exception: java.lang.IllegalStateException
Recording currently in progress - missing #endRecording() call?
android.graphics.RenderNode.beginRecording (RenderNode.java:446)
android.graphics.RenderNode.beginRecording (RenderNode.java:465)
androidx.compose.ui.graphics.layer.GraphicsLayerV29.record (GraphicsLayerV29.android.kt:225)
androidx.compose.ui.graphics.layer.GraphicsLayer.recordInternal (AndroidGraphicsLayer.android.kt:432)
androidx.compose.ui.graphics.layer.GraphicsLayer.record-mL-hObY (AndroidGraphicsLayer.android.kt:425)
androidx.compose.ui.platform.GraphicsLayerOwnerLayer.updateDisplayList (GraphicsLayerOwnerLayer.android.kt:237)
androidx.compose.ui.platform.AndroidComposeView.dispatchDraw (AndroidComposeView.android.kt:1544)
android.view.View.draw (View.java:25180)
android.view.View.updateDisplayListIfDirty (View.java:24036)
android.view.View.draw (View.java:24907)
android.view.ViewGroup.drawChild (ViewGroup.java:4780)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4538)
android.view.View.updateDisplayListIfDirty (View.java:24022)
android.view.View.draw (View.java:24907)
android.view.ViewGroup.drawChild (ViewGroup.java:4780)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4538)
androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw (ConstraintLayout.java:1994)
android.view.View.updateDisplayListIfDirty (View.java:24022)
android.view.View.draw (View.java:24907)
android.view.ViewGroup.drawChild (ViewGroup.java:4780)
androidx.fragment.app.FragmentContainerView.drawChild (FragmentContainerView.kt:240)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4538)
androidx.fragment.app.FragmentContainerView.dispatchDraw (FragmentContainerView.kt:230)

### Affected SDK versions

2.10.0

### Latest working SDK version

2.10.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

**Comment by mariusc83** [comment]
Hi @leedawonswing , thank you for taking the time to report it. We will have a look on our end but in the meantime can you please give us more information :

1. Are you using the Datadog Session Replay feature ?
2. How often this happens ?
3. Can you reproduce the issue on your end ? In that case can you try to reproduce it with and without session replay feature and tell us the outcome ? Any particular (custom layout) you are using in your application ?
4. Any other extra detail that could help us reproducing the issue on our end will be great.

Thanks !!

**Comment by Im-Tae** [comment]
1. yes, we are using the Datadog Session Replay, Rum, Trace.
2. It happened after uploaded the version. 2.2.0 -> 2.10.0.
3. It's not being reproduced, so I'll check it out and let you know later

**Comment by mariusc83** [comment]
Hello @Im-Tae any news on this issue ?

**Comment by Im-Tae** [comment]
Yes, there are no issues now.
This was an issue that occurred in the compose version that was uploaded together with the datadog version. It has now been resolved.

**Comment by childofthehorn** [comment]
> Yes, there are no issues now.
> This was an issue that occurred in the compose version that was uploaded together with the datadog version. It has now been resolved.

Can you state what Compose version seems to have had the issue?  I'm wondering if I am hitting something similar (and why we haven't had a Compose BOM update for July or August).
