### ISSUE TITLE
Troubleshooting link in README.md is broken

### ISSUE THREAD

**Issue by mateo-villa** [DataDog/dd-sdk-android#2163]
Currently, the troubleshooting link redirects to the following page:

https://docs.datadoghq.com/real_user_monitoring/android/troubleshooting/

This page does not exist and displays a 404 error. I believe this link should now redirect to this troubleshooting documentation page:

https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/android/

Updating this link would allow for easier access to troubleshooting steps for the Android SDK.

**Comment by mariusc83** [comment]
Hi @mateo-villa, thank you for taking the time to report it. Indeed that link is broken and we're going to fix it ASAP.
