### ISSUE TITLE
Hard casting to AdvancedNetworkRumMonitor causes crashes

### ISSUE THREAD

**Issue by ethan1406** [DataDog/dd-sdk-android#2183]
### Stack trace

```
 java.lang.ClassCastException: com.datadog.android.rum.NoOpRumMonitor cannot be cast to com.datadog.android.rum.internal.monitor.AdvancedNetworkRumMonitor
at com.datadog.android.okhttp.DatadogInterceptor.intercept(DatadogInterceptor.kt:250)

```

### Reproduction steps

Construct a DatadogInterceptor without setting Rum with `Rum.enabled()`

### Volume

100%

### Affected SDK versions

2.12.0

### Latest working SDK version

2.11.0

### Does the crash manifest in the latest SDK version?

Yes

### Kotlin / Java version

kotlin 1.9.24

### Gradle / AGP version

agp 8.5.2

### Other relevant information

it's crashing at https://github.com/DataDog/dd-sdk-android/blob/27f8ab9c766d0edc4d24862d36a9868d54fcbd0e/integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt#L250. 

The hard cast should be `as?`. This seems unintentional as soft casts were used elsewhere in the same pr: https://github.com/DataDog/dd-sdk-android/commit/3ba2e49ff3064b2771c71a6674273165d503d76b

**Comment by 0xnm** [comment]
Hello @ethan1406! 

Thanks for reporting it. Indeed it was a bug from our side, which is now fixed in the release `2.12.1`. Can you please try it out?
