### ISSUE TITLE
TImber Tags are Ignored

### ISSUE THREAD

**Issue by igorwojda** [DataDog/dd-sdk-android#2195]
### Describe the bug

The `tag` parameters is ignored inside `DatadogTree.log` merthod

### Reproduction steps

```kotlin
Timber
	.tag("tag")
	.w("message")
```

### Logcat logs

message

### Expected behavior

tag message

### Affected SDK versions

2.12.1

### Latest working SDK version

No

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Kotlin / Java version

Kotlin

### Other relevant information

Bug line https://github.com/DataDog/dd-sdk-android/blob/2529684896c167117a3c0e230f51fdcb43059ea2/integrations/dd-sdk-android-timber/src/main/kotlin/com/datadog/android/timber/DatadogTree.kt#L51 - notice lack of `tag` argument

**Comment by 0xnm** [comment]
Hello @igorwojda!

We are aware of this issue and it is in our backlog, but not with very high priority. Is this issue critical for you?

With the current logging API we can only attach attributes to the individual log events, so the only workaround which comes to my mind is adding attribute with the key something like `timber_tag` and value to be the tag passed with a Timber call.

**Comment by igorwojda** [comment]
This is a single line fix. I cam happy to open PR.
I guess I just need a ticket number

**Comment by 0xnm** [comment]
Hello @igorwojda!

We now support logging tags as well, check more details in the linked PR. This feature will be available in the next SDK release.
