### ISSUE TITLE
How can i populate DATADOG_INSTANCE_NAME in UploadWorker.kt?

### ISSUE THREAD

**Issue by ZivStep** [DataDog/dd-sdk-android#2252]
### Question

When using datadog in a library, i initilize it with an instance name but the name does not get populated into `DATADOG_INSTANCE_NAME` in the `UploadWorker.kt`, this results in an exception thrown inside the worker:

```
SDK instance with name _dd.sdk_core.default is not found, returning no-op implementation. 
Please make sure to call Datadog.initialize([instanceName]) before getting the instance.
SDK instance was requested from: (Ask Gemini)

at com.datadog.android.Datadog.getInstance(Datadog.kt:139)
at com.datadog.android.core.internal.data.upload.UploadWorker.doWork(UploadWorker.kt:42)
at androidx.work.Worker$1.run(Worker.java:82)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
2024-09-09 11:32:40.574 19812-20100 Datadog 
co.onestep.android.demoapp
E  Datadog has not been initialized.
```

Since those lines
```
 val instanceName = inputData.getString(DATADOG_INSTANCE_NAME)
 val sdkCore = Datadog.getInstance(instanceName) as? InternalSdkCore
```

return a null instance name and the call to Datadog.getInstance(instanceName/*this is always null/*) throws an exception

**Comment by ZivStep** [comment]
I call Datadog.initialize() in an SDK i am developing, my SDK initilization proccess is recommended but not guaranteed to be called in the application's onCreate.

This is how i initilize datadog in my SDK

```
internal fun initDataDog(
    context: Context,
): SdkCore {
    
    val configuration = Configuration.Builder(
        clientToken = BuildConfig.DATA_DOG_CLIENT_TOKEN,
        env = BuildConfig.BUILD_TYPE,
        service = BuildConfig.LIBRARY_PACKAGE_NAME,
    ).build()
    
    Datadog.initialize(BuildConfig.LIBRARY_PACKAGE_NAME, context, configuration, TrackingConsent.GRANTED)
    Datadog.setVerbosity(if (BuildConfig.DEBUG) Log.VERBOSE else Log.ASSERT)

    with(Datadog.getInstance(BuildConfig.LIBRARY_PACKAGE_NAME)) {
        // Log collection
        setupLogCollection(this)

        // Tracing
        setupTracing(this)

        // Realtime user monitoring
        setupRUM(this)
    }

    return Datadog.getInstance(BuildConfig.LIBRARY_PACKAGE_NAME)
}
```

As you can see i am initilizing it with an instance name, to avoid any conflicts with any datadog instances that may be in use by my hosting app.

This all works fine, however, the code for `doWork` in [`UploadWorker.kt`, line 42](https://github.com/DataDog/dd-sdk-android/blob/908b45a10786dc215db7e8627e9b2c8c3f34ec6d/dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadWorker.kt#L42),  is calling `Datadog.getInstance()` without my instance name, the instance name is taken from `DATADOG_INSTANCE_NAME`, but it is internal and i cannot populate it.

This results in the error above.

**Comment by ambushwork** [comment]
Hi @ZivStep,

Thank you for sharing your code! We've identified an issue with the `UploadWorker` and are currently working on a fix.
In the meantime, the data collected by the SDK can still be uploaded while the app is in use, the error you’re seeing is just a warning.
