### ISSUE TITLE
`-debug` releases mess with Dependabot

### ISSUE THREAD

**Issue by lwasyl** [DataDog/dd-sdk-android#2255]
### Feature description

Dependabot is confused and doesn't understand semver, suggesting to update to any version with `-suffix`:
![image](https://github.com/user-attachments/assets/3ff1eb48-cc94-40f9-a553-89e974305c40)

https://github.com/dependabot/dependabot-core/issues/7775

Unfortunately, this means Datadog `-debug` releases are always suggested as a version bump	

### Proposed solution

I don't have a good solution, but seeing as the issue is ignored on the Dependabot side, it'd be nice if DD published the debug artifact in a way that doesn't trigger this Dependabot bug

**Comment by ambushwork** [comment]
Hello @lwasyl,

It appears that there is an issue with Dependabot not respecting the [version ordering](https://docs.gradle.org/current/userguide/single_versions.html#version_ordering). The versions without a suffix should be always considered higher than those with a suffix. Given this, we will not be publishing a debug version to address the problem in the third-party tool.

Thank you for your understanding.
