### ISSUE TITLE
Building the master branch [156212a] fails with Could not find com.github.drieks.antlr-kotlin:antlr-kotlin-runtime:d4384e4d90.

### ISSUE THREAD

**Issue by brunck** [DataDog/dd-sdk-android#2263]
### Describe the bug

Trying to build the `master` branch at commit `156212a` fails with this message:

```
The supplied phased action failed with an exception.
Execution failed for task ':buildSrc:compileKotlin'.
Could not resolve all files for configuration ':buildSrc:compileClasspath'.
Could not find com.github.drieks.antlr-kotlin:antlr-kotlin-runtime:d4384e4d90.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/github/drieks/antlr-kotlin/antlr-kotlin-runtime/d4384e4d90/antlr-kotlin-runtime-d4384e4d90.pom
  - https://dl.google.com/dl/android/maven2/com/github/drieks/antlr-kotlin/antlr-kotlin-runtime/d4384e4d90/antlr-kotlin-runtime-d4384e4d90.pom
  - https://plugins.gradle.org/m2/com/github/drieks/antlr-kotlin/antlr-kotlin-runtime/d4384e4d90/antlr-kotlin-runtime-d4384e4d90.pom
  - https://maven.google.com/com/github/drieks/antlr-kotlin/antlr-kotlin-runtime/d4384e4d90/antlr-kotlin-runtime-d4384e4d90.pom
  - https://jitpack.io/com/github/drieks/antlr-kotlin/antlr-kotlin-runtime/d4384e4d90/antlr-kotlin-runtime-d4384e4d90.pom
Required by:
    project :buildSrc > com.github.kotlinx.ast:grammar-kotlin-parser-antlr-kotlin-jvm:0.1.0 > com.github.kotlinx.ast:parser-antlr-kotlin:0.1.0 > com.github.kotlinx.ast:parser-antlr-kotlin-jvm:0.1.0
```

### Reproduction steps

This can be seen easily by just running `./local_ci.sh --compile`.

### Logcat logs

See above

### Expected behavior

The build succeeds.

### Affected SDK versions

-

### Latest working SDK version

-

### Did you confirm if the latest SDK version fixes the bug?

No

**Comment by xgouchet** [comment]
Hello @brunck , and thanks for opening this ticket. 

This is a known issue, some of our dependencies come from Jitpack which seems to have lost this specific version. We fixed this issue on our `develop` branch already (see #2261). You can achieve the same effect by explicitly adding `com.github.drieks.antlr-kotlin:antlr-kotlin-runtime:v0.1.0` in your dependencies. 

The `master` branch will eventually get this fix too when we release a new version of our SDK.
