### ISSUE TITLE
Okhttp with DatadogInterceptor is blocking SSE streams

### ISSUE THREAD

**Issue by prashantwosti-prezzee** [DataDog/dd-sdk-android#2266]
### Describe the bug

Hi 

The app I'm working on has a DatadogInterceptor and it's working normally until I implemented the Server-Sent Events.
Even though the streams are coming in between certain interval, app receives all the streams at once.

But when I remove the `DatadogInterceptor`, the app receives the streams normally.

Need your help to fix it.

### Reproduction steps

Add datadog interceptor to okhttpclient:
```
List<String> tracedHosts = List.of(BuildConfig.BFF_BASE_URL);
okHttpClientBuilder.addInterceptor(new DatadogInterceptor.Builder(tracedHosts).build())
```
okHttpClientBuilder is passed to create httpclient engine.

Create an SSE endpoint that sends data
```
    sse(OrderStatusResource.PATH) {

        val sseFlow = flow {
            statuses.forEach {
                println(it)
                emit(SseEvent(data = it))
                delay(5.seconds)
            }
        }.shareIn(GlobalScope, SharingStarted.WhileSubscribed(5_000))

        sseFlow.collect {
            val json = Json { encodeDefaults = true }
            val data = json.encodeToString(it)
            send(ServerSentEvent(data = data))
        }
    }
```

now consume the data on the client
```
        httpClient.sse(host = "192.168.251.226", port = 8080, path = OrderStatusResource.PATH) {
            incoming.collect { event ->
                println("SSE::>> $event")
                _flow.emit(OrderStatusDto(data = event.data.toString()))
                if (event.data.equals("Done")) {
                    httpClient.close()
                }
            }
        }
```

you will get all the payload at once when the connection closes.

but when i comment the `DatadogInterceptor`, everything works normally.

### Expected behavior

App should receive SSE events normally

### Affected SDK versions

datadog-android 2.13.1

### Latest working SDK version

n/a

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Kotlin / Java version

kotlin 2.0.0

### Gradle / AGP version

agp 8.6.0-rc1

### Other dependencies versions

com.squareup.okhttp3 = "4.12.0"
io.ktor:ktor-client-okhttp = "3.0.0-rc-1"

**Comment by 0xnm** [comment]
Hello @prashantwosti-prezzee! Thanks for opening this issue.

Can you please elaborate your statement about events received. What do you mean by the following:

> you will get all the payload at once when the connection closes

Do you receive them only when connection closes and not one by one with interval of 5 seconds?

**Comment by prashantwosti-prezzee** [comment]
> Do you receive them only when connection closes and not one by one with interval of 5 seconds?
@0xnm yes, correct. only after connection is closed or timed-out.
