### ISSUE TITLE
SDK to Maui

### ISSUE THREAD

**Issue by jfobaltazar** [DataDog/dd-sdk-android#2303]
### Question

Hello, Do you have any idea when you will release RUM support for Maui?

**Comment by xgouchet** [comment]
Hi @jfobaltazar and thanks for opening this question.

We do not have any plan to add support directly to Maui for now. We know some customers embedded the Android / iOS native SDKs in their Xamarin/Maui applications, following Microsoft's [Native Embedding](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/native-embedding?view=net-maui-8.0) documentation, but we didn't experimented directly on it ourselves.
