### ISSUE TITLE
com.datadog.android.rum.internal.anr.ANRException: Application Not Responding

### ISSUE THREAD

**Issue by manju1375** [DataDog/dd-sdk-android#2316]
### Describe the bug

Seeing the ANR exception within com.datadog.android.rum.internal.anr.ANRException package.
Not sure what is the exact reason behind this exception. Checked session and Stack trace No luck. Nt able to reproduce as well.
Its happening on opening of one of bottom sheet fragment. None of the Datadog related calls/events were present within the class.
Please resolve ASAP.

brand Google
model Pixel 6 Pro
name Google Pixel 6 Pro

Android : 12 
 ext.dd_android_rum_version = "2.5.1"
 ext.dd_android_webview_version = "2.5.1"
 ext.dd_android_logs_version = "2.5.1"
 ext.dd_android_trace_version = "2.5.1"
 ext.dd_android_session_replay_version = "2.5.1"
ext.dd_android_okhttp_version = "2.7.1"

com.datadog.android.rum.internal.anr.ANRException: Application Not Responding
native: #00 pc 000000000004c25c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
native: #01 pc 0000000000051068  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+144)
native: #02 pc 00000000000b126c  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+80)
native: #03 pc 00000000000564e0  /system/lib64/libc++.so (std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)+20)
native: #04 pc 0000000000058efc  /system/lib64/libc++.so (std::__1::__assoc_sub_state::copy()+84)
native: #05 pc 00000000000591cc  /system/lib64/libc++.so (std::__1::future<void>::get()+24)
native: #06 pc 0000000000476694  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderProxy::setStopped(bool)+224)
at
android.graphics.HardwareRenderer.nSetStopped
Native method
at
android.graphics.HardwareRenderer.setStopped
HardwareRenderer.java:498
at
android.view.ViewRootImpl.performDraw
ViewRootImpl.java:4279
at
android.view.ViewRootImpl.performTraversals
ViewRootImpl.java:3374
at
android.view.ViewRootImpl.doTraversal
ViewRootImpl.java:2179
at
android.view.ViewRootImpl$TraversalRunnable.run
ViewRootImpl.java:8787
at
android.view.Choreographer$CallbackRecord.run
Choreographer.java:1037
at
android.view.Choreographer.doCallbacks
Choreographer.java:845
at
android.view.Choreographer.doFrame
Choreographer.java:780
at
android.view.Choreographer$FrameDisplayEventReceiver.run
Choreographer.java:1022
at
android.os.Handler.handleCallback
Handler.java:938
at
android.os.Handler.dispatchMessage
Handler.java:99
at
android.os.Looper.loopOnce
Looper.java:201
at
android.os.Looper.loop
Looper.java:288
at
android.app.ActivityThread.main
ActivityThread.java:7870
at
java.lang.reflect.Method.invoke
Native method
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
RuntimeInit.java:548
at
com.android.internal.os.ZygoteInit.main

### Reproduction steps

Seeing the ANR exception within com.datadog.android.rum.internal.anr.ANRException package.
Not sure what is the exact reason behind this exception. Checked session and Stack trace No luck. Nt able to reproduce as well.
Its happening on opening of one of bottom sheet fragment. None of the Datadog related calls/events were present within the class.
Please resolve ASAP.

### Logcat logs

com.datadog.android.rum.internal.anr.ANRException: Application Not Responding
native: #00 pc 000000000004c25c /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
native: https://github.com/DataDog/dd-sdk-android/pull/1 pc 0000000000051068 /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+144)
native: https://github.com/DataDog/dd-sdk-android/pull/2 pc 00000000000b126c /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+80)
native: https://github.com/DataDog/dd-sdk-android/pull/3 pc 00000000000564e0 /system/lib64/libc++.so (std::__1::condition_variable::wait(std::__1::unique_lockstd::__1::mutex&)+20)
native: https://github.com/DataDog/dd-sdk-android/pull/4 pc 0000000000058efc /system/lib64/libc++.so (std::__1::__assoc_sub_state::copy()+84)
native: https://github.com/DataDog/dd-sdk-android/pull/5 pc 00000000000591cc /system/lib64/libc++.so (std::__1::future::get()+24)
native: https://github.com/DataDog/dd-sdk-android/pull/6 pc 0000000000476694 /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderProxy::setStopped(bool)+224)
at
android.graphics.HardwareRenderer.nSetStopped
Native method
at
android.graphics.HardwareRenderer.setStopped
HardwareRenderer.java:498
at
android.view.ViewRootImpl.performDraw
ViewRootImpl.java:4279
at
android.view.ViewRootImpl.performTraversals
ViewRootImpl.java:3374
at
android.view.ViewRootImpl.doTraversal
ViewRootImpl.java:2179
at
android.view.ViewRootImpl$TraversalRunnable.run
ViewRootImpl.java:8787
at
android.view.Choreographer$CallbackRecord.run
Choreographer.java:1037
at
android.view.Choreographer.doCallbacks
Choreographer.java:845
at
android.view.Choreographer.doFrame
Choreographer.java:780
at
android.view.Choreographer$FrameDisplayEventReceiver.run
Choreographer.java:1022
at
android.os.Handler.handleCallback
Handler.java:938
at
android.os.Handler.dispatchMessage
Handler.java:99
at
android.os.Looper.loopOnce
Looper.java:201
at
android.os.Looper.loop
Looper.java:288
at
android.app.ActivityThread.main
ActivityThread.java:7870
at
java.lang.reflect.Method.invoke
Native method
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
RuntimeInit.java:548
at
com.android.internal.os.ZygoteInit.main

### Affected SDK versions

2.5.1

### Latest working SDK version

2.14.0

### Did you confirm if the latest SDK version fixes the bug?

No

### Kotlin / Java version

1.8.0

### Gradle / AGP version

8.5.0

### Device Information

brand Google
model Pixel 6 Pro
name Google Pixel 6 Pro

**Comment by manju1375** [comment]
Not sure if it is not going to happen on 2.14.0. This came has a crash within Errortracking on the app version when Datadog sdk targets to 2.5.1

**Comment by xgouchet** [comment]
Hi @manju1375 , 
This exception is sent when we detect that the end user received an ANR (Application Not Responding) Popup. The stack trace attached is a snapshot of the main thread at the moment we do detect it, which doesn't always reflect what was the cause of the ANR. 
Unfortunately, as we don't have access to the OS internals, we can't provide more precise insights appart from what you already get.
