### ISSUE TITLE
Empty page in Android webView session replay

### ISSUE THREAD

**Issue by BaHungSkedulo** [DataDog/dd-sdk-android#2355]
### Question

Hello DataDog Team, 

The current webView session replay shows only an empty page with no user interactions. How can I make it function like in native mobile?
![Image](https://github.com/user-attachments/assets/26522b7e-2c45-4b00-94c7-03cf8fd9b62c)

**Comment by jonathanmos** [comment]
hi @BaHungSkedulo, have you followed the steps in [this guide](https://docs.datadoghq.com/real_user_monitoring/session_replay/mobile/setup_and_configuration/?tab=android#web-view-instrumentation) for instrumenting the webview? Does this issue occur with the latest sdk version?

**Comment by BaHungSkedulo** [comment]
I haven't implemented the instrument for the webview yet; let me try and provide feedback as soon as possible.

**Comment by BaHungSkedulo** [comment]
Hi @jonathanmos after trying to follow your guide, I still faced the same issue: nothing changed, and the page remains empty, I believe my situation might be different. We load source data, save it in a local HTML file, and then display it in a webView, I'm using version 2.14.0, Do you think it still captures the content of the webview in this scenario?

**Comment by jonathanmos** [comment]
hi @BaHungSkedulo, webviews can only be captured if the web app that is being accessed in the webview is also instrumented with the browser sdk. Is this the case here?

**Comment by BaHungSkedulo** [comment]
hi @jonathanmos sorry, I don't fully understand your question. We use WebView to display content. I have reviewed the example data for Dog and verified the code in the WebViewRecordFragment class, as we have already established it. The key difference is that we display a locally stored HTML file. As far as I know, session replay cannot capture content from the webview since it's stored locally, right?

**Comment by jonathanmos** [comment]
One of the requirements to capture the webview is that the content of the webview must be instrumented with the [browser sdk](https://docs.datadoghq.com/real_user_monitoring/session_replay/browser/#setup) - in other words that the browser sdk is running inside the view at the time that you are recording it with session replay. This may be possible with a local html file if you can reference the js content.

**Comment by BaHungSkedulo** [comment]
Thank you for taking the time and effort to address my concerns, I genuinely appreciate it.

**Comment by jhj5897** [comment]
@jonathanmos
Hello. I have a same issue. I’m not sure if I understood correctly, but are you saying that for the WebView to be displayed correctly in SessionReplay, the webpage needs to be using the Browser SDK?

**Comment by 0xnm** [comment]
Hello @BaHungSkedulo! I believe that your question was answered, so I'm closing this issue. Don't hesitate to re-open it if needed.
