### ISSUE TITLE
Does DatadogInterceptor() for OkHttp need to be added as a normal interceptor, as a network interceptor, or both?

### ISSUE THREAD

**Issue by StylianosGakis** [DataDog/dd-sdk-android#2425]
### Question

There seems to be a note here https://github.com/DataDog/dd-sdk-android/blob/ba86ac8e54608c0d8fecdfbea9ad0264150bd2a3/integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt#L57-L58 which suggests to use a TraceInterceptor as a networkInterceptor, but this is not mentioned in the docs https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android/?tab=kotlin#automatically-track-network-requests as far as I can tell.

It would be nice for the docs to contain some more complete information on what the options are that we have so that we can make a more informed decision around this.

**Comment by ambushwork** [comment]
Hi @StylianosGakis,

Thank you for your question! `DatadogInterceptor` is designed to be used as a standard interceptor. If you need a network interceptor, you can use `TracingInterceptor`. Also the choice between an interceptor and a network interceptor depends on what you want to observe, as they intercept requests at different levels in OKHttp.

And We'll continue improving our documentation to make this distinction clearer.

**Comment by StylianosGakis** [comment]
> Also the choice between an interceptor and a network interceptor depends on what you want to observe

Yes exactly, it would be really nice for the docs to describe what exactly those differences will be if one decides to log both. And for the logs to include something about this, because as it stands it looks to only be a comment in the code documentation itself.

**Comment by 0xnm** [comment]
Thanks for the suggestion @StylianosGakis! We created a ticket internally to do the documentation update to make things more clear.
