### ISSUE TITLE
Is there a way to exclude some specific errors from being reported as RUM errors from the OkHttp DatadogInterceptor?

### ISSUE THREAD

**Issue by StylianosGakis** [DataDog/dd-sdk-android#2426]
### Question

Using the built-in datadog interceptor on our OkHttp instance, we get errors reported for IOExceptions that are originating from the request just being cancelled. This in our app happens basically any time some request may have started, but then the user navigates away from the screen, so we cancel the screen's CoroutineScope, which in turn can cancel some ongoing network requests.
These errors then get reported o RUM, where we see the exception starting with "java.io.IOException: Canceled...".
This messes up with our SLOs tracking due to those request being marked as errors, while they are just typical App behavior and there is nothing concerning about them.

I wonder two things here
a) Do you think this should not be happening and that we got something setup wrong?
b) If it works as intended, is there a way for us to exclude those errors from being reported as such in RUM?

**Comment by ambushwork** [comment]
Hi @StylianosGakis,

Thank you for your feedback! If I understand your requirement correctly, you can try using setEventMapper in the RumConfiguration to filter out unnecessary errors. We'll continue working on this to explore potential ways to make this functionality more convenient in the DatadogInterceptor.

**Comment by 0xnm** [comment]
Hi @StylianosGakis! Yes, RUM and Logs mappers are created to modify/filter out low-level events to the sent to Datadog, so this is a valid use case and your snippet is correct: by returning `null` event will be dropped and not sent to Datadog.

I'm closing this issue since it is solved, but don't hesitate to re-open it if needed.
