### ISSUE TITLE
Using GlobalTracer with AndroidTracer is not supported.

### ISSUE THREAD

**Issue by jhj5897** [DataDog/dd-sdk-android#2437]
### Question

I’m trying to integrate Datadog into my project, but I noticed it’s not working as expected after following the official documentation.

The documentation, which can be found here:(https://docs.datadoghq.com/ko/tracing/trace_collection/automatic_instrumentation/dd_libraries/android/?tab=kotlin#rxjava--retrofit), mentions creating a new AndroidTracer instance and passing it to the GlobalTracer.registerIfAbsent function as a parameter.

However, the registerIfAbsent function expects a Tracer type, not a DDTracer, which AndroidTracer inherits from.

![Image](https://github.com/user-attachments/assets/7c14e1f9-2eaf-4ff2-8175-c5a89ae662c9)
![Image](https://github.com/user-attachments/assets/284540f9-a7c4-4b4b-bf84-420875abb2e0)

Could you clarify the correct way to use GlobalTracer in an Android project?

**Comment by mariusc83** [comment]
Hi @jhj5897,

You are not using the right `GlobalTracer`, you are using our internal one. We are going to fix this by renaming it in a next version just to avoid the confusion. Please make sure you are using the `opentracing.util.GlobalTracer` there.

**Comment by jhj5897** [comment]
@mariusc83 
Thank you so much! I believe I was using the Datadog library correctly, and it’s working now. I truly appreciate your help!
