### ISSUE TITLE
AndroidX Fragment dependency missing from `dd-sdk-android-rum`

### ISSUE THREAD

**Issue by yogurtearl** [DataDog/dd-sdk-android#2440]
### Describe the bug

`com.datadoghq:dd-sdk-android-rum:2.16.0` contains `com.datadog.android.rum.tracking.FragmentViewTrackingStrategy`

This class imports `androidx.fragment.app.Fragment` 

but the metadata files do not declare a dependency on `androidx.fragment:fragment` 

https://repo1.maven.org/maven2/com/datadoghq/dd-sdk-android-rum/2.16.0/dd-sdk-android-rum-2.16.0.pom
https://repo1.maven.org/maven2/com/datadoghq/dd-sdk-android-rum/2.16.0/dd-sdk-android-rum-2.16.0.module

This causes Kotlin 2.1.0 to fail to compile with an error 

```
e: file:///home/runner/work/android/android/core/datadog/setup/src/main/kotlin/com/mycorp/android/core/datadog/DatadogSetup.kt:69:17 Cannot access class 'androidx.fragment.app.Fragment'. Check your module classpath for missing or conflicting dependencies.
```

Kotlin 2.0.1 worked fine even though this dependency is missing.

### Reproduction steps

Compile with Kotlin 2.1.0 and try to setup DataDog rum without explicitly added AndroidX Fragment. 

### Affected SDK versions

2.16.0

### Latest working SDK version

none

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Kotlin / Java version

2.1.0

### Gradle / AGP version

8.11.1/8.7.3

**Comment by xgouchet** [comment]
Hi @yogurtearl , and thanks for oppening this ticket

indeed it's not a dependency directly mentioned in our SDK, but it is a transitive dependency via the `androidx.navigation:navigation-fragment` library, so it should be included in your build. 

Could you give us what your dependency graph looks like in your project, using the `./gradelw :app:dependencies` command, please?

**Comment by yogurtearl** [comment]
It is a large project with 100s of modules, not really practical to give the full dep hierarchy here. 

The DD rum code directly imports `androidx.fragment.app.Fragment` so it should have a direct dep on `androidx.fragment:fragment` and not rely on the transitive dep. 

Kotlin `2.1.0` seems to have issues with deps that don't correctly declare direct deps for things they use directly. 

https://github.com/DataDog/dd-sdk-android/blob/d737ab46f3416547c945575b381e0b8c88bbe790/features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategy.kt#L13-L14
