### ISSUE TITLE
How can I configure HTTP client error statuses for Datadog Trace on Android like in the Java library?

### ISSUE THREAD

**Issue by ducnv3012** [DataDog/dd-sdk-android#2441]
### Question

I am trying to configure the HTTP client error statuses for Datadog Trace on Android, similar to how it's done in the Java library using the environment variable `DD_HTTP_CLIENT_ERROR_STATUSES` (e.g., 400-403,405,410-499). By default, the Java library reports 4xx errors as client errors for tracing, but I am unable to achieve the same behavior in the Android SDK.

I need to configure this because I have custom HTTP status codes that need to be considered as errors for tracing, and the default 4xx range doesn't cover them.

I have tried the following approaches, but none of them have worked:

1. Using `setAdditionalConfiguration` and `setEventMapper` in the `Configuration`.
2. Implementing the `tracedRequestListener` interface within `DatadogInterceptor`.

Could you please provide guidance on how to configure HTTP client error statuses for the Datadog Trace feature on Android?

Thank you!

**Comment by 0xnm** [comment]
Hello @ducnv3012!

It is not possible to achieve what you want with the current version of Android SDK. I've opened an internal ticket to add such functionality.

How critical is it for you?

**Comment by ducnv3012** [comment]
@0xnm 
Thank you for your response and for opening an internal ticket to address this functionality.

This feature is not critical for me at the moment. However, having it would make it easier to customize and manage request status codes effectively.

I appreciate your support and look forward to any updates regarding this functionality.

Thank you!
