### ISSUE TITLE
Is there a way to use the functionality of DatadogInterceptor with URLConnection?

### ISSUE THREAD

**Issue by jhj5897** [DataDog/dd-sdk-android#2449]
### Question

Hello, I want to record sessions with network activities in my Android application.
However, in some cases, the application still uses URLConnection instead of OkHttp.
I tried to find an alternative way to achieve the functionality of DatadogInterceptor, but it didn’t work. (Using trace and span was similar, but it wasn’t what I wanted.)
Is there any way to use DatadogInterceptor with URLConnection? Or would it be better to refactor the legacy code to use OkHttp?

**Comment by 0xnm** [comment]
Hello @jhj5897!

We don't support `URLConnection` instrumentation in our SDK, so it would be better to refactor legacy code to use OkHttp instead.

Does it answer your question?

**Comment by jhj5897** [comment]
@0xnm I was wondering if there was another way, but apparently there isn't. 🥲 Thanks for your reply.
