### ISSUE TITLE
Support for minSdkVersion 17?

### ISSUE THREAD

**Issue by ehrlichja** [DataDog/dd-sdk-android#298]
I need to be able to support older devices with sdk version 17. Is it a nonstarter, or is it worth trying? 

Using `implementation "com.datadoghq:dd-sdk-android:1.3.1"`

```Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 19 declared in library [com.datadoghq:dd-sdk-android:1.3.1] /Users/andrewehrlich/.gradle/caches/transforms-2/files-2.1/df5cca87da66308c0adc675b89ba1aa8/jetified-dd-sdk-android-1.3.1/AndroidManifest.xml as the library might be using APIs not available in 17
	Suggestion: use a compatible library with a minSdk of at most 17,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.datadog.android" to force usage (may lead to runtime failures)
```

**Comment by xgouchet** [comment]
Hi @ehrlichja, our target compatibility was set to API 19 (released 7 years ago, and compatible with more than 98% of all the devices out there).

After a really quick test, it appears that indeed using the library as is will indeed crash on a device running Android 17. We'll check if lowering our SDK compatibility is possible, and we'll get back to you.

**Comment by ehrlichja** [comment]
Fingers crossed

**Comment by xgouchet** [comment]
Hi @ehrlichja , I'm really sorry, but unfortunately, we don't have the resources and time to support such an old version of Android for our SDK right now, and so we won't be lowering our support to version 17.
But since all our code is open sourced, you can make your own fork to add the support to old versions of Android.

**Comment by ehrlichja** [comment]
Thanks for checking! Do you forsee any problems with using `<uses-sdk tools:overrideLibrary="com.datadog.android"/>`? I ran it and didn't get any runtime errors, but also didn't see any log messages in datadog.

**Comment by xgouchet** [comment]
When I tried doing that, I got a couple of crashes, so I wouldn't advise on doing that blindly in your application. The safest way would be to fork the project and compile it with `minSdk=17` and make sure the Android Lint detect all potential issues. 

Also try using the `Datadog.setVerbosity()` method to get information about any potential issue in the logcat.
