### ISSUE TITLE
Can't force the tag "source" value

### ISSUE THREAD

**Issue by fleficher** [DataDog/dd-sdk-android#300]
**Describe what happened**
Calling `addTag("source", "android")` on the Datadog logger doesn't override the default value used by the SDK.

On the iOS SDK, the default value is "ios" but on Android it's just "mobile".
It would be more appropriate to set it to "android" or to allow to override this value from the `DatadogConfig` or from the ` Logger.Builder` 

**Steps to reproduce the issue:**

Call `addTag("source", "android")` on a Datadog logger instance.

**Describe what you expected:**
The `source` tag can be overridden.

**Additional context**
 - Datadog SDK version: 1.4.1

**Comment by xgouchet** [comment]
Hi @fleficher 
This value is indeed reserved in the SDK, so this behavior works as intended. The `source` value has been changed to be `source:android` in version `1.5.0`. That version is still in beta for now, mostly for new features which are still in development, but if you only use the logger, you can move to the latest version (`1.5.0-beta1`)

**Comment by fleficher** [comment]
Hi @xgouchet thanks a lot, it's working as expected with the `1.5.0-beta1` 👍
