### ISSUE TITLE
Support custom EventListener in DatadogEventListener.Factory

### ISSUE THREAD

**Issue by neworld** [DataDog/dd-sdk-android#365]
**Is your feature request related to a problem? Please describe.**
Currently, I have custom `EventListener` which tracks some important stuff, but OkHttp supports only one. So I am needed to choose to use Datadog's or custom.

**Describe the solution you'd like**

A one way to solve problem is by using delegates:

```
internal constructor(val delegate: EventListener, val key: String) : EventListener() by delegate {

    class Factory(delegate: EventListener = NoOpEventListener) : EventListener.Factory {
        override fun create(call: Call): EventListener {
            val key = identifyRequest(call.request())
            return DatadogEventListener(delegate, key)
        }
    }
}
```

**Describe alternatives you've considered**

The alternative is to implement delegate support in the custom EventListener. However, I believe many other projects have some custom EventListener already, so maybe it is a good decision to support delegates in the library.

**Comment by xgouchet** [comment]
Hi @neworld , and thanks a lot for the feature request. 

Indeed this is not something we considered, but is definitely something we need to do. We added that to our roadmap and we'll try to deliver it in a timely manner.

If you want to, you can submit a Pull Request (if you do, make sure to read our [Contributing guidelines](../blob/master/CONTRIBUTING.md)).

**Comment by xgouchet** [comment]
As you said in the PR, it's indeed safer to do it the other way 'round and let your Listener call ours. 

You can do this easily like so: 

```kotlin
class CustomEventListener(
    private val delegate: EventListener
) : EventListener() {

    override fun connectStart(call: Call, inetSocketAddress: InetSocketAddress, proxy: Proxy) {
        super.connectStart(call, inetSocketAddress, proxy)
        delegate.connectStart(call, inetSocketAddress, proxy)
    }
    
    // …

    class Factory : EventListener.Factory {
        private val datadogFactory = DatadogEventListener.Factory()

        override fun create(call: Call): EventListener {
            val delegate = datadogFactory.create(call)

            return CustomEventListener(delegate)
        }
    }
}
```
