### ISSUE TITLE
Stacktrace deobfuscation

### ISSUE THREAD

**Issue by AdamGrzybkowski** [DataDog/dd-sdk-android#372]
Do you support stack trace deobfuscation in the Datadog console? If yes, where should I upload the mapping file? If no, would you consider adding this(logging exceptions in the app that has R8 enabled is not very useful)?

**Comment by henningms** [comment]
Adding support for automatic crash reporting with support for symbols would be great. Right now we have to add another third-party SDK to cover that need.

**Comment by elisamalzoni** [comment]
Hello, what is the status on this issue? Still no support?

If not the Log Collection documentation is misleading:
![image](https://user-images.githubusercontent.com/18201769/113919004-773a8580-97b9-11eb-9d09-2235c3c16054.png)
https://docs.datadoghq.com/logs/log_collection/android/?tab=us

**Comment by XyrizTan** [comment]
Bumping this up, I've been experimenting on what to submit to variant name, SDK indicated BuildConfig.FLAVOR is enough but I'm not convinced since mapping files are generated to outputs/mapping/{variant}/mapping.txt (if my app had google/huawei flavors for example, it would be googleRelease and huaweiRelease), anyway setting both `google` and `googleRelease` on datadog sdk credentials yielded no deobfuscated error stacktrace on the dashboard.

**Comment by priyanshi-gupta** [comment]
Wanted to update that crash reporting, de-obfuscation and error tracking has been released. Read more about it in [this blog post](https://www.datadoghq.com/blog/debug-android-crashes/) and get detailed instructions [here](https://docs.datadoghq.com/real_user_monitoring/error_tracking/android/?tab=us#upload-your-mapping-file).

**Comment by henningms** [comment]
Oh! Exciting. Will test asap 😁

**Comment by XyrizTan** [comment]
Hello @priyanshi-gupta, already tested by following the steps on our current release build, can you confirm if this works on the throwable we send in the Logger? Because from my testing, it still doesn't, is it the case that the de-obfuscation only works on Datadog crash reporting?

**Comment by xgouchet** [comment]
@XyrizTan the deobfuscation only works for crashes or errors reported in the RUM product. Logs aren't deobfuscated.

**Comment by XyrizTan** [comment]
> @XyrizTan the deobfuscation only works for crashes or errors reported in the RUM product. Logs aren't deobfuscated.

Any insight if this can be a part of the Datadog Android SDK roadmap? Since the SDK Logger methods take in a throwable, it seems to make sense to also deobfuscate the error objects passed to the logger.

**Comment by dnhyde** [comment]
I use this plugin with [Timber dd integration](https://github.com/DataDog/dd-sdk-android/blob/develop/dd-sdk-android-timber/README.md) it would make a lot of sense to de-obfuscate the throwable stacktrace. I mean I would like to handle the crash but log it somewhere

**Comment by Doetheman** [comment]
Following up on this, will deobfuscating logs be on the roadmap?

**Comment by xgouchet** [comment]
Hi @Doetheman , this is something we're considering, but it's not on our immediate roadmap yet.
