### ISSUE TITLE
RumMonitor.Builder.sampleRumSessions is missing

### ISSUE THREAD

**Issue by fleficher** [DataDog/dd-sdk-android#382]
**Describe what happened**
The `sampleRumSessions`  method from `RumMonitor.Builder` is missing

**Steps to reproduce the issue:**
try to create a RumMonitor object thru the builder:

```kotlin
val monitor = RumMonitor.Builder()
        .sampleRumSessions(75.0f)
        .build()
```

**Describe what you expected:**
The method should be available

**Additional context**
 - Datadog SDK version: 1.5.2

**Comment by xgouchet** [comment]
Hi @fleficher and thanks for opening this issue; 

This method will be available in the upcoming 1.6.0 version, the documentation change have already been merged but we have yet to make a release. A beta version of 1.6.0 will probably be available next week.
