### ISSUE TITLE
Where to find APPLICATION_ID & ENVIRONMENT_NAME vars?

### ISSUE THREAD

**Issue by widevel** [DataDog/dd-sdk-android#384]
Hi. I am trying to configure datadog in my android application but I don't know what to enter in the vars APPLICATION_ID  & ENVIRONMENT_NAME .
![image](https://user-images.githubusercontent.com/41244855/94367192-55ab6380-00dd-11eb-9a8f-80444b48dffe.png)

![image](https://user-images.githubusercontent.com/41244855/94367180-40ced000-00dd-11eb-9128-09124cc91d0f.png)
Thanks

**Comment by xgouchet** [comment]
Hi @widevel, 

You can find the Application Id when you [create an application](https://app.datadoghq.com/rum/create). 

The `"<ENVIRONMENT_NAME>"` is a tag that will be added to all the event from your application and which can be used to filter your events. A good practice is to use your application flavor (e.g: `free` / `paid`), the backend environment targeted (e.g.: `staging` / `prod`), or anything that makes sense for you. The only restriction is that your environment name contains only lowercase alphabetical or numerical characters, `_`, `.`, `/` or `-`.
