### ISSUE TITLE
Improve data usage by reusing Http connections

### ISSUE THREAD

**Issue by AdamGrzybkowski** [DataDog/dd-sdk-android#390]
**Is your feature request related to a problem? Please describe.**
Network data usage is critical for our business and currently, Datadog library is using the biggest number of data from all the libs that we use and our own service as well (around ~10 times more)

**Describe the solution you'd like**
While inspecting the network requests I noticed that Datadog is not reusing HTTP connections (~30-40% are new). This means it needs to make a TLS handshake that takes a significant amount of data. Take a look at the screenshots below (this were two consecutive requests). Notice the total data used.
|1|2|
|---|---|
| ![Zrzut ekranu 2020-10-1 o 10 19 32](https://user-images.githubusercontent.com/12660801/94785373-d5804900-03cf-11eb-9b66-669a76667d1c.png) | ![Zrzut ekranu 2020-10-1 o 10 19 53](https://user-images.githubusercontent.com/12660801/94785477-006a9d00-03d0-11eb-8d65-e21e2a516203.png) |

This profiling was done when the app was in the background and still, the DD was doing ~2 requests per minute. The app I'm working on is turned on 24/7 so if we count that 30% request created a new connection this gives us ~17MB extra data per day. 

Possible solutions:
1. Reuse the HTTP connections 
2. Improve the number of requests made in the background. Ideally, make it configurable by the app. 

**Describe alternatives you've considered**
Bumping up LogLevel
Leaving only critical logs (but at some point we might just as well use crashlytics only) 

**Additional context**
This request is also valid for tracing and RUM

**Comment by xgouchet** [comment]
Hello @AdamGrzybkowski  and thanks for bringing up this topic. 

Indeed we need to ensure we lower our impact on your application in such an intensive use. We are using OkHttp to perform our requests, and in theory it does reuse connections whenever possible. We'll investigate why this doesn't work in your case and fix that ASAP. 

We also intend to provide some ways to configure how often batches are sent, which can alos decrease the number of requests performed by the SDK.

**Comment by xgouchet** [comment]
I've been performing some verifications with Charles Proxy, and although the connection itself is not marked as "kept alive", it is indeed reused. But the default configuration of OkHttp means that any connection will be recreated after 5 minutes of inactivity. This matches what we can already observe on our test, so the next step will be to provide some ways to configure the way data is sent, and possibly tweak the inactivity delay yourself.

**Comment by AdamGrzybkowski** [comment]
> and although the connection itself is not marked as "kept alive", it is indeed reused

The client is reusing the connection, but the server restarts it. This means the TLS handshake is required.
You can see that in the screenshot.

**Comment by xgouchet** [comment]
Thanks for those details, we'll keep investigating that.

**Comment by AdamGrzybkowski** [comment]
Thanks, if you need more specific info from me, let me know. This is very important for us so I'm eager to help as much as I can :)

**Comment by xgouchet** [comment]
Hello @AdamGrzybkowski, 
I made a few more tests, and the server does allow keep alive but only allows one minute of inactivity. I was able to keep a connection alive for 30 minutes while sending logs every 55s, but the connection restarts after 1 minute of inactivity. There's nothing much we can do to improve at our level, apart from what we schedule, that is giving more control on how the batches are gathered and sent to get more efficient data usage.

**Comment by AdamGrzybkowski** [comment]
Hi @xgouchet 
thank you for testing it :) 

> and the server does allow keep alive but only allows one minute of inactivity

is there a reason why BE cannot increase that time? This would be a way quicker solution that would almost immediately work for us as it doesn't require a new SDK release(that will probably not happen soon?)

**Comment by xgouchet** [comment]
We cannot increase this value, first for performance of our load balancer and intake process just for one specific case. Most of our clients application are not running 24/7 (which in general is not a good idea unless it's really needed), so they don't meet such a situation. We'll try to work fast on delivering better control on the upload process, and we'll keep you informed as soon as we can.
