### ISSUE TITLE
Remove dependency on navigation-ui-ktx from the SDK?

### ISSUE THREAD

**Issue by rashadsookram** [DataDog/dd-sdk-android#396]
**Describe what happened**
After adding the Datadog SDK (`com.datadoghq:dd-sdk-android`) to my app, I noticed that the app size increased by more than I expected.

**Steps to reproduce the issue:**
Add the Datadog SDK to an app which doesn't depend on the navigation architecture component.

```gradle
implementation 'com.datadoghq:dd-sdk-android:1.5.2'
```

**Describe what you expected:**
I expected fewer transitive dependencies to be brought in, so that the app size wouldn't increase as much.

These dependencies were brought in, even though they don't appear to be used by the Datadog SDK:
- `androidx.navigation:navigation-ui-ktx`
- `androidx.navigation:navigation-ui`

**Additional context**
 - Datadog SDK version: 1.5.2

R8 is being run on the app, so the increase in size in this case was more from the resources being brought in from `androidx.navigation:navigation-ui`.

---

Looking at the code in this repo, it seems like the navigation dependencies are being brought in from [1](https://github.com/DataDog/dd-sdk-android/blob/71f145be02e51cafac60dc8f05e43c69d1cd4b87/dd-sdk-android/build.gradle.kts#L120) and [2](https://github.com/DataDog/dd-sdk-android/blob/71f145be02e51cafac60dc8f05e43c69d1cd4b87/buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt#L106-L110).

I'm guessing that `AndroidXNavigation` includes the `navigation-ui-ktx` since it might be used in the sample app, but it doesn't seem to be needed by the SDK that gets released.

On the other hand, removing this transitive dependency could be considered a breaking change if people were relying on the Datadog SDK to bring it in. But I hope that this isn't the case.

**Comment by xgouchet** [comment]
Hi @rashadsookram , 
As per the official [Jetpack Navigation Documentation](https://developer.android.com/guide/navigation/navigation-getting-started), the `androidx.navigation:navigation-ui-ktx` artifact is the recommended one when using Kotlin, which is the language used by the SDK and the samples. And this artifact as in turn a transitive dependency to `androidx.navigation:navigation-ui`.
As you said the final APK/App Bundle size should not be impacted with R8, but we'll take a look to figure out if we can safely remove this dependency.

**Comment by xgouchet** [comment]
Hello @rashadsookram 
Upcoming versions (starting with `1.6.0-beta2`) won't have the `androidx.navigation:navigation-ui` or `androidx.navigation:navigation-ui-ktx` dependencies as they are not required indeed.
