### ISSUE TITLE
Update kronos-android to latest version & remove android support dependencies

### ISSUE THREAD

**Issue by erawhctim** [DataDog/dd-sdk-android#408]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
N/A

**Is your feature request related to a problem? Please describe.**
Dependency upgrade

**Describe the solution you'd like**
Upgrade `kronos-android` to the latest version, which will help consumers drop transitive `com.android.support` deps in favor of AndroidX versions & help migrate off of Jetifier. This lib is one of the last remaining usages of support libraries keeping the Jetifier around on our builds.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by erawhctim** [comment]
@xgouchet Thank you for getting this reviewed/merged! Is there a way I can pull these changes down locally as of today (snapshot release?) or do I need to wait for the next official release?

**Comment by xgouchet** [comment]
Hi @erawhctim,
We released an alpha version of our library today (version `1.7.0-alpha1`) which should contain this PR.

Alternatively, you can download the repository and run the following command in s terminal tu publish it to your local maven repository.

```
./gradlew publishToMavenLocal
```

**Comment by erawhctim** [comment]
Perfect! Thank you again
