### ISSUE TITLE
Crash from crashlytics 

### ISSUE THREAD

**Issue by alparp27** [DataDog/dd-sdk-android#413]
v1.6.0 marks one of the crash fix, is this same?

Crash from firebase crqashlytics:

Unable to reproduce myself, or uncertain of exact steps 

Device
Brand: Google
Model: Pixel 5
Orientation: Portrait
RAM free: 3.44 GB
Disk free: 82.11 GB
Operating System
Version: 11
Orientation: Portrait
Rooted: No

Stacktrace:
Fatal Exception: java.lang.RuntimeException
Unable to create application com.everlance.EverlanceApplication: java.lang.SecurityException: Package android does not belong to 10277
android.app.ActivityThread.handleBindApplication
Caused by java.lang.SecurityException
Package android does not belong to 10277
android.os.Parcel.createExceptionOrNull (Parcel.java:2373)
android.net.ConnectivityManager.registerDefaultNetworkCallback (ConnectivityManager.java:4158)
com.datadog.android.core.internal.net.info.CallbackNetworkInfoProvider.register (CallbackNetworkInfoProvider.kt:55)
com.datadog.android.core.internal.CoreFeature.setupInfoProviders (CoreFeature.kt:109)
com.datadog.android.core.internal.CoreFeature.initialize (CoreFeature.kt:60)
com.datadog.android.Datadog.initialize (Datadog.kt:88)
com.datadog.android.Datadog.initialize (Datadog.kt:158)
com.datadog.android.Datadog.initialize$default (Datadog.kt:152)
com.datadog.android.Datadog.initialize (Unknown Source:2)
com.everlance.EverlanceApplication.onCreate (EverlanceApplication.java:70)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1192)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
Caused by android.os.RemoteException
Remote stack trace: at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7631) at com.android.server.ConnectivityService.ensureSufficientPermissionsForRequest(ConnectivityService.java:5444) at com.android.server.ConnectivityService.requestNetwork(ConnectivityService.java:5539) at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:1570) at android.os.Binder.execTransactInternal(Binder.java:1154)

**Comment by mariusc83** [comment]
Hi @alparp27, thank you for the feedback. This crash should have been fixed indeed in the version 1.6.0 already. If you are using Datadog you can look for that particular crash log and check the `logger.version` attribute. This will tell you exactly what was the version of the Datadog SDK in that moment.

**Comment by alparp27** [comment]
Thank you for quick response, @mariusc83, My current version is 1.4.1 so I will update it and keep an eye out for it in future.

**Comment by mariusc83** [comment]
Ok that's good news. I am going to close this issue for now. You can open a new issue anytime if the bug persists also in the 1.6.1. Thank you again for your feedbacks.

**Comment by woxblom** [comment]
Hey, what was the fix for this issue? Have the same crash in my app.

**Comment by mariusc83** [comment]
Hi @woxblom, what version o the SDK are you using ?

**Comment by woxblom** [comment]
Nah I mean I got the same crash in my private app I am making :P Since you said you fixed it in your sdk I thought that maybe you could share how you fixed it :)

**Comment by mariusc83** [comment]
We could not find any way to provide an elegant fix for this as this is thrown in weird conditions by the system. This is the [PR](https://github.com/DataDog/dd-sdk-android/commit/58c1adf2d7ee485b551b3adff25b11eee0f4b4a9) where we basically avoided that exception.

**Comment by woxblom** [comment]
Ah alright thanks! :)
