### ISSUE TITLE
Failed to resolve: com.datadoghq:dd-sdk-android:1.6.1

### ISSUE THREAD

**Issue by Arthur-Tavais-Turbi** [DataDog/dd-sdk-android#425]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Gradle unnable to resolve dependency implementation on Android Java project:
Failed to resolve: com.datadoghq:dd-sdk-android:1.6.1

**Steps to reproduce the issue:**
Added maven { url 'https://dl.bintray.com/datadog/datadog-maven' } to my repositories in my gradle file and  
implementation 'com.datadoghq:dd-sdk-android:1.6.1' to my dependencies

**Describe what you expected:**
Should have imported the dee

**Additional context**
 - Datadog SDK version:
1.6.1
 - Gradle Plugins
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.firebase.crashlytics'

**Comment by mariusc83** [comment]
Hi @Arthur-Tavais-Turbi , we tried to reproduce the issue on our end but we are not able to, everything work fine on our end. Can you please confirm that you are adding this block:
``` 
repositories {
     maven { setUrl("https://dl.bintray.com/datadog/datadog-maven") }
}
```
before the `dependencies` block in your `build.gradle` file ?

**Comment by aliztekup** [comment]
It'd be great if you could include this solution in your onboarding documentation (Edit RMU App --> Instrument your application) in your site as well. It doesn't say about adding the datadog-maven repo.  Currently it says:

```
Add the Gradle dependency by declaring the [dd-sdk-android](https://github.com/DataDog/dd-sdk-android) and [DataDog/dd-sdk-android-gradle-plugin](https://github.com/DataDog/dd-sdk-android-gradle-plugin) as dependencies in your build.gradle file:

plugins {
    id("com.datadoghq.dd-sdk-android-gradle-plugin")
}
dependencies {
    implementation "com.datadoghq:dd-sdk-android:x.x.x"
}
buildscript {
    dependencies {
        classpath("com.datadoghq:dd-sdk-android-gradle-plugin:x.x.x")
    }
}
```

**Comment by 0xnm** [comment]
Hello @aliztekup! Since version 1.8.1 (which was released 2 years ago), our SDK is hosted on the [Maven Central](https://central.sonatype.com/artifact/com.datadoghq/dd-sdk-android/1.17.2/versions) instead. We suggest you to use the recent version, so that no dependency on the Bintray is needed.
