### ISSUE TITLE
Add additional attributes on network interceptor

### ISSUE THREAD

**Issue by justinelliss** [DataDog/dd-sdk-android#448]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
I'm requesting for the DatadogInterceptor

**Is your feature request related to a problem? Please describe.**
Need additional information from the network traces.

**Describe the solution you'd like**
I would like to add additional attributes to the network interceptor. 
Specifically: deviceId, userId, build number, build name, build type

**Describe alternatives you've considered**
I can manually log the calls outside the interceptor.

**Additional context**
Will probably be looking at flutter in the near future - do you have a direct flutter plugin?

**Comment by mariusc83** [comment]
Hi @justinelliss and thank you for your feedback.
Regarding the needed additional information we are already sending part of it (build number, information about the device).
For all the others you can use our Public Api to set global attributes: 
```
    GlobalRum.get().addAttribute(key,value)

    Datadog.setUserInfo(...)
```

More information you can find in our docs: 
https://github.com/DataDog/dd-sdk-android/blob/master/docs/README.md

**Comment by 8secz-johndpope** [comment]
The source code is available for a vanilla interceptor here / minus the logging of datadog - perhaps you could extend this out?
https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor

**Comment by xgouchet** [comment]
Hi, since version `1.9.0`, you can provide a callback in the interceptor to add custom attributes to the RUM resource being captured. E.g.: 

```kotlin
 val attibutesProvider = object : RumResourceAttributesProvider {
            override fun onProvideAttributes(
                request: Request,
                response: Response?,
                throwable: Throwable?
            ): Map<String, Any?> {
                // Construct a map of attributes based on the request, response or throwable
                return mapOf(
                    "custom.request.info" to parseRequest(request),
                    "custom.response.info" to parseResponseBody(response?.peekBody(1024L))
                )
            }
        }

        val datadogInterceptor = RumInterceptor(
            rumResourceAttributesProvider = attibutesProvider
        )

        okHttpClient = OkHttpClient.Builder()
            .addInterceptor(datadogInterceptor)
            .build()
```
