### ISSUE TITLE
Multiple services found in the RUM explorer, despite setting serviceName explicitly 

### ISSUE THREAD

**Issue by hs-kdhillon** [DataDog/dd-sdk-android#462]
**Describe what happened**
I setup the ServiceName in the androidSDK manually as follow:
```
 val datadogConfig = DatadogConfig.Builder(
      BuildConfig.DATADOG_CLIENT_TOKEN,
      BuildConfig.BUILD_TYPE,
      BuildConfig.DATADOG_APPLICATION_ID
    )
      .setServiceName("Android: $packageName")
      .useViewTrackingStrategy(FragmentViewTrackingStrategy(true))
      .setRumEnabled(true)
      .trackInteractions()
      .build()
```

However, in the RUM Explorer I notice two services:

1. One with `Android: <MY PACKAGE NAME>`.
2. One with `android:_<MY PACKAGE NAME>`.

<img width="600" alt="screenshot" src="https://user-images.githubusercontent.com/61422551/103904966-fee5fa80-50cb-11eb-9638-6eb76f2e3da8.png">

Where is this `android:_<MY PACKAGE NAME>` coming from?

**Steps to reproduce the issue:**
1. Initialize datadog SDK in main application's class `onCreate()`.
2. Go to RUM Explorer, and track the services there.

**Describe what you expected:**
I expected to find only `Android: <MY PACKAGE NAME>` service. However, I found another service `android:_<MY PACKAGE NAME>` there.

**Additional context**
 - Android OS version: 10
 - Device Model: Galaxy S10
 - Datadog SDK version: 1.7.9
 - Versions of any other relevant dependencies (OkHttp, …): Retrofit 2.8.1
 - Proguard configuration: Default
 - Gradle Plugins: 
  ```
   const val buildToolsVersion = "4.0.0"
    const val androidJunit5Plugin = "1.6.0.0"
    const val navigationSafeArgsPlugin = "2.1.0"
    const val googleServicesPlugin = "4.3.3"
    const val firebaseCrashlyticsPlugin = "2.3.0"
```

**Comment by hs-kdhillon** [comment]
Apparently, my counterpart in the iOS department is facing the same issue. Even after explicitly setting the service name, a lower-case `ios:_<PACKAGE-NAME>` service is showing up.

The default service names for `android SDK` and `iOS SDK` are `android` and `iOS` respectively. Could it be that these are somehow messing up?

**Comment by xgouchet** [comment]
Hello @hs-kdhillon , 
On both SDK we send the service name the way you give them to us. But service names are sent as Datadog Tags, and so they are constrained in termes of value. This means that in theory, your service name should follow the [same rules](https://docs.datadoghq.com/getting_started/tagging/#defining-tags): 

> - Tags can only contains Alphanumeric characters, Underscores, Minuses, Colons, Periods, or Slashes;
> - Tags can be up to 200 characters (meaning your service name itself can only have 188 characters)
> - Tags are converted to lowercase.

My guess is that some kind of sanitization is perform on your events to conform to those constraints (replacing the space with an underscore). 
Also, note that in theory the default `serviceName` on both platforms (in the latest version of each SDK) should already be your package name.

**Comment by hs-kdhillon** [comment]
@hs-echkayben

**Comment by hs-kdhillon** [comment]
@xgouchet I fixed the issue by renaming my service to `android:<PACKAGE_NAME>`, i.e. by using lowercase `a` and removing the space. Thank you for your help!

PS: Maybe `setServiceName()` docs can be updated to mention that the service name has to comply the `tags` naming convention.

**Comment by xgouchet** [comment]
Glad to hear that, and yes we'll update the documentation to reflect that
