### ISSUE TITLE
DatadogConfig doesn't exist

### ISSUE THREAD

**Issue by 8secz-johndpope** [DataDog/dd-sdk-android#468]
We get an unresolved symbol - 
the rest of the datadog logging works / just not the real time stuff.
We're using the same gradle import mavern.
we have this.

repositories {
    maven { url "https://dl.bintray.com/datadog/datadog-maven" }
}

dependencies {
    implementation "com.datadoghq:dd-sdk-android:1.3.1"
}

@insubliminal

**Comment by xgouchet** [comment]
Hi @8secz-johndpope , 

Indeed, I think the DatadogConfig class didn't exist in version `1.3.1`. You should upgrade your gradle to use the latest version (`1.7.0`)

**Comment by 8secz-johndpope** [comment]
thanks
