### ISSUE TITLE
Clarification on RUM usage

### ISSUE THREAD

**Issue by 8secz-johndpope** [DataDog/dd-sdk-android#470]
When we plug in DataDog - RUM - we don't know what to put for trackingConsent.
Is this supposed to show a popup?
Does the sdk have a problem with debug builds? 
Should we know NOT use this in production?
Do we have to plug in the OKHTTP3 interceptor for it to work?

fyi - @insubliminal

**Comment by xgouchet** [comment]
Hi @8secz-johndpope , 
The tracking consent is mostly related to GDPR, where end users must give their consent to being tracked. The value you can pass in the `initialize()` or `setTrackingConsent()` methods reflect that. We don't create any UI at all, it's up to you to ask the user's consent in your own way.

The usual way we suggest is to start with `PENDING` when you don't yet know what the user asked, and then switch to `GRANTED` or `NOT_GRANTED` depending on the user's preference. While the consent is `PENDING`, we keep the RUM data locally and never upload them to Datadog, and only when the tracking is `GRANTED` do we upload them. 

If you don't have yet a mecanism to ask the user's consent, you can just use `GRANTED` and the SDK will send all the tracking data to Datadog. 

Regarding Debug builds, the SDK should work fine in debug too, but you can disable the SDK to prevent your Debug sessions to add noiose to your data if you want. You can definitely use Datadog in production of course, no issue there.

The OkHttp interceptor is required to get information about your network request and how they can impact the performance of your application.

**Comment by johndpope** [comment]
It seems the docs are specific to kotlin only for view fragment lifecycle. If you could spoon feed a Java snippet around step 5/6 or 7 that would be awesome around tracking of view fragments
