### ISSUE TITLE
Log class names with the Timber logger

### ISSUE THREAD

**Issue by cfa-eric** [DataDog/dd-sdk-android#483]
When using the Timber logger via
` Timber.plant(new DatadogTree(logger));`
the classname doesn't propagate in the logs.  All logs are tagged with `/DatadogTree: ...... 	| at .log(DatadogTree.kt:32)` instead of the actual tag(class).

If I use the DataDog logger directly it works.  It also works if I plant the Timber.DebugTree with `Timber.plant(new Timber.DebugTree());`

This is happening on 1.7.1 (and prior).

**Comment by xgouchet** [comment]
Hi @cfa-eric , and thanks for reporting this issue, we'll take a look into it and try to fix it soon.

In the meantime, note that you can plant multiple trees in Timber, so you can have both a `DatadogTree ` (without Logcat output) and your usual `Timber.DebugTree`.
