### ISSUE TITLE
RUM doesn't send anything

### ISSUE THREAD

**Issue by MohammadRezaei92** [DataDog/dd-sdk-android#484]
I don't receive any data in the RUM dashboard. When I run the application I see this warning in logcat.
`A RUM event was detected, but no view is active. To track views automatically, try calling the DatadogConfig.Builder.useViewTrackingStrategy() method.`

My datadog config:
```
Datadog.initialize(
            this, DatadogConfig.Builder(
                DATADOG_CLIENT_TOKEN,
                envName = BuildConfig.BUILD_TYPE,
                applicationId = DATADOG_APPLICATION_ID
            )
                .useViewTrackingStrategy(MixedViewTrackingStrategy(trackExtras = true))
                .trackInteractions()
                .setRumEnabled(true)
                .build()
        )
```

 - Android OS version:10
 - Device Model:Redmi Note7
 - Datadog SDK version:1.6.1-1.7.1

**Comment by mariusc83** [comment]
Hi @MohammadRezaei92, thank you for your feedback. I am afraid we will need more information from your end to be able to properly investigate this:

1. What approach are you using when creating your application Views (screens). Are you using Fragments + Activities, only Activities or the new Navigation API in the Jetpack package ?
2. Can you manually try to send your View events by calling : 
    ```
    GlobalRum.get().startView(key: Any, name: String)
    GlobalrRum.get().stopView(key:Any)
    
    ```
    and tell us if you can see any events in the Datadog dashboard after ?

**Comment by MohammadRezaei92** [comment]
> Hi @MohammadRezaei92, thank you for your feedback. We will need more information from your end to be able to properly investigate this:
> 
> 1. What approach are you using when creating your application Views (screens). Are you using Fragments + Activities, only Activities or the new Navigation API in the Jetpack package ?
> 2. Can you manually try to send your View events by calling :
>    ```
>    GlobalRum.get().startView(key: Any, name: String)
>    GlobalrRum.get().stopView(key:Any)
>    ```
>    
>    
>    and tell us if you can see any events in the Datadog dashboard after ?

1. I use a mixture of all of them (Activity + Fragment + navigation).
2. I tried this method but, nothing happened and there is no data in my RUM dashboard.

Logcat
```
We could not find a valid target for the TAP event.The DecorView was empty and either transparent or not clickable for this Activity.

RUM Action bc424de7-25c1-4fc2-a898-0b06de725cc3 (TAP on BottomNavigationItemView(navigation_profile)) was dropped (no side effect was registered during its scope)
```

**Comment by mariusc83** [comment]
Hi again @MohammadRezaei92 ,

That log message is normal as we only keep RUM actions that lead to a resource load or an UI state change for now. If your tracked RUM action does not have any outcome we will drop it. 
What I find weird is that you could not see any RUM View event in your Dashboard even by using the manual RUM API, this tells me that maybe it is something wrong in your configuration. Can you check the way we configure the SDK in our [sample](https://github.com/DataDog/dd-sdk-android/blob/master/sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt) app and confirm that you are following all the required steps ?

**Comment by moetouban** [comment]
Hi @mariusc83 i seem to have same issue where i can't see metrics on Datadog dashboard. I followed the documentation and the sample app code. Is there a way to enable logs by datadog to figure out the issue ?

**Comment by xgouchet** [comment]
Hi @moetouban , you can add the following line after you've initialised datadog to enable internal logs: 
```
 Datadog.setVerbosity(Log.VERBOSE)
```
Then if you run your app, you should see warnings or errors in logcat that will help you understand what's hapenning. 

@MohammadRezaei92 were you able to get data showing in the RUM page ?

**Comment by moetouban** [comment]
It was the battery % set to be less than 10% on emulator. Thanks for the help @xgouchet
