### ISSUE TITLE
Crash due to onClick event on an overflowMenu

### ISSUE THREAD

**Issue by hs-kdhillon** [DataDog/dd-sdk-android#492]
**Describe what happened**
Application crashes on `onOverflowMenu` `click` event.
### Crashlog:
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p1
        at com.datadog.android.rum.internal.instrumentation.gestures.WindowCallbackWrapper.onMenuOpened(Unknown Source:2)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuOpened(WindowCallbackWrapper.java:104)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onMenuOpened(AppCompatDelegateImpl.java:2868)
        at com.uxcam.a.d.onMenuOpened(Unknown Source:2)
        at androidx.appcompat.app.AppCompatDelegateImpl$ActionMenuPresenterCallback.onOpenSubMenu(AppCompatDelegateImpl.java:2528)
        at androidx.appcompat.view.menu.BaseMenuPresenter.onSubMenuSelected(BaseMenuPresenter.java:221)
        at androidx.appcompat.widget.ActionMenuPresenter.showOverflowMenu(ActionMenuPresenter.java:345)
        at androidx.appcompat.widget.ActionMenuPresenter$OverflowMenuButton.performClick(ActionMenuPresenter.java:681)
        at android.view.View.performClickInternal(View.java:7831)
        at android.view.View.access$3600(View.java:879)
        at android.view.View$PerformClick.run(View.java:29359)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Steps to reproduce the issue:**
`OnClick` event on an overflow menu item.

**Describe what you expected:**
Datadog is this case is simply being used in the application to monitor app crashes and logging. Datadog reporting the view action event is not a concern in this case. **However, it causing application to crash is alarming.**

**Additional context**
 - Android OS version: 10
 - Device Model: galaxy S10
 - Datadog SDK version: 1.7.1
 - Proguard configuration: default config
 - Gradle Plugins: 
```
        const val kotlinGradlePlugin = "1.3.61"
        const val androidGradlePlugin = "3.6.0"
        const val googleServicesPlugin = "3.1.1"
        const val realmPlugin = "4.3.2"
        const val firebaseCrashlyticsPlugin = "2.3.0"
        const val firebasePerformancePlugin = "1.3.1"
```

**Comment by hs-kdhillon** [comment]
Another similar issue logged here https://github.com/DataDog/dd-sdk-android/issues/455.

**Comment by xgouchet** [comment]
Hi @hs-kdhillon 
Thanks for reporting this issue. The official android source code [explicitely mentions the menu is supposed to be `NonNull`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/Window.java#463) and the `WindowCallbackWrapper ` class in our SDK uses Kotlin to delegate it to the wrapped callback. All that considered, we are missing more information to reproduce and fix this issue.

Can you share with us the  xml file used to create the menu, and any other useful information to understand how a menu can be passed as null ?

**Comment by hs-kdhillon** [comment]
### chat_menu.xml
```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    >

    <item
        android:id="@+id/action_phone"
        android:orderInCategory="100"
        android:title="Phone"
        app:showAsAction="always"
        android:icon="@drawable/ic_call_button"/>

    <item
        android:id="@+id/action_hired"
        android:orderInCategory="100"
        android:title="Hired"
        app:showAsAction="never" />

    <item
        android:id="@+id/action_nothired"
        android:orderInCategory="100"
        android:title="Not Hired"
        app:showAsAction="never" />

    <item
        android:id="@+id/action_accept"
        android:orderInCategory="100"
        android:title="Accept"
        app:showAsAction="never" />

    <item
        android:id="@+id/action_decline"
        android:orderInCategory="100"
        android:title="Decline"
        app:showAsAction="never" />

    <item
        android:id="@+id/action_archive"
        android:orderInCategory="100"
        android:title="Archive"
        app:showAsAction="never" />

    <item android:id="@+id/action_unarchive"
        android:orderInCategory="100"
        android:title="Unarchive"
        app:showAsAction="never" />

    <item
        android:id="@+id/action_share"
        android:orderInCategory="100"
        android:title="Share"
        app:showAsAction="never" />

</menu>
```
### ChatActivity
```
override fun onCreateOptionsMenu(menu: Menu?): Boolean {
    menuInflater.inflate(R.menu.chat_menu, menu)
    return true
}

override fun onOptionsItemSelected(item: MenuItem?): Boolean {
        when {
            item!!.itemId == R.id.action_share -> viewModel.onShareClicked()
            item.itemId == android.R.id.home -> onBackPressed()
            item.itemId == R.id.action_accept -> viewModel.onAcceptClicked()
            item.itemId == R.id.action_decline -> viewModel.onDeclineClicked()
            item.itemId == R.id.action_phone -> viewModel.onPhoneClicked()
            item.itemId == R.id.action_unarchive -> viewModel.onUnarchiveClicked()
            item.itemId == R.id.action_hired -> viewModel.onHiredClicked()
            item.itemId == R.id.action_nothired -> viewModel.onNotHiredClicked()
        }

        return super.onOptionsItemSelected(item)
}
```

Is the absence of `nullability check` here causing the error `override fun onOptionsItemSelected(item: MenuItem?): Boolean`? This is an old project, and not my code.

**Comment by hs-kdhillon** [comment]
Seems like `onOptionItemsSelected` signature has changed to `onOptionsItemSelected(item: MenuItem): Boolean`. I'll test the app with this new change, and update the issue with the findings.

**Comment by hs-kdhillon** [comment]
Changing the signatures did nothing. App still crashes when `menu` is clicked on. Removing the dataDog dependency, however doesn't crash the app.

**Comment by xgouchet** [comment]
Hi @hs-kdhillon, even when using your menu I couldn't reproduce this issue at first. I dug into the `androidx.appcompat` source code and found a bug in the version `1.1.0` which was solved in `1.2.0`.

In your dependencies, can you make sure you're using `"androidx.appcompat:appcompat:1.2.0"` or higher. This should make this crash disappear.

**Comment by hs-kdhillon** [comment]
Hi @xgouchet , can confirm the bug was related to `androidx.appcompat:appcompat` as the project was using version `1.0.0` and upgrading to version `1.2.0` fixed it 👍. Can you attach the link where this issue is mentioned @xgouchet ? would be helpful for post-analysis. And thank you for your swift help as always 💯 .

Closing the issue now.

**Comment by xgouchet** [comment]
Of course, here's the official issue in the `appcompat` project: https://issuetracker.google.com/issues/142843126
