### ISSUE TITLE
Network Error: Error when dispatching Datadog logs

### ISSUE THREAD

**Issue by rdavidson2143** [DataDog/dd-sdk-android#493]
**Describe what happened**
Include any error message or stack trace if available.
We have been seeing an issue related to his network for about 3 weeks. When running the project, the android sdk is not logging properly to the dashboard. This is the error we're seeing:

`3139/com.cfa.openpos.sppayment E/Datadog: Unable to send batch [80681 bytes] (LogsOkHttpUploader) because of a network error; we will retry later.`

I've attached the full logs here:
[DDLoggingDevTerm_2_5.txt](https://github.com/DataDog/dd-sdk-android/files/5945065/DDLoggingDevTerm_2_5.txt)

**Steps to reproduce the issue:**
Only one of our team members has been seeing this and can reproduce it on their network. A router reboot fixes the issue but after a few hours the sdk will stop reporting logs again.

**Additional context**
 - Android OS version: Running android sdk 29 on app, android version 6.0 on device
 - Device Model: Pax A60 & A77
 - Datadog SDK version: 1.7.1
 - Versions of any other relevant dependencies (OkHttp, …): okhttp 4.4.0
 - Proguard configuration: 
 - Gradle Plugins:

**Comment by mariusc83** [comment]
Hi @rdavidson2143 , thank your for taking the time to describe this issue. We're going to investigate this internally an we will get back to you once we have found something. In the meantime can you please give us more details:

1. Can you perform any other network request from the specific application once you get the `Unable to send batch...` error log ?
2. Is this happening only on that specific device type ?
3. If you switch on a different router is the problem persisting ?

**Comment by mariusc83** [comment]
Hi again @rdavidson2143 , there is one more think you may try:
- set the verbosity level to `Log.VERBOSE` in your SDK : `Datadog.setVerbosityLevel(Log.VERBOSE)`. This will enable more logs coming from the SDK
- after doing this please look for an info log: 
                   ```                   
                   Response from [URL] code:[HTTP_CODE] body: [RESPONSE_BODY] headers: [RESPONSE_HEADERS
                    ```
  and send it to us if possible. 
  
  Thanks !!

**Comment by rdavidson2143** [comment]
Hi Marius,
1. We are able to run Sp-Payments transactions when the android sdk is having issues
2. So we only test on the A77 and A60 but this issue occurs in both devices.
3. We do not have another router as this is on a teammates home network. 
4. Our application is Android only as of now so we're not able to answer this.

I believe I set the Verbosity level of the logs to `Log.VERBOSE` to ensure we had the full flow of logs coming through. Is there a way to tell what verbosity it is set to on your side?

Thank you!

**Comment by mariusc83** [comment]
Hi Rob,

Thanks for all the information. Actually you are right, we do not log that type of information for the release version of our SDK sot the verbosity level will not change anything on that front. Let me speak with our support team, maybe we can have a live debug session with you in order to better understand what is going on.

**Comment by mariusc83** [comment]
In the meantime there's a trick that you can do by using a proxy (Charles for example) and see what the is the request answer in that moment. If you can get that please let me know.

**Comment by xgouchet** [comment]
Hi @rdavidson2143, this issue has been stale for a while now, is this issue still happening with the latest version `1.11.0-rc1`? I'll close this issue for now, but feel free to repoen it if you have more details about this.
