### ISSUE TITLE
Move away from Bintray

### ISSUE THREAD

**Issue by pvegh** [DataDog/dd-sdk-android#494]
One more reason now: service is shutting down

Source:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by xgouchet** [comment]
Hello @pvegh 
Thanks for reaching out to us, we already know about JFrog shutting down and migrating to another host is part of our roadmap.

**Comment by benkuhn** [comment]
Any updates on the timing on this? Bintray started their first brownout today, so our Datadog dependency is currently breaking our Android build.

**Comment by pvegh** [comment]
https://status.bintray.com/

**Comment by prolificcoder** [comment]
Hello, this is completely blocking our pipelines, please give us an alternative location to download the binaries

**Comment by erawhctim** [comment]
@prolificcoder I was able to check out the repository manually and follow the assembly instructions in [the Contributing guidelines](https://github.com/DataDog/dd-sdk-android/blob/master/CONTRIBUTING.md) to generate an AAR to use; you may want to try that.

**Comment by xgouchet** [comment]
Hi everyone, 
In theory, old packages will still be served by Bintray for the next 12 months (cf [their update here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)). In the meantime we already started migrating to [maven central](https://search.maven.org/search?q=dd-sdk-android), so all versions starting with `1.9.0` will be available there. We already have a couple of `alpha` released there, `beta`, `rc` and a release will follow in the upcoming weeks.

**Comment by pvegh** [comment]
Sorry for being pushy, but can we ask for more? Is it really too much to ask to upload the current stable to maven central?

We are using the library in PROD and actually paying for the service. If our releases/MRs/any builds are blocked because of this, it's not quite acceptable if you ask some of us.

**Comment by xgouchet** [comment]
Hi @pvegh, I'll work to add the latest stable version before the next scheduled downtime at Bintray.

**Comment by xgouchet** [comment]
Hi @pvegh  , @samandmoore, @prolificcoder, @benkuhn  
The latest stable version `1.8.1` is now available on Maven Central, which you can use now until the `1.9.0` stable version is released.
