### ISSUE TITLE
[Question] How to modify RUM Resource metadata

### ISSUE THREAD

**Issue by erawhctim** [DataDog/dd-sdk-android#508]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
No

**Is your feature request related to a problem? Please describe.**
We're using `DatadogInterceptor` to enable both APM tracing and RUM integration in our Android app.
We have an internal tool that obfuscates URL paths so that HTTP request data in DD/other systems removes PII: 
- `GET /orders/1.0/{orderId}` would become `GET /orders/1.0/[ORDERID]`
- `POST /users/CustomerId-1234/profile` would become `POST /users/[USERID]/profile`

Currently, we're using a custom `TracedRequestListener` on the interceptor to modify the Span and update the URL path, and its working great 👍 However, the automatic tracking of HTTP calls as RUM Resources doesn't use that same listener like I though it would, so RUM Resources aren't obfuscated and PII is showing up in our HTTP URLs in the RUM Resource records.

**Describe the solution you'd like**
Is there a way to translate/modify RUM Resource data before its sent up to the server? I'm not sure if RUM Resources are built/tracked using Spans, or some other mechanism... so re-using the existing `TracedRequestListener` may not make sense. 

**Describe alternatives you've considered**
It seems like the RUM integration may have internal mechanisms to accomplish this (e.g. `EventMapper` ?), but I'm not sure of the best way to take advantage of them.

**Additional context**
N/A

**Comment by mariusc83** [comment]
Hi @erawhctim , yes there is a way in our latest version `1.8.0`. We are providing event mappers that could be added in the configuration:
```
val configuration = Configuration.Builder(...).setRumResourceEventMapper(object:EventMapper<ResourceEvent>{
                override fun map(event: ResourceEvent): ResourceEvent? {
                   event.resource.url = <YOUR_URL>
                   return event 
                }
            })
```

**Comment by erawhctim** [comment]
@mariusc83 Thank you! This is _exactly_ what I'm looking for 😄
