### ISSUE TITLE
[Question] How to correctly identify users in RUM Sessions

### ISSUE THREAD

**Issue by rmelick-vida** [DataDog/dd-sdk-android#510]
The javascript docs are pretty clear about the correct way to set the user context, by calling the [setUser function](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#identify-user-sessions).  What's the correct way to do this using the android sdk?  Should I use those same properties (`usr.id`, `usr.name`, `usr.email`), and call `GlobalRum.addAttribute(...)`?

If so, it would be great to update the docs.

**Comment by erawhctim** [comment]
@rmelick-vida I'm just using the global `Datadog.setUserInfo(...)` call and seeing user attributes appear (both in RUM events/resources, and APM tracing).

**Comment by mariusc83** [comment]
Hi @rmelick-vida, indeed what @erawhctim is proposing the right away. You can set the user information by calling the following API method:
```
Datadog.setUserInfo(id, name, email, extraInfo)
```
We are going to have also updated docs on this topic very soon.

**Comment by xgouchet** [comment]
Our documentation now mentions how to [Track Users](https://github.com/DataDog/dd-sdk-android/blob/master/docs/configure_rum_android_sdk.md#track-user-sessions).
