### ISSUE TITLE
OkHttp interceptor doesn't see "known hosts" list when OkHttp is initialized before the SDK

### ISSUE THREAD

**Issue by erawhctim** [DataDog/dd-sdk-android#513]
Thanks for taking the time for reporting an issue!

**Describe what happened**
When `OkHttp` is initialized before the DD SDK and one of the `TracingInterceptor`s is used, any "known hosts" set in the SDK Configuration aren't picked up by the interceptor(s) and those requests ultimately aren't traced in APM. This happens with the newer, non-deprecated Interceptor constructors that _don't_ take in a list of known hosts (e.g. [here](https://github.com/DataDog/dd-sdk-android/blob/09f7543eacf788755bb4a3bc05b5c4310bf684b3/dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt#L116-L118)). 

**Steps to reproduce the issue:**
I've modified the sample app in my own fork to reproduce this issue ([commit here](https://github.com/erawhctim/dd-sdk-android/commit/e2b045e204c4a4508987843835690247a7f9287f)):
- Create an OkHttpClient with a `TracedRequestListener` and _no_ known hosts provided. 
- Set known hosts in the DD SDK Configuration
- Initialize the `OkHttpClient` _before_ the DD SDK
- Add the expected hostname as a known host (e.g. "unsplash.com" in this case)
- Run the sample, go to the image loader and choose Picasso as the load type
- Load image; If you debug within `TracingInterceptor` you'll notice that tracing is not enabled and `FirstPartyHostDetector.knownHosts` is empty

~This can be avoided by using the deprecated Interceptor constructor(s) that take in the list of known hosts when constructing the `OkHttpClient`, but I'd rather not rely on deprecated functionality if it will be removed in the future.~
EDIT: This doesn't seem to work any more with v1.8.0 🤔 however, providing the known hosts into the Interceptor used to work in prior SDK versions.

**Describe what you expected:**
- I expect to be able to construct my `OkHttpClient` earlier than the DD SDK and still have APM/RUM tracing work properly. 
  - (we initialize `OkHttp` earlier than any of our dependencies since its used by almost everything).
- If the DD SDK must be initialized first, I need an initialization callback to be notified when the SDK is finished initializing (see issue #511). 
- If neither of those are possible, should [the old/deprecated Interceptor constructor](https://github.com/DataDog/dd-sdk-android/blob/09f7543eacf788755bb4a3bc05b5c4310bf684b3/dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt#L91-L95) become un-deprecated? What's the best path forward here?

**Additional context**
 - Android OS version: Android 11
 - Device Model: Galaxy S10
 - Datadog SDK version: 1.8.0
 - Versions of any other relevant dependencies (OkHttp, …): Whatever is set in the sample app
 - Proguard configuration: Whatever is set in the sample app
 - Gradle Plugins: Whatever is set in the sample app

**Comment by xgouchet** [comment]
Hello @erawhctim , and thanks for reporting this issue. It's been fixed and will be available in version `1.8.1` (which should be available soon).

**Comment by erawhctim** [comment]
Great, thank you!
