### ISSUE TITLE
Update documentation on Glide module

### ISSUE THREAD

**Issue by fleficher** [DataDog/dd-sdk-android#528]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
No

**Is your feature request related to a problem? Please describe.**
The Glide README documentation file hasn't been updated since the RUMM-911 PR: https://github.com/DataDog/dd-sdk-android/pull/433.
The main example still use the deprecated `DatadogGlideModule`.

**Describe the solution you'd like**
Update the documentation without the usage of `DatadogGlideModule` & by using `DatadogConfig.setFirstPartyHosts()`

**Additional context**
The deprecation warning isn't clear enough: should we replace the entire `DatadogGlideModule` usage to use our own OkHttp client & add the `DatadogInterceptor` ourselves or is it just the `DatadogGlideModule` constructor with `tracedHosts` that is deprecated?

**Comment by xgouchet** [comment]
Hi @fleficher , and thanks for noticing that. We actually un-deprecated that method (to follow the un-deprecation of the underlying OkHttp interceptors).
