### ISSUE TITLE
First party hosts don't support regex

### ISSUE THREAD

**Issue by fleficher** [DataDog/dd-sdk-android#530]
**Describe what happened**
After updating from version `1.6.1` to `1.8.1`, I encounter some issues with the integration of resources tracking.

As suggested in the deprecation replacements guide, I've moved the hosts from the `DatadogInterceptor` constructor to the `DatadogConfig#setFirstPartyHosts` method.

After doing that, I got an error message
`The host name or ip address used for first party hosts: ^*\.blabla\.* was malformed. It will be dropped.`

**Steps to reproduce the issue:**
During the sdk init, call `setFirstPartyHosts` with a host containing a valid regex :

```kotlin
        Configuration.Builder(
            ...
        )
            .setFirstPartyHosts(listOf("^*\\.cloudfront\\.*"))
            .build()
```

And add a  `DatadogInterceptor` to the OkHttp client.

**Describe what you expected:**
This works like before. Regex in hosts should be accepted.

**Additional context**
 - Android OS version: Any
 - Device Model:Any
 - Datadog SDK version: 1.8.1

**Comment by xgouchet** [comment]
Hi @fleficher, 

the goal of `firstPartyHosts` is to define hosts that do belong to you, and as such we do not support regex to define those. Note that when you provide us with a host name (e.g.: `d111111abcdef8.cloudfront.net`), any request with the given host will be traced, even if the request uses subdomains (e.g.: if you use host `example.com`, requests made to `api.example.com` will be traced and considered first party).

**Comment by fleficher** [comment]
Hi @xgouchet 

In my use-case we host many domain names per countries, for ex: `mydomain.fr`, `mydomain.com`, `mydomain.de`. How can I trace all of them with a single item in `firstPartyHosts`?

**Comment by xgouchet** [comment]
Hi @fleficher 
Unfortunately for now we don't have any way to do this. Unless you actually do own all the TLDs (as of today, there are 1500+ valid TLDs) for your host name, you shouldn't user a regex to do that.
Our of curiosity, how do you set which endpoint you target when you build your request? Is it something different per application? Per user?

**Comment by fleficher** [comment]
Currently, I use the `DatadogInterceptor` with a list using regex on it & it's working:

```kotlin
DatadogInterceptor(
    listOf("preprod.mydomain\\.*", "www.mydomain\\.*",)
)
```
So I can have the traces for www.mydomain.fr www.mydomain.de, etc.

**Comment by xgouchet** [comment]
Yes it is an unwanted side effect of the previous implementation. We highly recommend you set the list of hosts manually. You must have a manual way to do that anyway when you build your requests, don't you ?

**Comment by fleficher** [comment]
Not really, we use a base url for our requests that can be dynamic, so the host can change at runtime.
If it's the recommended way, we will have to set the list of all our hosts one by one then. Otherwise, I preferred the previous way it was working :)

**Comment by xgouchet** [comment]
It is indeed the recommended way, passing in regex won't work as it will lead to a more complex pattern to handle, and can also break the behavior of the SDK.
