### ISSUE TITLE
isInitialized is non-static

### ISSUE THREAD

**Issue by joel-bitar** [DataDog/dd-sdk-android#566]
**Describe what happened**
I'm trying to use the isInitialized method in com.datadog.android.Datadog. However it seems like it's a non static member and there is no way to get an instance of Datadog?

**Steps to reproduce the issue:**
Try to call Datadog.isInitialized() like in the readme (https://github.com/DataDog/dd-sdk-android/blob/master/docs/log_collection.md). It's not possible since isInitialized isn't a static method.

**Describe what you expected:**
I expect to be able to call Datadog.isInitialized() like the readme describes (without using an instance of Datadog).

**Additional context**
 - Android OS version: n/a
 - Device Model: n/a
 - Datadog SDK version: 1.8.1
 - Versions of any other relevant dependencies (OkHttp, …): n/a
 - Proguard configuration: n/a
 - Gradle Plugins: n/a

**Comment by xgouchet** [comment]
It seems you might be calling from Java. We indeed miss the static visibility on this particular method, but you should be able to call 
```java
    Datadog.INSTANCE.isInitialized()
```

**Comment by joel-bitar** [comment]
Alright, thanks!
