### ISSUE TITLE
Allow org.json.JSONObject attributes

### ISSUE THREAD

**Issue by fleficher** [DataDog/dd-sdk-android#588]
**Is your feature request related to a problem? Please describe.**
Attributes values can be added for String Long, Int,... types & also with a JsonObject from **Gson** library.

**Describe the solution you'd like**
Instead of only allowing `JsonObject` from Gson, allow passing `JSONObject` from `org.json` package.
This will allow SDK users to add a dependency over Gson to send Json attribute types.

```kotlin
fun addAttribute(key: String, value: JSONObject)
```

**Comment by xgouchet** [comment]
Hi @fleficher 
We're going to look into that, thanks a lot for this  feature request

**Comment by HusseinElFeky** [comment]
Is there any plan on implementing this? We would also like to add `JSONObject` as an attribute to avoid adding `Gson`.

**Comment by xgouchet** [comment]
Hey @HusseinElFeky, this is on our roadmap, but I can't give you any ETA yet. You can also use the following code as a work around if you need to : 
```


    fun addAttribute(logger: Logger, key: String, obj: JSONObject) {
        val objKeys = obj.keys()
        while (objKeys.hasNext()) {
            val k = objKeys.next()
            val v = obj.get(k)
            val nestedKey = "$key.$k"
            if (v is JSONObject) {
                addAttribute(logger, nestedKey, v)
            } else if (v is String) {
                logger.addAttribute(nestedKey, v)
            } else if (v is Int) {
                logger.addAttribute(nestedKey, v)
            } else if (v is Long) {
                logger.addAttribute(nestedKey, v)
            } else if (v is Float) {
                logger.addAttribute(nestedKey, v)
            } else if (v is Double) {
                logger.addAttribute(nestedKey, v)
            } else if (v is Boolean) {
                logger.addAttribute(nestedKey, v)
            } else {
                logger.addAttribute(nestedKey, v.toString())
            }
        }
    }
```

**Comment by HusseinElFeky** [comment]
@xgouchet That's great, and thank you for the workaround!
