### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by joshua-davis-rose** [DataDog/dd-sdk-android#590]
**Describe what happened**
Builds are now failing when trying to pull from maven central

Snippet from app/gradle.build
```
allprojects {
    repositories {
        ...
        maven { url "https://dl.bintray.com/datadog/datadog-maven" }
        ...
    }
}
```

Snippet from /gradle.build
```
dependencies {
    ...
    implementation "com.datadoghq:dd-sdk-android:1.4.3"
    ...
}
```

Error message during build:
```
   > Could not resolve com.datadoghq:dd-sdk-android:1.4.3.
     Required by:
         project :app
      > Could not resolve com.datadoghq:dd-sdk-android:1.4.3.
         > Could not get resource 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/dd-sdk-android/1.4.3/dd-sdk-android-1.4.3.pom'.
            > Could not GET 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/dd-sdk-android/1.4.3/dd-sdk-android-1.4.3.pom'. Received status code 403 from server: Forbidden
```

**Steps to reproduce the issue:**
Nothing has changed since July 2020. Our travis ci builds started failing today. Local builds work for the above version, but fail for all newer versions.

**Comment by rgross4** [comment]
I'm experiencing the same issue when I attempt to fetch version 1.6.1 on CircleCI, I've migrated to the newly hosted files on maven central, but need to update an existing build.

```      > Could not resolve com.datadoghq:dd-sdk-android:1.6.1.
         > Could not get resource 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/dd-sdk-android/1.6.1/dd-sdk-android-1.6.1.pom'.
            > Could not GET 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/dd-sdk-android/1.6.1/dd-sdk-android-1.6.1.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.datadoghq:dd-sdk-android:1.6.1.
         > Could not get resource 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/dd-sdk-android/1.6.1/dd-sdk-android-1.6.1.pom'.
            > Could not GET 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/dd-sdk-android/1.6.1/dd-sdk-android-1.6.1.pom'. Received status code 403 from server: Forbidden
```

**Comment by xgouchet** [comment]
Hi @joshua-davis-rose , @rgross4 ,

Our old artifacts used to be stored on Bintray which has stopped its reprository hosting services. All our artifacts from version `1.8.1` and up are stored on maven central, but unfortunately older artifacts were not migrated. We highly recommend upgrading to the latest version of our SDK to get the latest features and many bugfixes.

**Comment by jonstine** [comment]
In case anyone else runs into this and has the same problems that @joshua-davis-rose and I did, there was an update to how you had to initialize the Datadog agent. We used to do:

```
        final DatadogConfig.Builder configBuilder;
        configBuilder = new DatadogConfig.Builder(clientToken)
            .setEnvironmentName(environment);
        Datadog.initialize(MainApplication.getContext(), configBuilder.build());
```

With the upgrade to 1.8.1 I had to change this to:

```
        final DatadogConfig.Builder configBuilder;
        configBuilder = new DatadogConfig.Builder(clientToken, environment);
        Datadog.initialize(MainApplication.getContext(), configBuilder.build());
```

I couldn't for the life of me find any documentation about this, so hopefully this saves someone else from flailing.

**Comment by xgouchet** [comment]
Hi @jonstine, there was indeed changes on how we initialise the SDK, the [documentation page](https://docs.datadoghq.com/real_user_monitoring/android/?tab=us) explains the recommended method to initialise the SDK
