### ISSUE TITLE
Option to provide an HTTP proxy or custom OkHttpBuilder / factory

### ISSUE THREAD

**Issue by ruXlab** [DataDog/dd-sdk-android#592]
Hello Datadog team

Could you please provide an option to set HTTP proxy? Devices in our organisation can't access the Internet directly. 

**Is your feature request related to a problem? Please describe.**
Our Android devices don't have direct access to the Internet, all applications must use HTTP proxy

**Describe the solution you'd like**
Please provide an option to supply a custom `OkHttpClient` or proxy configuration settings. 

**Describe alternatives you've considered**
There are no alternatives

**Comment by xgouchet** [comment]
Hi @ruXlab, 
Thanks for reporting this issue, we're going to look into this feature request.
In the meantime, is there a way to setup the Proxy on the device level, to apply this globally ?

**Comment by trymnilsen** [comment]
Are you open for external contributions on this? We are also looking at using a proxy for our project and could be willing develop and share this.

**Comment by ruXlab** [comment]
I ended up forking project locally and adding `okHttpBuilder` to `Configuration.Core` and `DatadogConfig.CoreConfig`, changing few relevant methods, namely `setupOkHttpClient` and adding `setOkHttpBuilder` method for `Configuration.Builder`.

**Comment by xgouchet** [comment]
Hi @trymnilsen , we added this topic in our backlog and we have a bunch of constraints, but thanks for offering to contribute. We'll try and have this done as soon as possible

**Comment by trymnilsen** [comment]
Great, thanks for the response
