### ISSUE TITLE
Log collection exceptions stacktrace deobfuscation

### ISSUE THREAD

**Issue by XyrizTan** [DataDog/dd-sdk-android#627]
A related issue has been resolved (stacktrace de-obfuscation for the crash reporting feature of datadog)
https://github.com/DataDog/dd-sdk-android/issues/372

But I have some problem with the Log collection documentation implying that log reporting errors are de-obfuscated (which it isn't according to @xgouchet 's response to the above closed issue)

From https://docs.datadoghq.com/logs/log_collection/android/?tab=us : 

> Note that in the credentials required for initialization, your application variant name is also required. This is important because it enables the right proguard mapping.txt file to be automatically uploaded at build time. This allows a Datadog dashboard to de-obfuscate the stack traces.

Can you confirm what does the documentation really meant? It's in the log collection section yet SDK devs confirmed that de-obfuscation isn't supported in the log reporting as per https://github.com/DataDog/dd-sdk-android/issues/372

**Comment by xgouchet** [comment]
Hi @XyrizTan ,
this is indeed an error on our part in the documentation. We'll remove this misleading line, for now there's no deobfuscation available on logs.
