### ISSUE TITLE
DatadogInterceptor for grpc

### ISSUE THREAD

**Issue by bplotnick** [DataDog/dd-sdk-android#646]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : [e.g. `Realm`, `RxJava`]
grpc
- Library type: [e.g. database]
rpc

**Is your feature request related to a problem? Please describe.**
There's a tracing+RUM interceptor for OKHttp, but it would be great to have this for grpc, like an android version of the [TracingClientInterceptor](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/TracingClientInterceptor.java)

**Comment by 0xnm** [comment]
Hello @bplotnick. As stated in https://github.com/DataDog/dd-sdk-ios/issues/515 we don't have plans to support `gRPC` in the short term, but you can trace it by yourself: you need to create interceptor for the library you are using, and then you can use our tracer. You can start span by doing `GlobalTracer.get().buildSpan(...).start()` and finish it with `finish` method. You can check more examples here https://github.com/DataDog/dd-sdk-android/blob/master/docs/trace_collection.md. Does it work for you?

**Comment by bplotnick** [comment]
@0xnm I ended up just using the OT-contrib interceptor, which seems to work. I just pass it the `GlobalTracer`. I was just thinking that it would be great to have a consistent approach: https://github.com/opentracing-contrib/java-grpc/blob/master/src/main/java/io/opentracing/contrib/grpc/TracingClientInterceptor.java

But I can close this issue out
