### ISSUE TITLE
Make Datadog plugin compatible with Gradle configuration cache

### ISSUE THREAD

**Issue by NFesquet** [DataDog/dd-sdk-android#655]
**Is your feature request related to a problem? Please describe.**
Datadog plugin is not compatible with [Gradle configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:usage).
This feature is still experimental but it would significantly improve build performance.

**Describe the solution you'd like**
An improvement to make it compatible.

**Describe alternatives you've considered**
Disable configuration cache while the plugin is not compatible.

**Additional context**
When enabling configuration cache, build is in error. Here's a piece of the stacktrace:
```
Caused by: org.gradle.configurationcache.ConfigurationCacheError: Configuration cache state could not be cached: field 
  'action' from type 'org.gradle.api.internal.AbstractTask$TaskActionWrapper': error writing value of type 
  'com.datadog.gradle.plugin.DdAndroidGradlePlugin$configureVariantForSdkCheck$1'

Caused by: org.gradle.configurationcache.ConfigurationCacheError: Configuration cache state could not be cached: field 
  '$variant' from type 'com.datadog.gradle.plugin.DdAndroidGradlePlugin$configureVariantForSdkCheck$1': error writing value
   of type 'com.android.build.gradle.internal.api.ApplicationVariantImpl'
```

**Comment by 0xnm** [comment]
Hello @NFesquet. Please follow comments here https://github.com/DataDog/dd-sdk-android-gradle-plugin/issues/39. The necessary change was done and will be available in the next release of `dd-sdk-android-gradle-plugin`, you would need also to set sdk check to `none`.
