### ISSUE TITLE
Modularize core SDK

### ISSUE THREAD

**Issue by eduardb** [DataDog/dd-sdk-android#680]
**Is your feature request related to a problem? Please describe.**

I would like for the core SDK to be modularized, so I can include in my project only the features I want/use. This would result in smaller binary size, but also it could help avoid crashes caused by some of the (unused) features, like the one described in #678 

**Describe the solution you'd like**
Separate artifacts for RUM, logs, tracing and crash reporting, something like this:
`"com.datadoghq:dd-sdk-android-core:x.x.x"` <- main entry point
`"com.datadoghq:dd-sdk-android-rum:x.x.x"`
`"com.datadoghq:dd-sdk-android-logs:x.x.x"`
`"com.datadoghq:dd-sdk-android-traces:x.x.x"`
`"com.datadoghq:dd-sdk-android-crash-reporting:x.x.x"`

Change DataDog initialization method to something like this:
```kotlin
fun initialize(
    context: Context,
    credentials: Credentials,
    trackingConsent: TrackingConsent,
    vararg features: Feature
)
```

Which could be used like this:
```kotlin
Datadog.initialize(
    this, 
    credentials, 
    TrackingConsent.GRANTED, 
    Feature.Logs.Builder().build(), 
    Feature.RUM.Builder().build(), 
    Feature.Tracing.Builder().build(),
)
```

**Comment by xgouchet** [comment]
Hi @eduardb, thanks for the suggestion, indeed this align with some of the improvement we might want to add in the future. This is a huge refactor though, so I can't give you any ETA on when that might come.

**Comment by 0xnm** [comment]
Hello @eduardb! 

We now have [first beta of SDK v2 available](https://github.com/DataDog/dd-sdk-android/releases/tag/2.0.0-beta1) which have a better modularization and allows to use individual products without pulling unnecessary code overhead. Please check migration guide for more details.
