### ISSUE TITLE
How To run sample App

### ISSUE THREAD

**Issue by Sagar9821** [DataDog/dd-sdk-android#736]
Thanks for taking the time for reporting an issue!

**Describe what happened**
I am not able to run the downloaded sample app and also not able to add the package in new project
**Steps to reproduce the issue:**

**Describe what you expected:**
I Just want to run sample app from my android studio 
**Additional context**
 - Android OS version: 8.0
 - Device Model: 
 - Datadog SDK version: 1.7.0

**Comment by xgouchet** [comment]
Hello @Sagar9821, did @0xnm's advice help you in using the SDK in your project? There's not been activity on this ticket so I'll assume it works, feel free to reopen it if you still have trouble on this specific topic.
