### ISSUE TITLE
Sampling setting is ignored

### ISSUE THREAD

**Issue by ogartaganis** [DataDog/dd-sdk-android#742]
Hello!

**Describe what happened**
I'm trying to set traces in my Android application and even though I can see the traces through the Datadog Web UI, it seems that I'm subjected to sampling smaller than 100%.

I tried explicitely declaring `ANALYTICS_SAMPLE_RATE` to `1.0` but it didn't help. It seems like I'm receiving one sample every ~10 minutes.
```
GlobalTracer.get().buildSpan("awesome.span")
            .withTag("chunkId", chunkId)
            .withTag(DDTags.SPAN_TYPE, "client.android")
            .withTag(DDTags.ANALYTICS_SAMPLE_RATE, 1.0)
            .start()
```

**Steps to reproduce the issue:**
I hope the information is sufficient. Otherwise I can clarify something for you.

**Describe what you expected:**
Expecting all my spans to be seen in the "Traces" section and not sampled.

**Additional context**
 - Android OS version: 12
 - Device Model: Pixel 4a 
 - Datadog SDK version: 1.8.1
 - Versions of any other relevant dependencies (OkHttp, …):  -
 - Proguard configuration:  -
 - Gradle Plugins:  -

**Comment by ogartaganis** [comment]
Thanks for the answer and your time @xgouchet, there's only one (default) retention filter active and that's for 100%. 

We also have a backend trace that I'm trying [unsuccessfully till now] to map to, which, however, has a correct sampling of 100%, in contrast to our Android trace.

**Comment by ogartaganis** [comment]
I'm going to close this as it was my bad, it's kinda complicated with the spans and the scopes but as it seems I managed to get all the samples from my Android client.

**Comment by xgouchet** [comment]
Glad you sorted it out, feel free to open a new issue if you have any other question or roadblocks when integrating the SDK.
