### ISSUE TITLE
Failed to resolve (Datadog for Jetpack Compose)

### ISSUE THREAD

**Issue by bicho19** [DataDog/dd-sdk-android#763]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Gradle unnable to resolve dependency implementation on Jetpack Compose project:
Failed to resolve: com.datadoghq:dd-sdk-android-compose:1.11.0-rc1

**Steps to reproduce the issue:**
All Datadog dependencies works well (Android / Timber). but when i added Datadog for Jetpack compose i am getting the error mentioned above.
I even tried to add maver repository too: 
maven { url "https://dl.bintray.com/datadog/datadog-maven" }

**Describe what you expected:**
Gradle download the library as expected.

**Additional context**

**Comment by xgouchet** [comment]
Hi @bicho19 , the Jetpack compose artifact is not yet available in version `1.11.0`. It'll be available in version `1.12.0`, which will be released as soon as possible.
