### ISSUE TITLE
Tracking custom RUM action

### ISSUE THREAD

**Issue by victorlsn** [DataDog/dd-sdk-android#765]
Most of the times I try to create a custom action (addAction for a clicking event, say), it doesn't actually get send to DataDog.
Whenever I click on a button I wanted to log a specific event for, I get something like this:

RUM Action (TAP on ) was dropped, because another action is still active for the same view (I didn't call this one, so I take it's automatically registered)
RUM Action (CLICK on SWITCH_SITE) was dropped, because another action is still active for the same view (this is mine)

I've even removed trackInteractions when building Datadog configuration, but it keeps happening nonetheless.

Am I missing some configuration to actually disable automatic tracking of actions?

**Comment by 0xnm** [comment]
Hello @victorlsn. You can use `CUSTOM` action type with `addAction` call, which is allowed to be sent even if another action is still active.

**Comment by victorlsn** [comment]
Thanks @0xnm! That actually sorts out everything!

**Comment by rupakTj** [comment]
Hello @0xnm - Could you please elaborate this action drop warning ?

**Comment by 0xnm** [comment]
Hello @rupakTj. This is mainly because non-`CUSTOM` actions are representing user interactions and to model things properly in RUM flows we don't allow having multiple user interactions at the same time.

**Comment by rupakTj** [comment]
@0xnm thanks for quick response. In my case its reproduced by following steps ..
Fragment1 -> Fragment2/Activity -> Fragment1 

Once coming back to Fragment1 it shows the Action drop warning. So in this case the action is still active in first fragment ? 

Is there any way to overcome ?

**Comment by 0xnm** [comment]
@rupakTj Can you please open the separate ticket with all the necessary details (like SDK version, which type of the action is performed, etc.)?

**Comment by rupakTj** [comment]
Thanks, created a new bug . here is the link to it https://github.com/DataDog/dd-sdk-android/issues/990#issue-1312685643
