### ISSUE TITLE
Logger not sending logs to Datadog

### ISSUE THREAD

**Issue by bicho19** [DataDog/dd-sdk-android#767]
**Describe what happened**
I have implemented Datadog Android logs collection before and it's working perfectly. But now I am trying to integrate it in a new version (Built with Jetpack compose) and I am not seeing any logs in the dashboard, I even tried with new client key / service name / logger name ... But still cannot see any logs in the dashboard. 

I added the Datadog plant with Timber, it does logs in Logcat but no logs are sent to the dashboard.

My Configurations: 
```
val configuration = Configuration.Builder(
        rumEnabled = false,
        logsEnabled = true,
        tracesEnabled = true,
        crashReportsEnabled = true,
    ).build()

val credentials = Credentials(
        clientToken = "",
        envName = BuildConfig.BUILD_TYPE,
        variant = Credentials.NO_VARIANT,
        serviceName = "seriveName",
        rumApplicationId = "",
    )

val appLogger = Logger.Builder()
            .setNetworkInfoEnabled(true)
            .setLogcatLogsEnabled(true)
            .setDatadogLogsEnabled(true)
            .setLoggerName("logger-name")
            .build();

 Datadog.initialize(
            context = this,
            credentials = credentials,
            configuration = configuration,
            trackingConsent = TrackingConsent.GRANTED,
        )
 if (Datadog.isInitialized()) {
            // Always returns true
            Log.i("Logger", "Log collector is initialized")
        }
```

**Additional context**
 - Android OS version: 11 
 - Datadog SDK version:  1.11.0-rc1

**Comment by xgouchet** [comment]
Hi @bicho19 , can you add the following line before calling `Datadog.initialize(…)` in your configuration code, and let us know if any warning or error is displayed in the Logcat.

```
Datadog.setVerbosity(Log.VERBOSE)
```

**Comment by tomaz** [comment]
I have similar issue, no logs/RUM events in dashboard. I can see warnings in logcat that client token is not valid, but the token is definitely registered in organization settings. The token was created in RUM application "wizard" but also tried with another token I created in org settings, and still same results. Also tried copying sample code from RUM app page (filling in missing values) and still the same.

**Comment by xgouchet** [comment]
Are you login on the `app.datadoghq.com` website, or `us3.datadoghq.com`, `us5.datadoghq.com`, or the european website `app.datadoghq.eu`? Depending on which you're targeting you need to also tell the SDK to upload your data there using the following line in your `Configuration.Builder`: 
```
val configBuilder = Configuration.Builder(
            logsEnabled = true,
            tracesEnabled = true,
            crashReportsEnabled = true,
            rumEnabled = true
        )
        .useSite(DatadogSite.US1) // targets app.datadoghq.com by default
        .useSite(DatadogSite.US3) // targets us3.datadoghq.com 
        .useSite(DatadogSite.US5) // targets us5.datadoghq.com 
        .useSite(DatadogSite.EU1) // targets app.datadoghq.eu 
```

**Comment by tomaz** [comment]
This sounds like plausible reason... We should use EU, and Android is setup as such, but will check with admin to make sure!

**Comment by tomaz** [comment]
Yup, that was the issue - we use US server, leaving default (removing `useSite`) started working!

Just na idea: maybe the warning text can include site selection as suggestion? It wasn't apparent this was the real issue from text.

**Comment by xgouchet** [comment]
Good to know, and indeed, we'll add this as a suggestion to ensure customers check this variable as well.
