### ISSUE TITLE
Invalid application ID and session ID when reporting traces

### ISSUE THREAD

**Issue by msasikanth** [DataDog/dd-sdk-android#811]
Hello. In our app, we are reporting SQL operations traces to Datadog. While it is showing up in the dashboard, the application id and session id seems to be always invalid? 
![image](https://user-images.githubusercontent.com/6140516/149261820-101a5986-512d-4225-9a79-42acf9065aea.png)

We also have RUM configured, but I am not able to see the SQL operations in the RUM events as well. I am guessing this is the reason? 

**Additional context**
 - Android OS version: 12
 - Device Model: Pixel 3
 - Datadog SDK version: 1.11.1

**Comment by xgouchet** [comment]
Hi @msasikanth , and thanks for reporting this issue. Are you creating your AndroidTracer before or after initializing the DatadogSDK? If the tracer is initialized before, it can't link itself to the RUM session and set those attributes properly so this might be the cause. Otherwise, could you share with us the code snippet you use to 
- initialize the SDK
- initialize the Android Tracer
- generate the spans for your SQL calls ?

**Comment by xgouchet** [comment]
Oh good your app's open source. That'll make things easier, i'll take a look right now

**Comment by xgouchet** [comment]
I did a test run and it seems that on my side the RUM information is correctly set, and they do appear in the related RUM View. I tried this in debug mode, and from your code it seems it should be there. Can you reproduce this issue when running a debug build too?

**Comment by msasikanth** [comment]
I have tried it on both debug and release builds. Are you able to see the SQL queries traces in RUM dashboard? 🤔 . I can see UI actions, network responses and other session data. But not the SQL tracing information. Is it possible to see something like that with the SDK currently? 

For example, would it be possible to see the SQL instrumentation data in the session list along with other UI and screen information?

**Comment by xgouchet** [comment]
You won't see them directly in the RUM Dashboard side, but they should appear in a RUM View, in the traces Tab:

<img width="1431" alt="Screenshot 2022-01-13 at 13 32 05" src="https://user-images.githubusercontent.com/818706/149330744-1586f2a3-3d08-4d80-a734-bd84737f2b4f.png">

**Comment by xgouchet** [comment]
Another option for you might be to track SQL queries as RUM Resources. Those will appear the same way as network requests. 

```
class DatadogSqlPerformanceReportingSink : ReportSink {

  override fun begin(operation: SqlOperation) {

    GlobalRum.get().startResource(
        key = "${operation.daoName}.${operation.methodName}.${operation.startTimeMillis}",
        method = "POST", // maybe have a mapper to tag methods as POST/GET/DELETE,
        url = "sql://${operation.daoName}/${operation.methodName}",
        attributes = mapOf(
            "dao" to operation.daoName,
            "method" to operation.methodName
        )
    )
  }

  override fun end(operation: SqlOperation) {
    GlobalRum.get().stopResource(
        key = "${operation.daoName}.${operation.methodName}.${operation.startTimeMillis}",
        statusCode = 200, // maybe use a 400/500 if the query fails,
        size = null,
        kind = RumResourceKind.OTHER,
        attributes = emptyMap()
    )
  }
}
```

**Comment by msasikanth** [comment]
Got it, thanks a lot. I am gonna try out reporting it as a RUM resource. For some reason, I didn't see traces in sessions when using 1.10.0. I have updated to the latest version, gonna see if it works in prod. We can close this issue, for now.

**Comment by xgouchet** [comment]
Thanks, let us know if you have any other question or blocking points.
