### ISSUE TITLE
Documentation link broken - Automatically Track Views

### ISSUE THREAD

**Issue by ccc-dvansevenant** [DataDog/dd-sdk-android#821]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Include any error message or stack trace if available.

In a couple of spots in the documentation (first noted in `https://github.com/DataDog/dd-sdk-android/blob/master/docs/configure_rum_android_sdk.md`) there are references to more information about `Tracking Views` that result in a 404 error, as the link is dead.

**Steps to reproduce the issue:**

Visit [https://github.com/DataDog/dd-sdk-android/blob/master/docs/configure_rum_android_sdk.md](https://github.com/DataDog/dd-sdk-android/blob/master/docs/configure_rum_android_sdk.md), under the `Custom Views` section, follow the `tracking views automatically` link. It will try to take you to [https://github.com/DataDog/dd-sdk-android/blob/master/real_user_monitoring/android/advanced_configuration/#automatically-track-views](https://github.com/DataDog/dd-sdk-android/blob/master/real_user_monitoring/android/advanced_configuration/#automatically-track-views)

**Describe what you expected:**

The link to provide the documentation needed.

**Additional context**

N/A

**Comment by xgouchet** [comment]
Hi @ccc-dvansevenant , thanks a lot for reporting this. We're going to fix this asap.

**Comment by xgouchet** [comment]
This was fixed by #836
