### ISSUE TITLE
Kotlin Glide Instance Implementations

### ISSUE THREAD

**Issue by ccc-dvansevenant** [DataDog/dd-sdk-android#825]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Include any error message or stack trace if available.

- trying to implement DataDog Glide coverage

**Steps to reproduce the issue:**

Read the DataDog Glide docs.

**Describe what you expected:**

Actually implement this.

The documentation seems to be for standard Android implementations and does not take in to account Kotlin implementations where Glide is crated as its own instance and uses the `kapt` methodology noted here: [https://bumptech.github.io/glide/doc/generatedapi.html#kotlin](https://bumptech.github.io/glide/doc/generatedapi.html#kotlin)

Suggestions would be appreciated.

**Additional context**
 - Android OS version:
 - Device Model:
 - Datadog SDK version:
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins:

**Comment by xgouchet** [comment]
Hi, 
our glide implementation is compatible with Kotlin application. As stated in [our documentation](https://github.com/DataDog/dd-sdk-android/tree/master/dd-sdk-android-glide), you only need to write a single class as follow:

```
// the provided list 
@GlideModule
class CustomGlideModule :  DatadogGlideModule(listOf("example.com", "example.eu"))
```

and then apply the `kapt` dependency as mentionned in the Glide's documentation page you linked. You can check how we use this exact method in our sample's [SampleGlideModule](https://github.com/DataDog/dd-sdk-android/blob/master/sample/kotlin/src/main/kotlin/com/datadog/android/sample/picture/SampleGlideModule.kt) and our sample's [`build.gradle.kts`](https://github.com/DataDog/dd-sdk-android/blob/743257ad879e04f7907f161c84934c8fd209652e/sample/kotlin/build.gradle.kts#L158).

**Comment by ccc-dvansevenant** [comment]
Thanks. I did review that, but our Glide is implemented as an interface companion object, so I'm not sure how that would work out. Maybe I'll have to poke at the Glide people.

(snippet)
```
interface GlideInstance {

    companion object {

        private const val FADE_DURATION = 300
        private const val THUMB_SIZE = 0.05f
        private val DISK_CACHE_STRATEGY = DiskCacheStrategy.ALL

        private val TRANSITION_OPTIONS = DrawableTransitionOptions().crossFade(FADE_DURATION)

        @RawRes
        @DrawableRes
        val JPG_PLACEHOLDER: Int = R.drawable.jpg_placeholder

        /**
         * Loads a photo into the provided [view]
         * @param view [ImageView] to load [fileUri] into
         * @param fileUri [String] file uri to load into [view]
         * @param isThumbnail [Boolean] should the image be loaded as a thumbnail
         * @param cacheStrategy [DiskCacheStrategy] cache strategy after the image is loaded
         * @param skipMemoryCache [Boolean] should the load skip the memory cache strategy
         */
        fun loadPhoto(view: ImageView, fileUri: String, isThumbnail: Boolean = true, cacheStrategy: DiskCacheStrategy = DISK_CACHE_STRATEGY, skipMemoryCache: Boolean = false) {
            Glide
                .with(view)
                .load(fileUri)
                .transition(TRANSITION_OPTIONS)
                .thumbnail(if (isThumbnail) THUMB_SIZE else 1f)
                .diskCacheStrategy(cacheStrategy)
                .skipMemoryCache(skipMemoryCache)
                .into(view)
        }
```

**Comment by xgouchet** [comment]
Hi @ccc-dvansevenant , the `GlideModule` and the method you use to call Glide are different things. If you just create an interface somewhere in your codebase like I showed in my snippet, and use the `kapt` line, then it'll bind itself automatically to Glide.

**Comment by ccc-dvansevenant** [comment]
> Hi @ccc-dvansevenant , the `GlideModule` and the method you use to call Glide are different things. If you just create an interface somewhere in your codebase like I showed in my snippet, and use the `kapt` line, then it'll bind itself automatically to Glide.

Ooohhhh! I misunderstood how that worked. I will try that, then. Thank you.

**Comment by ccc-dvansevenant** [comment]
Looks like we were already using kapt to call the glide compiler in our app/build.gradle:

```
dependencies {
...
    // Glide Dependency
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    kapt 'com.github.bumptech.glide:compiler:4.11.0'
...
}
```

So I created the new class file (we try to keep things pretty tight that way) based on your suggested code, and I *seem* to be seeing some new `D/Glide...` messages in my Logcat when I tap on an image:

`D/Glide: Finished loading BitmapDrawable from LOCAL for android.graphics.Bitmap@fdddcdb with size [54x54] in 6.769413 ms`

But I'm not sure I'm seeing anything new in the RUM Session logs.

What should I be seeing, and when?

**Comment by xgouchet** [comment]
Mostly our Glide module will track Glide specific errors that would be silent otherwise: errors thrown form Glide's cache or when Glide tries to fetch images from the network.
