### ISSUE TITLE
Google Play Data Safety disclosure

### ISSUE THREAD

**Issue by chao2zhang** [DataDog/dd-sdk-android#843]
I am working on the data safety for Android apps Google Play. The official documentation for this new privacy policy requirement can be found on this [page](https://support.google.com/googleplay/android-developer/answer/10787469?hl=en). All apps are required to complete by April 2022.

I was not able to find the page where DataDog is disclosing data collection and usage. I am wondering if the data collection and usage are already disclosed, or this is something still being worked on.

If the latter is the case, below are some good examples that disclose the data usage in the desired format:
- https://help.branch.io/using-branch/docs/answering-the-google-play-store-privacy-questions
- https://firebase.google.com/docs/android/play-data-disclosure
- https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/mobile-trackers/android-google-play-data-safety/

**Comment by xgouchet** [comment]
Hi @chao2zhang , you can find the list of data collected oby the Android SDK on [this documentation page](https://docs.datadoghq.com/real_user_monitoring/android/data_collected/?tab=session)

**Comment by xgouchet** [comment]
Great I'll close this ticket for now, feel free to reopen it if you think some details are missing.
