### ISSUE TITLE
Unable to upload logs

### ISSUE THREAD

**Issue by nik-caspeco** [DataDog/dd-sdk-android#844]
**What Happened**
I am unable to see any logging activity in the logging monitor from my android sdk/app. I get no error messages regarding Credentials, Configuration or Logger.Builder; and if I run `Datadog.isInitialized()` that comes back as `true`.
I get only one line of error in logcat:
```
E/Datadog: Batch c0f52efc-60a1-417b-a463-9e7c3b4f8151 [374 bytes] (LogsOkHttpUploaderV2) failed because of a processing error or invalid data; the batch was dropped.
```

**Steps to reproduce the issue:**
I am using the following information
```
Configuration.Builder(
    logsEnabled = true,
    tracesEnabled = false, // same result when true
    crashReportsEnabled = false, // same result when true
    rumEnabled = false
).build()

Credentials(
    clientToken = DATADOG_CLIENT_TOKEN, // ("pub3a86....") token, not app_id
    envName =  "dev"
    variant = BuildConfig.FLAVOR
    rumApplicationId = null,
    serviceName = null
)

Datadog.initialize(
    context = applicationContext,
    credentials = credentials,
    configuration = configuration,
    trackingConsent = TrackingConsent.GRANTED
)

Logger.Builder()
    .setNetworkInfoEnabled(true)
    .setLogcatLogsEnabled(true)
    .setDatadogLogsEnabled(true)
    .build()
```

We do not have a RUM application, and no interest in having one at this point in time.
What I'm then trying to do is simply `logger.i("some_unique_string")`
After a while after sending the log I get the error message that the batch data is broken.

**Expected**
A simple log showing up in the logging monitor ≈ sdk working...

**Additional context**
 - Android OS version: Android 11
 - Device Model: Xperia 1 ii
 - Datadog SDK version: com.datadoghq:dd-sdk-android:1.11.1
 - Versions of any other relevant dependencies (OkHttp, …): OkHttp{
        4.9.2 according to OkHttp.VERSION. Probably through Coil { 1.4.0 }
 - }
 - Proguard configuration: No proguard files setup yet
 - Gradle Plugins: { 'com.android.library', 'kotlin-android', 'kotlin-kapt' }

**Comment by xgouchet** [comment]
Hi @nik-caspeco, when looking at your Datadog account, which website are you using? We have [several different sites](https://docs.datadoghq.com/getting_started/site/) (for example we have data centers in the US and in Europe), and depending on which one you use, you need to setup the SDK accordingly. 
E.g.: if you use the [EU1 site https://app.datadoghq.eu](https://app.datadoghq.eu), then your configuration should look like this: 
```kotlin
val configuration = Configuration.Builder(
        logsEnabled = true,
        tracesEnabled = false, // same result when true
        crashReportsEnabled = false, // same result when true
        rumEnabled = false
    )
    .useSite(DatadogSite.EU1)
    .build()
```

**Comment by nik-caspeco** [comment]
We are using the EU site, great! ^^
I couldn't see anything like this in any of the tutorials / getting started- that would be great.
One piece of feedback I think would be that the logcat output from datadog could also be increased: The only errors I got was if I said I wanted RUM and did't provide an ID for that, and that's when I had it set to verbose.

Thank you!

**Comment by Naktibalda** [comment]
This issue is the only resource about `(LogsOkHttpUploaderV2) failed because of a processing error or invalid data; the batch was dropped.` on internet so I will share my experience that I got this error when I used incorrect client token.

It would be great if error message was more specific.
