### ISSUE TITLE
Add possibility to set minimal log level for DatadogTree

### ISSUE THREAD

**Issue by Gaket** [DataDog/dd-sdk-android#847]
**Is your feature request related to a problem? Please describe.**

We have many Timber Trees in the app, including the standard LogCat one. We use different Log levels, including Verbose which is... verbose by its nature.

Our Non-release builds have LogCat Tree enabled, so we have those Verbose logs. Release trees don't handle Verbose level at all.
It looks like the DatadogTree (or its Logger) is not allowing to set the Log Level

As a result, we have a high-volume Verbose logs sent to Datadog while we are not interested in this info.

**Describe the solution you'd like**
1) Add configuration to set min log level

**Describe alternatives you've considered**
Copypaste DatadogTree and configure it internally - this is my current solution.
Checked out both the Tree and Logger classes, haven't found a better workaround

**Comment by xgouchet** [comment]
Hi @Gaket , indeed that's an interesting feature to add, we'll try and work on this eventually. 
Note that you can submit a PR to implement this faster if you need.
