### ISSUE TITLE
Disable network info does not remove network data from logs

### ISSUE THREAD

**Issue by LarsEliasNielsen** [DataDog/dd-sdk-android#865]
I've tried setting up Datadog logging with Timber a couple of times, but due to restriction on what I am allowed to log I want to exclude network info from the logs, like IP, locations, etc.

This is the logger I'm attempting to set up:

```
val configuration = Configuration.Builder(
    logsEnabled = true,
    tracesEnabled = true,
    crashReportsEnabled = false,
    rumEnabled = false
).run {
    useSite(DatadogSite.EU1)
}.build()

Datadog.initialize(context, credentials, configuration, trackingConsent)
```

```
val logger = Logger.Builder()
    .setNetworkInfoEnabled(false)
    .setLogcatLogsEnabled(false)
    .setDatadogLogsEnabled(true)
    .setBundleWithTraceEnabled(true)
    .build()
Timber.plant(DatadogTree(logger))
```

I'm setting `setNetworkInfoEnabled(false)` but I still see the network info on each log: https://i.imgur.com/9vatwxL.png
Avoiding to call the method above results in the same output; Network info is still attached to each log, even though it should not.

**Comment by xgouchet** [comment]
Hi @LarsEliasNielsen , the geoip information is not collected by the SDK itself but by the backend, based on the request uploading the collected data. You can disable this by removing the default Android pipeline in the Logs setting page on your Datadog account.

**Comment by LarsEliasNielsen** [comment]
Thank you very much for the clarification.
