### ISSUE TITLE
Enabling RUM Collection is hogging the CPU

### ISSUE THREAD

**Issue by nordfalk** [DataDog/dd-sdk-android#884]
When I enable RUM the application is using CPU, even when it is backgrounded.

The following screenshots show output of `adb shell top` on a Samsung S21 running Android 12 
App is started, then back button is pressed to go to out of the app and back to the phone's home screen. 
Then I wait a minute or so, while the app is not visible and not used. 
First is without DD , second is with DD.

![image](https://user-images.githubusercontent.com/1143272/160387701-93441ff1-7cbe-49db-8075-db702bd117c6.png)

![image](https://user-images.githubusercontent.com/1143272/160387770-2a5d7110-56a4-4647-992d-10aec15229c3.png)

Same behaviour has been seen on emulators running API 26, API 28, API 29 and API 30.
I havent seen a phone or emulator that didnt exhibit the problem.

**Describe what happened**
CPU usage by the app (dk.dinero.android) is 22% when RUM is enabled.

**Steps to reproduce the issue:**
Set 
                rumEnabled = true,

**Describe what you expected:**
There should be no CPU usage - like the first image.

**Additional context**
 - Android OS version: All investigated
 - Device Model: All
 - Datadog SDK version: 1.10.0, 1.11.0, 1.12.0-beta1 exhibits the problem
 - Datadog SDK version: 1.9.0 does **not** exhibit the problem

In 1.10.0 you added a [FEATURE] RUM: Track Memory and CPU usage, as well as views' refresh rate.
If you provide advice on how to disable that feature, then I'd be happy to try it out.

This has also been reported to Owen Eoin Phelan.

Yours,
Jacob Nordfalk
Visma Dinero

**Comment by xgouchet** [comment]
Hi @nordfalk , thanks for reporting this. Indeed this is a side effect of our mobile vitals, we're working actively on a fix to disable this when the app is in background (cf #879 ). It will be part of the upcoming sdk version `1.13.0` which will be out in beta in a few weeks.

**Comment by nordfalk** [comment]
Dear @xgouchet thanks for the update.
I just checked out com.datadoghq:dd-sdk-android:1.13.0-beta1 and the problems still seems to be present, as far as I can see.
Should I check more throroughly, or is the fix not merget yet?

**Comment by xgouchet** [comment]
The fix should be merged, I'll make another check to make sure it does work as expected

**Comment by nordfalk** [comment]
It seems to be fixed in 1.13.0-rc1

This is with 1.13.0-rc1:
![image](https://user-images.githubusercontent.com/1143272/172608492-2bad9685-a02a-4f2c-9be4-ebc59c600357.png)

This is with 1.13.0-beta1:
![image](https://user-images.githubusercontent.com/1143272/172607916-d1fd1e4a-127d-44c8-9062-ee3f38539956.png)

This is without datadog:
![image](https://user-images.githubusercontent.com/1143272/172608164-a6f3bcaf-9d5a-4b31-a66e-249e7db13d7c.png)
