### ISSUE TITLE
Where are you uploading DatadogTree to?

### ISSUE THREAD

**Issue by Macarse** [DataDog/dd-sdk-android#90]
Hello!
I am testing out the library and I couldn't figure out where to get `DatadogTree` from.

The README doesn't make sense to me:
https://github.com/DataDog/dd-sdk-android/blame/master/dd-sdk-android-timber/README.md#L14-L15

I also couldn't find the separate library browsing https://dl.bintray.com/datadog/datadog-maven

I ended up copying and pasting the class into my source code.

Thanks!

**Comment by xgouchet** [comment]
Good point Macarse, we'll fix that ASAP.

**Comment by xgouchet** [comment]
The artifact is now available on Bintray, you can add them in your `build.gradle` as follow : 

```
repositories {
    maven { url “https://dl.bintray.com/datadog/datadog-maven" }
}

dependencies {
    implementation "com.datadoghq:dd-sdk-android:1.1.1"
    implementation "com.datadoghq:dd-sdk-android-timber:1.1.1"
}
```

**Comment by Macarse** [comment]
Perfect. Thanks!
