### ISSUE TITLE
Allow ViewEvent.Context.additionalProperties to be mutable

### ISSUE THREAD

**Issue by lgvalle** [DataDog/dd-sdk-android#958]
**Is your feature request related to a problem? Please describe.**
The problem we're facing is we'd like to enrich ViewEvents with custom attributes but `additionalProperties` can't be modified

The approach we're following is to set up `EventMapper<ViewEvent>` to get a callback when a `ViewEvent` is generated.
As it's known you can't clone the viewEvent or it will be discarded. So only a few `var` properties can be modified. The `Context.additionalProperties` is a map that looks like the right place to add extra properties but unfortunately is not mutable.

**Describe the solution you'd like**
Change 
```kotlin
public val additionalProperties: Map<String, Any?> = emptyMap(),
```
to 
```kotlin
public var additionalProperties: Map<String, Any?> = emptyMap()
```
or alternatively to
```kotlin
public val additionalProperties: MutableMap<String, Any?> = mutableMapOf()
```

so extra properties can be added to ViewEvents

**Describe alternatives you've considered**
The alternative we've considered was to write a custom `ViewTrackingStrategy` that will create its own set of `attributes` to track, but it seems overkill for this

**Additional context**
Alternatively consider allowing the injection of custom rules on `RumEventMapper` regarding which events are dropped to, for example, allow events that are not the same instance (aka, allow `.copy()`)

**Comment by xgouchet** [comment]
Hi @lgvalle , thanks alot for this feature request. Indeed for now we don't allow modification of the additional properties, but we are considering adding some APIs to allow enriching the view. 
You can also add custom attributes through the `GlobalRum.addAttribute()` (and similar methods).

**Comment by 0xnm** [comment]
Hello @lgvalle! `ViewEvent.Context.additionalProperties` is now mutable (it has the type `MutableMap<String, Any?>`, this change was done in #1089) and was delivered in the release [1.15.0](https://github.com/DataDog/dd-sdk-android/releases/tag/1.15.0).

I'm closing this issue as your request was implemented, don't hesitate to re-open it if needed.
