### ISSUE TITLE
Seeing unexpected custom actions "back" and "" reported in the DataDog console

### ISSUE THREAD

**Issue by mattttvaughn** [DataDog/dd-sdk-android#964]
**Describe what happened**

I'm setting up DataDog in an Android project and seeing some unexpected custom events being reported. We are seeing two unknown custom events/actions being reported in our DataDog console. We are not calling `GlobalRum.get().addUserAction(RumActionType.CUSTOM, event, attributes)` with either "back" or "" as parameters:

1. "back": there is a custom event being reported with a name/description of "back" that is reported when the Android system back button is pressed.

2. "": we have also seen a custom event reported with no name/description.

Screenshot included below shows both in the DataDog console, filtered by actions with type `custom`:

<img width="416" alt="Screen Shot 2022-06-29 at 2 47 44 PM" src="https://user-images.githubusercontent.com/58408581/176513204-132c9596-e0d1-4697-b4b0-aac877faafe3.png">

**Steps to reproduce the issue:**

1. System back button is pressed, a custom action/event is reported with name "back"

2. Have not reproduced getting the empty name event, but less important to us as it's only ever occurred 2 times during testing.

**Describe what you expected:**

Expecting to only see custom events sent when `GlobalRum.get().addUserAction(RumActionType.CUSTOM, event, attributes)` is called. (Or expecting to see back button reported as a TAP action, maybe)

**Additional context**
 - Android OS version: 10
 - Device Model: Samsung SM-G975U1
 - Datadog SDK version: 1.12.0
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins:

**Comment by xgouchet** [comment]
Hi @mattttvaughn and thanks for reporting this issue. Indeed we do report some actions as custom although they shouldn't be. We will fix this shortly.
