### ISSUE TITLE
Crash on Moto Z

### ISSUE THREAD

**Issue by stevie-patreon** [DataDog/dd-sdk-android#979]
**Describe what happened**
We have a report of multiple crashes coming from the Datadog SDK. The reports occurred on Moto Z(3) running Android 9.

**Steps to reproduce the issue:**
```
Caused by java.lang.UnsupportedOperationException
java.nio.ByteBuffer.putUnchecked (ByteBuffer.java:1587)
com.datadog.android.core.internal.net.FirstPartyHostDetector.addKnownHosts (FirstPartyHostDetector.kt:47)
com.datadog.android.core.internal.CoreFeature.initialize (CoreFeature.kt:134)
com.datadog.android.Datadog.initialize (Datadog.kt:92)
```

**Additional context**
 - Android OS version: 9
 - Device Model: Moto Z(3)
 - Datadog SDK version: 1.12.0
 - Versions of any other relevant dependencies (OkHttp, …): OkHttp: 4.9.3
 - Proguard configuration: n/a
 - Gradle Plugins: Hilt, Kotlin-Android, KAPT, Realm, GMS, Crashlytics, Firebase Perf

**Comment by stevie-patreon** [comment]
The layers below this in the stacktrace are our own codebase. The entry point for this is `Application.onCreate`

**Comment by 0xnm** [comment]
The connection between `com.datadog.android.core.internal.net.FirstPartyHostDetector.addKnownHosts` and `java.nio.ByteBuffer.putUnchecked` is unclear from the given stacktrace, there is nothing evident in the `addKnownHosts` method body in the [version you are using](https://github.com/DataDog/dd-sdk-android/blob/dd17b905895e1e53ef5c7a6575be83870b661ef6/dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/FirstPartyHostDetector.kt#L36).

I believe it should be some layers between them which are not a part of your app, can you please add them?

Also does this crash happen only on Moto Z(3) running Android 9?

**Comment by stevie-patreon** [comment]
Our only known instance of it is on Moto Z(3) using Android 9. Unfortunately, that trace is from Firebase and there doesn't seem to be any more of the stack trace available

**Comment by 0xnm** [comment]
Unfortunately there is not enough information to trace the issue. We will appreciate if any additional information is provided regarding this crash, I will leave this ticket open for a while.

**Comment by 0xnm** [comment]
I'm closing this ticket, because no additional info was provided and we didn't see any other reports like this.
