### ISSUE TITLE
RUM Action Dropped, because another action is still active for the same view

### ISSUE THREAD

**Issue by rupakTj** [DataDog/dd-sdk-android#990]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Console - datadog showing RUM Action (TAP on ) was dropped, because another action is still active for the same view

**Steps to reproduce the issue:**
Fragment 1 -> Fragement 2 / Activity -> press back -> and it show the Warning of RUM action dropped

Note :- though it shows warning still the Action is recorded in RUM.

One more way to reproduce -

GlobalRum.get().startUserAction(RumActionType.CUSTOM, eventName, extraData)
GlobalRum.get().addUserAction(RumActionType.CUSTOM, eventName, extraData)
GlobalRum.get().stopUserAction(RumActionType.CUSTOM, eventName, extraData) 

The above will show warning 
RUM Action (CUSTOM on "eventName") was dropped, because another action is still active for the same view

**Describe what you expected:**
How to fix / avoid Action drop warning.

**Additional context**
 - Android OS version: - 12
 - Device Model: - Checked on Emulator and One Plus as well
 - Datadog SDK version: - com.datadoghq:dd-sdk-android:1.13.0
 - Versions of any other relevant dependencies (OkHttp, …): retrofit - 2.9.0 , okhttp3.okhttp.okhttpclient- 3.14.9
 - Proguard configuration: not enabled
 - Gradle Plugins: Gradle - 4.1.3

Code - for initialising - Datadog

 ```
val configuration = Configuration.Builder(
            rumEnabled = true,
            crashReportsEnabled = true,
            logsEnabled = true,
            tracesEnabled = true
        ).trackInteractions()
            .useSite(DatadogSite.US1)
            .trackBackgroundRumEvents(true) // may impact billing as additional sessions created
            .setUploadFrequency(UploadFrequency.AVERAGE)
            .setUseDeveloperModeWhenDebuggable(BuildConfig.DEBUG)
            .useViewTrackingStrategy(MixedViewTrackingStrategy(trackExtras = true))
            .setBatchSize(BatchSize.MEDIUM)
            .build()

        val credentials = Credentials(clientToken, environmentName, appVariantName, applicationId)
        Datadog.initialize(this, credentials, configuration, TrackingConsent.GRANTED)
        GlobalRum.registerIfAbsent(RumMonitor.Builder().build())
```

**Comment by xgouchet** [comment]
Hi @rupakTj , you're mentioning that this happen while also navigating and pressing the back button. With just the three lines you provided, we were unable to reproduce the issue, could you please provide more context around your example?

**Comment by 0xnm** [comment]
Closing this ticket due to inactivity, feel free to re-open it if you still experience this issue.
